---
modules-search: [ local, @out@/lib/calamares/modules ]

instances:
- id:       unfree
  module:   notesqml
  config:   unfree.conf
- id:       naming
  module:   packagechooser
  config:   packagechooser-naming.conf
- id:       debug
  module:   packagechooser
  config:   packagechooser-debug.conf
- module:   nixos
  weight:   48

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - users
  - packagechooser
  - packagechooser@naming
  - packagechooser@debug
  - notesqml@unfree
  - partition
  - summary
- exec:
  - partition
  - mount
  - nixos
  - users
  - umount
- show:
  - finished

branding: nixos

prompt-install: false
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
hide-back-and-next-during-exec: false
quit-at-end: false
