# Generated by the finix installer: finix branding fixes.
{
  config,
  pkgs,
  lib,
  inputs,
  ...
}:
let
  cfg = config.programs.limine;

  # Same JSON the upstream module builds (modules/programs/limine/
  # providers.bootloader.nix at the pinned finix revision).
  limineInstallConfig = pkgs.writeText "limine-install.json" (
    builtins.toJSON {
      inherit (cfg)
        additionalFiles
        biosDevice
        biosSupport
        efiSupport
        enrollConfig
        extraEntries
        force
        partitionIndex
        settings
        validateChecksums
        secureBoot
        ;

      nixPath = config.services.nix-daemon.package;
      efiBootMgrPath = pkgs.efibootmgr;
      liminePath = cfg.package;
      efiMountPoint = config.boot.loader.efi.efiSysMountPoint;
      fileSystems = config.fileSystems;
      canTouchEfiVariables = config.boot.loader.efi.canTouchEfiVariables;
      efiRemovable = cfg.efiInstallAsRemovable;
      maxGenerations = if cfg.maxGenerations == null then 0 else cfg.maxGenerations;
      hostArchitecture = pkgs.stdenv.hostPlatform.parsed.cpu;
      fwupdEfiPath = config.services.fwupd.package or null;
    }
  );

  # Upstream limine-install.py with the boot menu group renamed
  # "NixOS ..." -> "finix ..." (keeps the @python3@/@configPath@
  # placeholders for replaceVarsWith below).
  patchedInstallScript =
    pkgs.runCommand "limine-install-finix.py" { } ''
      sed -e "s|/+NixOS {group_name}|/+finix {group_name}|" \
        ${inputs.finix}/modules/programs/limine/limine-install.py > $out
    '';
in
{
  config = lib.mkIf (config.providers.bootloader.backend or null == "limine") {
    providers.bootloader.installHook = lib.mkForce (
      pkgs.replaceVarsWith {
        src = patchedInstallScript;
        isExecutable = true;
        replacements = {
          python3 = pkgs.python3.withPackages (python-packages: [ python-packages.psutil ]);
          configPath = limineInstallConfig;
        };
      }
    );
  };
}
