# finix system configuration, generated by the finix installer.
# finix uses finit as PID 1 (no systemd), mdevd+seatd (or eudev+elogind when
# KDE Plasma is installed), and the Nix package manager.
# Edit this file, then rebuild with:  sudo finix-rebuild switch
# (the system flake lives in /etc/finix)

{ config, pkgs, ... }:

{
  imports =
    [ # Include the results of the hardware scan.
      ./hardware-configuration.nix
    ];

  # --- finix core (finit init + Nix daemon) ---
  finit.runlevel = 3;
  finit.services.nix-daemon.environment.CURL_CA_BUNDLE = config.security.pki.caBundle;
  services.nix-daemon.enable = true;
  services.nix-daemon.settings.experimental-features = [ "nix-command" "flakes" ];
  services.nix-daemon.settings.trusted-users = [ "root" "@wheel" ];

  # --- logging / policy (finix replacements for systemd bits) ---
  # (the device manager — mdevd or eudev — is emitted with the seat
  # management block below; the two choices are coupled)
  services.dbus.enable = true;
  services.sysklogd.enable = true;
  services.polkit.enable = true;

  programs.sudo.enable = true;
  programs.bash.enable = true;
  hardware.graphics.enable = true;
  fonts.fontconfig.enable = true;
  fonts.enableDefaultPackages = true;

  # Bootloader: limine (UEFI).
  programs.limine.enable = true;
  programs.limine.efiSupport = true;
  programs.limine.settings.editor_enabled = true;
  # No distro artwork behind the boot menu (the finix limine module defaults
  # to a NixOS wallpaper); keep the plain dark backdrop instead.
  programs.limine.settings.wallpaper = [ ];
  boot.loader.efi.canTouchEfiVariables = true;

  # Low-RAM machine (detected at install time): build one derivation at a
  # time with limited compiler jobs, so system updates that recompile the
  # finix-patched packages (compositors, PipeWire, Noctalia) stay safe.
  # Raise these if you add RAM. Delete to return to Nix defaults.
  services.nix-daemon.settings.max-jobs = 1;
  services.nix-daemon.settings.cores = 4;

  # --- device manager + seat management: eudev + elogind ---
  # (required by KDE Plasma / KWin; elogind needs the udev database for
  # TakeDevice, so the device manager is eudev instead of mdevd here)
  services.udev.enable = true;
  services.elogind.enable = true;
  # finix xorg-module quirk: its udevApi is null under eudev, which builds
  # xorg-server without any libudev and fails; link eudev's libudev in.
  programs.xorg.package = pkgs.xorg-server.override { udev = pkgs.eudev; };

  # Let wheel users power off / reboot / suspend through elogind without a
  # password. The default policy answers "challenge", and desktop power
  # buttons (Noctalia, Plasma) launch `loginctl poweroff` detached — the
  # prompt has nowhere to go, so the button silently does nothing.
  services.polkit.extraConfig = ''
    polkit.addRule(function(action, subject) {
      if (subject.isInGroup("wheel") &&
          (action.id.indexOf("org.freedesktop.login1.power-off") == 0 ||
           action.id.indexOf("org.freedesktop.login1.reboot") == 0 ||
           action.id.indexOf("org.freedesktop.login1.suspend") == 0 ||
           action.id.indexOf("org.freedesktop.login1.hibernate") == 0)) {
        return polkit.Result.YES;
      }
    });
  '';

  # --- networking (dhcpcd + iwd; no NetworkManager/systemd) ---
  services.dhcpcd.enable = true;
  services.dhcpcd.extraArgs = [ "--noipv6rs" ];
  services.iwd.enable = true;
  programs.resolvconf.enable = true;
  programs.resolvconf.settings.name_servers_append = [ "1.1.1.1" "1.0.0.1" ];
  # glibc reads at most three nameservers (MAXNS); a router advertising itself
  # over v4 + two v6 addresses fills all three, so the append above drops out
  # exactly where a fallback would matter.  Bound the wait instead: the default
  # timeout:5 attempts:2 stalls every lookup for half a minute when a resolver
  # is dead, which is what "connected but the page never loads" looks like.
  programs.resolvconf.settings.resolv_conf_options = [ "timeout:2" "attempts:2" ];
  # openresolv is built with RESTARTCMD="initctl restart $1" and iwd, which
  # calls resolvconf, has no initctl on its PATH; make the hook a no-op rather
  # than log "initctl: command not found" on every DNS update.
  programs.resolvconf.settings.libc_restart = "true";

  networking.hostName = "finix"; # Define your hostname.
  # networking.wireless.enable = true;  # Enables wireless support via wpa_supplicant.

  # Configure network proxy if necessary
  # networking.proxy.default = "http://user:password@proxy:port/";
  # networking.proxy.noProxy = "127.0.0.1,localhost,internal.domain";

  # Set your time zone.
  time.timeZone = "Europe/Bucharest";

  # Select internationalisation properties.
  i18n.defaultLocale = "en_US.UTF-8";

  # --- login: regreet (GTK) under cage ---
  # cage drives its own DRM output instead of painting a VT, so the console
  # handover that blanks tuigreet's already-drawn frame cannot reach it.  The
  # module sets services.greetd.settings.default_session.command itself, so
  # nothing here may define that option too.
  programs.regreet.enable = true;
  # regreet appends /xsessions and /wayland-sessions to every XDG_DATA_DIRS
  # entry and otherwise falls back to /usr/share/..., which does not exist
  # here; greetd's PAM stack exports no environment, so without this the
  # session list comes up empty.
  programs.regreet.compositor.environment.XDG_DATA_DIRS = "/run/current-system/sw/share";
  programs.regreet.settings.background = {
    path = "/etc/finix/wallpaper.png";
    fit = "Cover";
  };
  programs.regreet.settings.GTK.application_prefer_dark_theme = true;
  services.greetd.settings.terminal.vt = 1;
  services.getty.ttys = [ "tty2" "tty3" "tty4" "tty5" "tty6" ];

  # --- audio: PipeWire + WirePlumber (started by the session launchers) ---
  programs.pipewire.enable = true;
  programs.pipewire.alsa.enable = true;
  programs.wireplumber.enable = true;
  services.rtkit.enable = true;
  users.groups.audio.gid = config.ids.gids.audio;

  # --- desktop: labwc (lightweight Wayland compositor) ---
  programs.labwc.enable = true;

  # --- desktop: labwc + Noctalia shell (bar, launcher, lock, OSD) ---

  # --- desktop: LXQt (full desktop environment, Wayland session on labwc) ---
  programs.lxqt.enable = true;

  # --- desktop: KDE Plasma 6 (Wayland; experimental on finix) ---
  programs.plasma.enable = true;

  # --- desktop: Sway (i3-like tiling Wayland compositor) ---
  programs.sway.enable = true;

  # --- desktop: Niri (scrollable-tiling Wayland compositor) ---
  programs.niri.enable = true;

  # --- desktop: Niri + Noctalia shell (with xwayland-satellite) ---
  programs.xwayland-satellite.enable = true;

  # --- desktop: vxwm (versatile dwm-style X11 tiling WM) ---
  programs.xorg.enable = true;
  programs.xinit.enable = true;

  # --- desktop: newm (touchpad-centric Wayland compositor, pywm) ---

  # --- desktop: Mango / MangoWC (dwl-based tiling Wayland compositor) ---
  programs.mango.enable = true;

  # --- desktop: Mango + Noctalia shell ---

  # --- desktop: NVWM (vim-inspired tiling X11 window manager) ---

  # Define a user account. Don't forget to set a password with ‘passwd’.
  users.users."tester" = {
    isNormalUser = true;
    description = "Tester";
    extraGroups = [ "wheel" "video" "audio" ];
    packages = with pkgs; [];
  };

  # List packages installed in system profile. To search, run:
  # $ nix search wget
  environment.systemPackages = with pkgs; [
    vim
    git
    wget
    iproute2 # `ip addr` & friends — finix's base ships no network CLI at all
    iputils # ping; without it every "is the net up?" check fails with
    # "ping: command not found" on a fresh install
    pciutils # lspci — invaluable for GPU/driver debugging
    foot # Wayland terminal
    firefox # web browser (plain package; finix has no programs.firefox module)
    # usermod & friends in /run/current-system/sw/bin: the installer's password
    # step runs `chroot <target> usermod -p <hash> <user>` and resolves the
    # binary through the target's PATH; finix's shadow module only ships the
    # setuid wrappers (su/passwd), not the plain tools. Also useful post-install.
    shadow
    # `sudo finix-rebuild switch` (or boot): stages /etc/finix into git —
    # required, the flake only sees git-tracked files — then rebuilds.
    (writeShellScriptBin "finix-rebuild" ''
      set -e
      ${git}/bin/git -C /etc/finix add -A
      exec ${nixos-rebuild}/bin/nixos-rebuild "''${1:-switch}" --flake /etc/finix#finixos "''${@:2}"
    '')
    # fastfetch: stock binary; the finix-recolored NixOS snowflake comes from
    # /etc/xdg/fastfetch/config.jsonc (below). A user config in
    # ~/.config/fastfetch/ overrides it entirely — standard fastfetch behavior.
    fastfetch
    # `neofetch` = neowofetch (the maintained neofetch fork from hyfetch;
    # upstream neofetch is dead and was removed from nixpkgs). It has no
    # system-wide config file, so only the two logo flags are baked in
    # (os-release ID=finix is unknown to it and would show Tux); everything
    # else, including ~/.config/neofetch/config.conf, works as usual.
    # Colors: 1 = red, 8 = gray.
    # distro= preset: neowofetch checks for /etc/NIXOS (which the NixOS
    # activation machinery creates and finix keeps — do NOT delete it)
    # BEFORE reading os-release, so it would print "OS: NixOS ...".
    # get_distro() starts with `[[ $distro ]] && return`, and environment
    # variables are visible as shell variables to the script — presetting
    # distro skips detection entirely.
    (writeShellScriptBin "neofetch" ''
      exec env distro="finix $(uname -m)" ${hyfetch}/bin/neowofetch --ascii_distro nixos --ascii_colors 1 8 1 8 1 8 "$@"
    '')
  ];

  # Default fastfetch config: any direct invocation of a stock fastfetch
  # binary also gets the finix-recolored NixOS snowflake instead of Tux.
  # The "modules" list MUST be spelled out: with a config file present,
  # fastfetch does not fall back to its built-in module list — a logo-only
  # config prints the logo and nothing else (verified on 2.x).
  environment.etc."xdg/fastfetch/config.jsonc".text = builtins.toJSON {
    logo = {
      source = "nixos";
      color = {
        "1" = "31";
        "2" = "90";
        "3" = "31";
        "4" = "90";
        "5" = "31";
        "6" = "90";
      };
    };
    modules = [
      "title" "separator" "os" "host" "kernel" "uptime" "packages" "shell"
      "display" "de" "wm" "wmtheme" "theme" "icons" "font" "cursor"
      "terminal" "terminalfont" "cpu" "gpu" "memory" "swap" "disk"
      "localip" "battery" "poweradapter" "locale" "break" "colors"
    ];
  };

  # Enable the OpenSSH daemon (optional).
  # services.openssh.enable = true;

  # NOTE: finix does not use NixOS's system.stateVersion; it is intentionally omitted.
}
