# KDE Plasma 6 on finix, generated by the finix installer.
# Based on the WIP upstream module (finix branch modules/plasma).
{
  config,
  pkgs,
  lib,
  ...
}:
let
  cfg = config.programs.plasma;

  inherit (pkgs) kdePackages;

  # start audio in-session, refresh the kservice cache, start plasma.
  # config.programs.*.package (not pkgs.*): under mdevd pipewire is
  # rebuilt against libudev-zero
  sessionScript = pkgs.writeShellScript "plasma-session" ''
    ${config.programs.pipewire.package}/bin/pipewire &
    ${config.programs.wireplumber.package}/bin/wireplumber &
    ${config.programs.pipewire.package}/bin/pipewire-pulse &
    ${kdePackages.kservice}/bin/kbuildsycoca6 || true
    # greetd sessions have no visible stderr, so a Plasma that comes up as a
    # black screen with a cursor (kwin_wayland alive, plasmashell not) leaves
    # nothing to look at.  Log to $HOME, not $XDG_RUNTIME_DIR: the latter is
    # tmpfs and the evidence evaporates on reboot, which is exactly when it
    # is needed.
    exec ${kdePackages.plasma-workspace}/bin/startplasma-wayland       >"$HOME/plasma.log" 2>&1
  '';

  sessionFile = pkgs.writeTextDir "share/wayland-sessions/plasma.desktop" ''
    [Desktop Entry]
    Name=Plasma (Wayland)
    Comment=KDE Plasma Desktop
    Exec=${pkgs.dbus}/bin/dbus-run-session -- ${sessionScript}
    Type=Application
    DesktopNames=KDE
  '';

  # look-and-feel package: breeze dark + finix wallpaper; user settings win
  lnfMetadata = pkgs.writeTextDir "share/plasma/look-and-feel/org.finix.desktop/metadata.json" (
    builtins.toJSON {
      KPackageStructure = "Plasma/LookAndFeel";
      KPlugin = {
        Id = "org.finix.desktop";
        Name = "finix";
        Description = "Breeze Dark with the finix wallpaper";
      };
      "X-Plasma-APIVersion" = "2";
    }
  );
  lnfDefaults = pkgs.writeTextDir "share/plasma/look-and-feel/org.finix.desktop/contents/defaults" ''
    [kdeglobals][KDE]
    widgetStyle=Breeze
    [kdeglobals][General]
    ColorScheme=BreezeDark
    [kdeglobals][Icons]
    Theme=breeze-dark
    [plasmarc][Theme]
    name=default
    [Wallpaper]
    Image=/etc/finix/wallpaper.png
  '';
in
{
  options.programs.plasma = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Whether to enable the KDE Plasma 6 Wayland session.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    # kwin creates its Xwayland sockets inside /tmp/.X11-unix and treats the
    # directory as part of the installation: when it is missing, Xwayland is
    # skipped and an X11-dependent step of the Plasma startup dies before
    # plasmashell ever runs -- black screen, only the kwin cursor.  systemd
    # distros create it via tmpfiles; on finix only xwayland-satellite's
    # module ships the rule, so a Plasma pick without niri-noctalia booted
    # without it.  (It "worked" whenever an X11 session had run first in the
    # same boot: Xorg creates the directory itself.)  Same rules as the
    # xwayland-satellite module.
    finit.tmpfiles.rules = [
      "D! /tmp/.X11-unix  1777 root root"
      "z  /tmp/.X11-unix"
    ];

    # Battery / power management backend for powerdevil.
    services.upower.enable = true;

    environment.systemPackages = with kdePackages; [
      # session entry point
      (lib.hiPrio sessionFile)

      # Qt Wayland support
      qtwayland
      qtsvg
      qtimageformats

      # kwin + the xwayland binary it lazy-spawns; without xwayland every
      # X11 client connecting to :0 hangs and session startup blocks
      kwin
      pkgs.xwayland

      # core plasma (mirrors nixos/modules/services/desktop-managers/plasma6.nix
      # requiredPackages, minus systemd-only bits)
      plasma-workspace
      plasma-desktop
      kscreen
      libkscreen
      kscreenlocker
      kactivitymanagerd
      kglobalacceld
      kwrited
      baloo
      milou
      kmenuedit
      kinfocenter
      plasma-systemmonitor
      ksystemstats
      libksysguard
      systemsettings
      kcmutils
      kdeplasma-addons
      pkgs.xdg-user-dirs

      # KDE frameworks needed at runtime
      frameworkintegration
      kauth
      kcoreaddons
      kded
      kfilemetadata
      kguiaddons
      kiconthemes
      kimageformats
      kio
      kio-admin
      kio-extras
      kio-fuse
      knighttime
      kpackage
      kservice
      kunifiedpush
      solid
      plasma-activities
      phonon-vlc

      # QML / Qt plugins needed by plasmashell
      libplasma
      qqc2-desktop-style
      kde-cli-tools

      # theme
      breeze
      breeze-icons
      breeze-gtk
      kde-gtk-config
      ocean-sound-theme
      pkgs.hicolor-icon-theme
      qqc2-breeze-style
      # finix default look-and-feel (wallpaper + Breeze Dark)
      lnfMetadata
      lnfDefaults

      # polkit agent
      polkit-kde-agent-1

      # platform integration
      plasma-integration

      drkonqi

      # audio + power applets; no plasma-nm (networking is dhcpcd + iwd,
      # wifi via iwgtk/iwctl)
      plasma-pa
      powerdevil
      pkgs.iwgtk

      # wallet (plasma-nm stores Wi-Fi passphrases here)
      kwallet
      kwalletmanager

      # beginner-friendly default applications
      dolphin
      konsole
      kate
      ark
      gwenview
      okular
      spectacle
      kdegraphics-thumbnailers
    ];

    environment.pathsToLink = [
      "/share"

      # for drkonqi
      "/libexec"
    ];

    security.pam.environment =
      let
        qtVersions = with pkgs; [
          qt5
          qt6
        ];
      in
      {
        QT_PLUGIN_PATH.default = map (qt: "/run/current-system/sw/${qt.qtbase.qtPluginPrefix}") qtVersions;
        QML2_IMPORT_PATH.default = map (qt: "/run/current-system/sw/${qt.qtbase.qtQmlPrefix}") qtVersions;

        # /etc/xdg holds the finix default kdeglobals below
        XDG_CONFIG_DIRS.default = [
          "@{HOME}/.config/kdedefaults"
          "/etc/xdg"
        ];

        KPACKAGE_DEP_RESOLVERS_PATH.default = [
          "${kdePackages.frameworkintegration.out}/libexec/kf6/kpackagehandlers"
        ];
      };

    # default look-and-feel for new users; system settings override it
    environment.etc."xdg/kdeglobals".text = ''
      [KDE]
      LookAndFeelPackage=org.finix.desktop
    '';

    # kscreenlocker authenticates through the "kde" PAM service
    security.pam.services.kde.text = ''
      auth      substack      login
      account   include       login
      password  substack      login
      session   include       login
    '';

    security.wrappers = {
      kwin_wayland = {
        owner = "root";
        group = "root";
        capabilities = "cap_sys_nice+ep";
        source = "${lib.getBin pkgs.kdePackages.kwin}/bin/kwin_wayland";
      };
    };

    xdg.portal.portals = [
      pkgs.kdePackages.xdg-desktop-portal-kde
      pkgs.xdg-desktop-portal-gtk
    ];
  };
}
