# KDE Plasma 6 on Finix — generated by the Finix installer.
# Based on the WIP upstream module (finix branch modules/plasma), extended
# with audio startup, network/audio applets and default applications.
{
  config,
  pkgs,
  lib,
  ...
}:
let
  cfg = config.programs.plasma;

  inherit (pkgs) kdePackages;

  # Start the PipeWire audio stack inside the session (Finix has no systemd
  # user units), refresh the KService cache, then hand over to Plasma.
  # startplasma detects the missing systemd user manager and logs
  # "Using classic boot" (plasma_session) — the supported non-systemd path.
  # IMPORTANT: config.programs.*.package, not pkgs.* — under mdevd the
  # PipeWire packages are rebuilt against libudev-zero.
  sessionScript = pkgs.writeShellScript "plasma-session" ''
    ${config.programs.pipewire.package}/bin/pipewire &
    ${config.programs.wireplumber.package}/bin/wireplumber &
    ${config.programs.pipewire.package}/bin/pipewire-pulse &
    ${kdePackages.kservice}/bin/kbuildsycoca6 || true
    exec ${kdePackages.plasma-workspace}/bin/startplasma-wayland
  '';

  sessionFile = pkgs.writeTextDir "share/wayland-sessions/plasma.desktop" ''
    [Desktop Entry]
    Name=Plasma (Wayland)
    Comment=KDE Plasma Desktop
    Exec=${pkgs.dbus}/bin/dbus-run-session -- ${sessionScript}
    Type=Application
    DesktopNames=KDE
  '';
in
{
  options.programs.plasma = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Whether to enable the KDE Plasma 6 Wayland session.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    # Battery / power management backend for powerdevil.
    services.upower.enable = true;

    environment.systemPackages = with kdePackages; [
      # session entry point
      (lib.hiPrio sessionFile)

      # Qt Wayland support
      qtwayland
      qtsvg
      qtimageformats

      # compositor + the Xwayland binary KWin lazy-spawns for X11 apps.
      # Without pkgs.xwayland any X11 client connecting to :0 hangs forever
      # (KWin accepts the connection, fails to start Xwayland, never answers):
      # xrdb from a phase-0 kcminit module then blocks the whole
      # plasma_session startup: a black screen with only a cursor.
      kwin
      pkgs.xwayland

      # core plasma (mirrors nixos/modules/services/desktop-managers/plasma6.nix
      # requiredPackages, minus systemd-only bits)
      plasma-workspace
      plasma-desktop
      kscreen
      libkscreen
      kscreenlocker
      kactivitymanagerd
      kglobalacceld
      kwrited
      baloo
      milou
      kmenuedit
      kinfocenter
      plasma-systemmonitor
      ksystemstats
      libksysguard
      systemsettings
      kcmutils
      kdeplasma-addons
      pkgs.xdg-user-dirs

      # KDE frameworks needed at runtime
      frameworkintegration
      kauth
      kcoreaddons
      kded
      kfilemetadata
      kguiaddons
      kiconthemes
      kimageformats
      kio
      kio-admin
      kio-extras
      kio-fuse
      knighttime
      kpackage
      kservice
      kunifiedpush
      solid
      plasma-activities
      phonon-vlc

      # QML / Qt plugins needed by plasmashell
      libplasma
      qqc2-desktop-style
      kde-cli-tools

      # theme
      breeze
      breeze-icons
      breeze-gtk
      kde-gtk-config
      ocean-sound-theme
      pkgs.hicolor-icon-theme
      qqc2-breeze-style

      # polkit agent
      polkit-kde-agent-1

      # platform integration
      plasma-integration

      drkonqi

      # audio + power applets (PipeWire and upower are enabled when this
      # session is selected; these are gated on NixOS-only options upstream
      # so they must be listed explicitly). NOTE: no plasma-nm — Finix
      # networking is dhcpcd + iwd (NetworkManager reads the udev database,
      # which mdevd does not provide);
      # Wi-Fi is managed with iwgtk (GUI) or iwctl.
      plasma-pa
      powerdevil
      pkgs.iwgtk

      # wallet (plasma-nm stores Wi-Fi passphrases here)
      kwallet
      kwalletmanager

      # beginner-friendly default applications
      dolphin
      konsole
      kate
      ark
      gwenview
      okular
      spectacle
      kdegraphics-thumbnailers
    ];

    environment.pathsToLink = [
      "/share"

      # for drkonqi
      "/libexec"
    ];

    security.pam.environment =
      let
        qtVersions = with pkgs; [
          qt5
          qt6
        ];
      in
      {
        QT_PLUGIN_PATH.default = map (qt: "/run/current-system/sw/${qt.qtbase.qtPluginPrefix}") qtVersions;
        QML2_IMPORT_PATH.default = map (qt: "/run/current-system/sw/${qt.qtbase.qtQmlPrefix}") qtVersions;

        XDG_CONFIG_DIRS.default = [ "@{HOME}/.config/kdedefaults" ];

        KPACKAGE_DEP_RESOLVERS_PATH.default = [
          "${kdePackages.frameworkintegration.out}/libexec/kf6/kpackagehandlers"
        ];
      };

    # kscreenlocker authenticates through the "kde" PAM service — without it
    # the lock screen can never verify the password (user locked out).
    security.pam.services.kde.text = ''
      auth      substack      login
      account   include       login
      password  substack      login
      session   include       login
    '';

    security.wrappers = {
      kwin_wayland = {
        owner = "root";
        group = "root";
        capabilities = "cap_sys_nice+ep";
        source = "${lib.getBin pkgs.kdePackages.kwin}/bin/kwin_wayland";
      };
    };

    xdg.portal.portals = [
      pkgs.kdePackages.xdg-desktop-portal-kde
      pkgs.xdg-desktop-portal-gtk
    ];
  };
}
