# Generated by the finix installer: session launchers and packages for
# the selected desktop sessions (Noctalia shell variants, NVWM).
{
  config,
  pkgs,
  lib,
  inputs,
  ...
}:
let
  # start the PipeWire audio stack inside the user session (finix ships
  # no service for it). IMPORTANT: use config.programs.*.package, not
  # pkgs.* — under mdevd the packages are rebuilt against libudev-zero.
  audioStart = ''
    ${config.programs.pipewire.package}/bin/pipewire &
    ${config.programs.wireplumber.package}/bin/wireplumber &
    ${config.programs.pipewire.package}/bin/pipewire-pulse &
  '';

  # Noctalia v5 desktop shell, built from the pinned source against the
  # same nixpkgs as the rest of the system
  noctalia = pkgs.callPackage (inputs.noctalia-src + "/nix/package.nix") { };

  session-labwc-noctalia = pkgs.writeShellScript "session-labwc-noctalia" ''
    ${config.programs.labwc.package}/bin/labwc &
    comp=$!
    sock=""
    i=0
    while [ $i -lt 100 ]; do
      for s in "$XDG_RUNTIME_DIR"/wayland-*; do
        case "$s" in
          *.lock) ;;
          *) if [ -S "$s" ]; then sock="$(basename "$s")"; break; fi ;;
        esac
      done
      [ -n "$sock" ] && break
      i=$((i + 1))
      sleep 0.1
    done
    if [ -n "$sock" ]; then
      export WAYLAND_DISPLAY="$sock"
      # first XWayland display on a fresh boot
      export DISPLAY=:0
      ${audioStart}
      ${noctalia}/bin/noctalia --daemon &
    fi
    wait "$comp"
  '';

  session-niri-noctalia = pkgs.writeShellScript "session-niri-noctalia" ''
    ${config.programs.niri.package}/bin/niri --session &
    comp=$!
    sock=""
    i=0
    while [ $i -lt 100 ]; do
      for s in "$XDG_RUNTIME_DIR"/wayland-*; do
        case "$s" in
          *.lock) ;;
          *) if [ -S "$s" ]; then sock="$(basename "$s")"; break; fi ;;
        esac
      done
      [ -n "$sock" ] && break
      i=$((i + 1))
      sleep 0.1
    done
    if [ -n "$sock" ]; then
      export WAYLAND_DISPLAY="$sock"
      # first XWayland display on a fresh boot
      export DISPLAY=:0
      i=0
      while [ $i -lt 20 ]; do
        for ns in "$XDG_RUNTIME_DIR"/niri.*.sock; do
          if [ -S "$ns" ]; then export NIRI_SOCKET="$ns"; break 2; fi
        done
        i=$((i + 1))
        sleep 0.1
      done
      ${audioStart}
      ${noctalia}/bin/noctalia --daemon &
    fi
    wait "$comp"
  '';

  session-mango-noctalia = pkgs.writeShellScript "session-mango-noctalia" ''
    ${config.programs.mango.package}/bin/mango &
    comp=$!
    sock=""
    i=0
    while [ $i -lt 100 ]; do
      for s in "$XDG_RUNTIME_DIR"/wayland-*; do
        case "$s" in
          *.lock) ;;
          *) if [ -S "$s" ]; then sock="$(basename "$s")"; break; fi ;;
        esac
      done
      [ -n "$sock" ] && break
      i=$((i + 1))
      sleep 0.1
    done
    if [ -n "$sock" ]; then
      export WAYLAND_DISPLAY="$sock"
      # first XWayland display on a fresh boot
      export DISPLAY=:0
      ${audioStart}
      ${noctalia}/bin/noctalia --daemon &
    fi
    wait "$comp"
  '';

  # NVWM: vim-inspired tiling X11 window manager, built from the pinned
  # source input (C99, only Xlib deps — builds in seconds).
  nvwm = pkgs.stdenv.mkDerivation {
    pname = "nvwm";
    version = "0-unstable-pinned";
    src = inputs.nvwm-src;
    buildInputs = with pkgs; [
      libx11
      libxinerama
      libxrandr
      libxcomposite
      libxrender
    ];
    makeFlags = [
      "PREFIX=${placeholder "out"}"
      "SYSCONFDIR=${placeholder "out"}/etc"
    ];
  };

  session-nvwm = pkgs.writeShellScript "session-nvwm" ''
    ${audioStart}
    exec ${nvwm}/bin/nvwm
  '';

  # vxwm: versatile dwm-style X11 WM, built from the pinned Codeberg
  # source (C + Xlib/Xft/Xinerama; dwm-style compiled-in config —
  # customize by editing config.def.h in an overridden build).
  vxwm = pkgs.stdenv.mkDerivation {
    pname = "vxwm";
    version = "2.3-pinned";
    src = inputs.vxwm-src;
    buildInputs = with pkgs; [
      libx11
      libxft
      libxinerama
      fontconfig
      freetype
    ];
    makeFlags = [
      "PREFIX=${placeholder "out"}"
      "X11INC=${pkgs.libx11.dev}/include"
      "X11LIB=${pkgs.libx11}/lib"
      "FREETYPEINC=${pkgs.freetype.dev}/include/freetype2"
    ];
  };

  session-vxwm = pkgs.writeShellScript "session-vxwm" ''
    ${audioStart}
    exec ${vxwm}/bin/vxwm
  '';

  # newm: touchpad-centric Wayland compositor (pywm). Comes from its
  # own flake with its own OLD locked nixpkgs (the only combination
  # it builds with); config: ~/.config/newm/config.py.
  session-newm = pkgs.writeShellScript "session-newm" ''
    ${audioStart}
    exec ${inputs.newm-flake.packages.x86_64-linux.newm}/bin/start-newm
  '';

  seed-user-configs = pkgs.writeShellScript "seed-user-configs" ''
    export PATH=${pkgs.coreutils}/bin:$PATH
    seed() {
      [ -e "$1" ] || return 0
      [ -e "$2" ] && return 0
      mkdir -p "$(dirname "$2")"
      # -L: resolve the /etc/static -> store symlinks into real,
      # writable files; chmod: store files are read-only
      cp -rL "$1" "$2" || return 0
      chmod -R u+w "$2"
    }
    while IFS=: read -r user _ uid gid _ home _; do
      [ "$uid" -ge 1000 ] && [ "$uid" -lt 65000 ] || continue
      [ -d "$home" ] || continue
      h="$home"
      seed "/etc/xdg/labwc" "$h/.config/labwc"
      seed "/etc/sway/config" "$h/.config/sway/config"
      seed "/etc/mango/config.conf" "$h/.config/mango/config.conf"
      seed "/etc/nvwm/config.conf" "$h/.config/nvwm/config.conf"
      chown -R "$uid:$gid" "$h/.config" 2>/dev/null || true
    done < /etc/passwd
  '';
in
{
  environment.systemPackages = [
    (pkgs.writeTextDir "share/wayland-sessions/labwc-noctalia.desktop" ''
      [Desktop Entry]
      Name=Labwc + Noctalia
      Comment=labwc stacking compositor with the Noctalia desktop shell
      Exec=${pkgs.dbus}/bin/dbus-run-session -- ${session-labwc-noctalia}
      Type=Application
      DesktopNames=labwc;wlroots
    '')
    (pkgs.writeTextDir "share/wayland-sessions/niri-noctalia.desktop" ''
      [Desktop Entry]
      Name=Niri + Noctalia
      Comment=Niri scrollable-tiling compositor with the Noctalia desktop shell
      Exec=${pkgs.dbus}/bin/dbus-run-session -- ${session-niri-noctalia}
      Type=Application
      DesktopNames=niri
    '')
    (pkgs.writeTextDir "share/wayland-sessions/mango-noctalia.desktop" ''
      [Desktop Entry]
      Name=Mango + Noctalia
      Comment=Mango tiling compositor with the Noctalia desktop shell
      Exec=${pkgs.dbus}/bin/dbus-run-session -- ${session-mango-noctalia}
      Type=Application
      DesktopNames=mango;wlroots
    '')
    (pkgs.writeTextDir "share/xsessions/nvwm.desktop" ''
      [Desktop Entry]
      Name=NVWM
      Comment=Vim-inspired tiling X11 window manager
      # NO `--` here. X11 sessions are launched through tuigreet's
      # --xsession-wrapper (startx ...), and startx treats the FIRST `--`
      # as its own client/server separator: it took the session script as
      # the X server binary, so no X server ever started ("xinit: unable to
      # connect to X server: Connection refused"). dbus-run-session accepts
      # PROGRAM without the separator.
      Exec=${pkgs.dbus}/bin/dbus-run-session ${session-nvwm}
      Type=Application
      DesktopNames=nvwm
    '')
    # runtime tools nvwm's default config binds keys to
    pkgs.alacritty
    pkgs.rofi
    pkgs.maim
    nvwm
    vxwm
    (pkgs.writeTextDir "share/xsessions/vxwm.desktop" ''
      [Desktop Entry]
      Name=vxwm
      Comment=Versatile dwm-style X11 tiling window manager
      # no `--`: startx (the xsession wrapper) would read it as
      # its client/server separator — see the nvwm entry
      Exec=${pkgs.dbus}/bin/dbus-run-session ${session-vxwm}
      Type=Application
      DesktopNames=vxwm
    '')
    # runtime tools vxwm's default (dwm-style) binds call:
    # Super+Shift+Return = st, Super+P = dmenu_run
    pkgs.st
    pkgs.dmenu
    inputs.newm-flake.packages.x86_64-linux.newm
    (pkgs.writeTextDir "share/wayland-sessions/newm.desktop" ''
      [Desktop Entry]
      Name=newm
      Comment=Touchpad-centric Wayland compositor
      Exec=${pkgs.dbus}/bin/dbus-run-session -- ${session-newm}
      Type=Application
      DesktopNames=newm
    '')
    # niri's excellent built-in defaults (Mod+Shift+/ shows them all)
    # spawn alacritty (Mod+T) and fuzzel (Mod+D) — install both so the
    # defaults work; ~/.config/niri/config.kdl customizes as usual
    pkgs.alacritty
    pkgs.fuzzel
    # the launcher every default config above binds to Super+D
    pkgs.rofi
    (lib.setPrio (-15) (pkgs.writeShellScriptBin "poweroff" ''
      [ "$(id -u)" = 0 ] && exec ${config.finit.package}/bin/initctl poweroff
      exec sudo -n ${config.finit.package}/bin/initctl poweroff
    ''))
    (lib.setPrio (-15) (pkgs.writeShellScriptBin "reboot" ''
      [ "$(id -u)" = 0 ] && exec ${config.finit.package}/bin/initctl reboot
      exec sudo -n ${config.finit.package}/bin/initctl reboot
    ''))
    (pkgs.writeShellScriptBin "zzz" ''
      [ "$(id -u)" = 0 ] && exec ${pkgs.writeShellScript "finix-suspend" "echo mem > /sys/power/state"}
      exec sudo -n ${pkgs.writeShellScript "finix-suspend" "echo mem > /sys/power/state"}
    '')
  ];
  environment.etc."nvwm/config.conf".source = "${nvwm}/etc/nvwm/config.conf";
  # default MangoWC config (copy to ~/.config/mango/config.conf to customize)
  environment.etc."mango/config.conf".source =
    config.programs.mango.package.src + "/assets/config.conf";
  # labwc reads $XDG_CONFIG_DIRS/labwc/ when ~/.config/labwc/ is absent
  environment.etc."xdg/labwc/rc.xml".text = ''
      <?xml version="1.0"?>
      <!-- finix default labwc config. Copy /etc/xdg/labwc/ to ~/.config/labwc/
           to customize; your copy takes precedence. <default /> keeps all of
           labwc's built-in key and mouse bindings (Alt-Tab, window menu, ...). -->
      <labwc_config>
        <keyboard>
          <default />
          <keybind key="W-Return">
            <action name="Execute" command="foot" />
          </keybind>
          <keybind key="W-d">
            <action name="Execute" command="rofi -show drun" />
          </keybind>
          <keybind key="W-q">
            <action name="Close" />
          </keybind>
          <keybind key="W-S-e">
            <action name="Exit" />
          </keybind>
        </keyboard>
        <mouse>
          <default />
        </mouse>
      </labwc_config>
  '';
  environment.etc."xdg/labwc/menu.xml".text = ''
      <?xml version="1.0" encoding="UTF-8"?>
      <!-- finix default labwc root menu (right-click on the desktop). -->
      <openbox_menu>
        <menu id="root-menu" label="finix">
          <item label="Terminal (foot)">
            <action name="Execute" command="foot" />
          </item>
          <item label="Applications (rofi)">
            <action name="Execute" command="rofi -show drun" />
          </item>
          <item label="Reconfigure">
            <action name="Reconfigure" />
          </item>
          <item label="Exit labwc">
            <action name="Exit" />
          </item>
        </menu>
      </openbox_menu>
  '';
  # sway probes $XDG_CONFIG_DIRS/sway/config and /etc/sway/config as
  # system fallbacks; ship the same file at both lookup paths
  environment.etc."sway/config".text = ''
      # finix default sway config. Copy to ~/.config/sway/config to customize;
      # your copy takes precedence over this system fallback.
      set $mod Mod4
      set $left h
      set $down j
      set $up k
      set $right l
      set $term foot
      set $menu rofi -show drun

      output * bg #1A1A1A solid_color
      floating_modifier $mod normal

      bindsym $mod+Return exec $term
      bindsym $mod+d exec $menu
      bindsym $mod+Shift+q kill
      bindsym $mod+Shift+c reload
      bindsym $mod+Shift+e exec swaynag -t warning -m 'Exit sway?' -B 'Yes, exit sway' 'swaymsg exit'

      bindsym $mod+$left focus left
      bindsym $mod+$down focus down
      bindsym $mod+$up focus up
      bindsym $mod+$right focus right
      bindsym $mod+Left focus left
      bindsym $mod+Down focus down
      bindsym $mod+Up focus up
      bindsym $mod+Right focus right
      bindsym $mod+Shift+$left move left
      bindsym $mod+Shift+$down move down
      bindsym $mod+Shift+$up move up
      bindsym $mod+Shift+$right move right
      bindsym $mod+Shift+Left move left
      bindsym $mod+Shift+Down move down
      bindsym $mod+Shift+Up move up
      bindsym $mod+Shift+Right move right

      bindsym $mod+1 workspace number 1
      bindsym $mod+2 workspace number 2
      bindsym $mod+3 workspace number 3
      bindsym $mod+4 workspace number 4
      bindsym $mod+5 workspace number 5
      bindsym $mod+6 workspace number 6
      bindsym $mod+7 workspace number 7
      bindsym $mod+8 workspace number 8
      bindsym $mod+9 workspace number 9
      bindsym $mod+Shift+1 move container to workspace number 1
      bindsym $mod+Shift+2 move container to workspace number 2
      bindsym $mod+Shift+3 move container to workspace number 3
      bindsym $mod+Shift+4 move container to workspace number 4
      bindsym $mod+Shift+5 move container to workspace number 5
      bindsym $mod+Shift+6 move container to workspace number 6
      bindsym $mod+Shift+7 move container to workspace number 7
      bindsym $mod+Shift+8 move container to workspace number 8
      bindsym $mod+Shift+9 move container to workspace number 9

      bindsym $mod+b splith
      bindsym $mod+v splitv
      bindsym $mod+s layout stacking
      bindsym $mod+w layout tabbed
      bindsym $mod+e layout toggle split
      bindsym $mod+f fullscreen
      bindsym $mod+Shift+space floating toggle
      bindsym $mod+space focus mode_toggle

      bar {
          position top
          status_command while date +'%Y-%m-%d %H:%M'; do sleep 60; done
      }
  '';
  environment.etc."xdg/sway/config".text = ''
      # finix default sway config. Copy to ~/.config/sway/config to customize;
      # your copy takes precedence over this system fallback.
      set $mod Mod4
      set $left h
      set $down j
      set $up k
      set $right l
      set $term foot
      set $menu rofi -show drun

      output * bg #1A1A1A solid_color
      floating_modifier $mod normal

      bindsym $mod+Return exec $term
      bindsym $mod+d exec $menu
      bindsym $mod+Shift+q kill
      bindsym $mod+Shift+c reload
      bindsym $mod+Shift+e exec swaynag -t warning -m 'Exit sway?' -B 'Yes, exit sway' 'swaymsg exit'

      bindsym $mod+$left focus left
      bindsym $mod+$down focus down
      bindsym $mod+$up focus up
      bindsym $mod+$right focus right
      bindsym $mod+Left focus left
      bindsym $mod+Down focus down
      bindsym $mod+Up focus up
      bindsym $mod+Right focus right
      bindsym $mod+Shift+$left move left
      bindsym $mod+Shift+$down move down
      bindsym $mod+Shift+$up move up
      bindsym $mod+Shift+$right move right
      bindsym $mod+Shift+Left move left
      bindsym $mod+Shift+Down move down
      bindsym $mod+Shift+Up move up
      bindsym $mod+Shift+Right move right

      bindsym $mod+1 workspace number 1
      bindsym $mod+2 workspace number 2
      bindsym $mod+3 workspace number 3
      bindsym $mod+4 workspace number 4
      bindsym $mod+5 workspace number 5
      bindsym $mod+6 workspace number 6
      bindsym $mod+7 workspace number 7
      bindsym $mod+8 workspace number 8
      bindsym $mod+9 workspace number 9
      bindsym $mod+Shift+1 move container to workspace number 1
      bindsym $mod+Shift+2 move container to workspace number 2
      bindsym $mod+Shift+3 move container to workspace number 3
      bindsym $mod+Shift+4 move container to workspace number 4
      bindsym $mod+Shift+5 move container to workspace number 5
      bindsym $mod+Shift+6 move container to workspace number 6
      bindsym $mod+Shift+7 move container to workspace number 7
      bindsym $mod+Shift+8 move container to workspace number 8
      bindsym $mod+Shift+9 move container to workspace number 9

      bindsym $mod+b splith
      bindsym $mod+v splitv
      bindsym $mod+s layout stacking
      bindsym $mod+w layout tabbed
      bindsym $mod+e layout toggle split
      bindsym $mod+f fullscreen
      bindsym $mod+Shift+space floating toggle
      bindsym $mod+space focus mode_toggle

      bar {
          position top
          status_command while date +'%Y-%m-%d %H:%M'; do sleep 60; done
      }
  '';
  environment.pathsToLink = [ "/share/xsessions" ];
  security.wrappers.X.enable = lib.mkForce true;
  system.activation.scripts.seed-user-configs = {
    deps = [ "users" ];
    text = "${seed-user-configs}";
  };
  # exact commands only, wheel group, no password (see shims above)
  environment.etc.sudoers.text = lib.mkOrder 2000 ''
    %wheel ALL=(root) NOPASSWD: ${config.finit.package}/bin/initctl poweroff, ${config.finit.package}/bin/initctl reboot, ${pkgs.writeShellScript "finix-suspend" "echo mem > /sys/power/state"}
  '';
}
