# Generated by the finix installer: session launchers and packages for
# the selected desktop sessions (Noctalia shell variants, NVWM).
{
  config,
  pkgs,
  lib,
  inputs,
  ...
}:
let
  # start the pipewire stack inside the session (no user services).
  # config.programs.*.package, not pkgs.*: under mdevd the packages
  # are rebuilt against libudev-zero.
  audioStart = ''
    ${config.programs.pipewire.package}/bin/pipewire &
    ${config.programs.wireplumber.package}/bin/wireplumber &
    ${config.programs.pipewire.package}/bin/pipewire-pulse &
  '';

  # Noctalia v5 desktop shell, built from the pinned source against the
  # same nixpkgs as the rest of the system
  noctalia = pkgs.callPackage (inputs.noctalia-src + "/nix/package.nix") { };

  session-labwc-noctalia = pkgs.writeShellScript "session-labwc-noctalia" ''
    ${config.programs.labwc.package}/bin/labwc >"$XDG_RUNTIME_DIR/labwc-compositor.log" 2>&1 &
    comp=$!
    sock=""
    i=0
    while [ $i -lt 100 ]; do
      for s in "$XDG_RUNTIME_DIR"/wayland-*; do
        case "$s" in
          *.lock) ;;
          *) if [ -S "$s" ]; then sock="$(basename "$s")"; break; fi ;;
        esac
      done
      [ -n "$sock" ] && break
      i=$((i + 1))
      sleep 0.1
    done
    if [ -n "$sock" ]; then
      export WAYLAND_DISPLAY="$sock"
      # first XWayland display on a fresh boot
      export DISPLAY=:0
      # finix wallpaper behind the shell (Noctalia can replace it
      # from its own wallpaper settings later)
      ${pkgs.swaybg}/bin/swaybg -i /etc/finix/wallpaper.png -m fill &
      ${audioStart}
      # Log to a file: Noctalia treats EGL/GL init failure as FATAL
      # (e.g. broken GL on nouveau, or a hybrid laptop whose EGL picks
      # the wrong DRM node) and greetd sessions have no visible stderr.
      # If it dies right away, bring it back on Qt's software
      # rasterizer rather than leaving the user with a bare compositor
      # and no bar, launcher or lock screen.
      (
        ${noctalia}/bin/noctalia --daemon >"$XDG_RUNTIME_DIR/noctalia.log" 2>&1 &
        np=$!
        sleep 5
        if ! kill -0 "$np" 2>/dev/null; then
          echo "noctalia exited early; retrying with software rendering" \
            >>"$XDG_RUNTIME_DIR/noctalia.log"
          QT_QUICK_BACKEND=software LIBGL_ALWAYS_SOFTWARE=1 \
            ${noctalia}/bin/noctalia --daemon \
            >>"$XDG_RUNTIME_DIR/noctalia.log" 2>&1 &
        fi
      ) &
    fi
    wait "$comp"
  '';

  session-sway-noctalia = pkgs.writeShellScript "session-sway-noctalia" ''
    ${config.programs.sway.package}/bin/sway -c /etc/sway/config-noctalia >"$XDG_RUNTIME_DIR/sway-compositor.log" 2>&1 &
    comp=$!
    sock=""
    i=0
    while [ $i -lt 100 ]; do
      for s in "$XDG_RUNTIME_DIR"/wayland-*; do
        case "$s" in
          *.lock) ;;
          *) if [ -S "$s" ]; then sock="$(basename "$s")"; break; fi ;;
        esac
      done
      [ -n "$sock" ] && break
      i=$((i + 1))
      sleep 0.1
    done
    if [ -n "$sock" ]; then
      export WAYLAND_DISPLAY="$sock"
      # first XWayland display on a fresh boot
      export DISPLAY=:0
      # finix wallpaper behind the shell (Noctalia can replace it
      # from its own wallpaper settings later)
      ${pkgs.swaybg}/bin/swaybg -i /etc/finix/wallpaper.png -m fill &
      ${audioStart}
      # Log to a file: Noctalia treats EGL/GL init failure as FATAL
      # (e.g. broken GL on nouveau, or a hybrid laptop whose EGL picks
      # the wrong DRM node) and greetd sessions have no visible stderr.
      # If it dies right away, bring it back on Qt's software
      # rasterizer rather than leaving the user with a bare compositor
      # and no bar, launcher or lock screen.
      (
        ${noctalia}/bin/noctalia --daemon >"$XDG_RUNTIME_DIR/noctalia.log" 2>&1 &
        np=$!
        sleep 5
        if ! kill -0 "$np" 2>/dev/null; then
          echo "noctalia exited early; retrying with software rendering" \
            >>"$XDG_RUNTIME_DIR/noctalia.log"
          QT_QUICK_BACKEND=software LIBGL_ALWAYS_SOFTWARE=1 \
            ${noctalia}/bin/noctalia --daemon \
            >>"$XDG_RUNTIME_DIR/noctalia.log" 2>&1 &
        fi
      ) &
    fi
    wait "$comp"
  '';

  session-niri-noctalia = pkgs.writeShellScript "session-niri-noctalia" ''
    ${config.programs.niri.package}/bin/niri --session >"$XDG_RUNTIME_DIR/niri-compositor.log" 2>&1 &
    comp=$!
    sock=""
    i=0
    while [ $i -lt 100 ]; do
      for s in "$XDG_RUNTIME_DIR"/wayland-*; do
        case "$s" in
          *.lock) ;;
          *) if [ -S "$s" ]; then sock="$(basename "$s")"; break; fi ;;
        esac
      done
      [ -n "$sock" ] && break
      i=$((i + 1))
      sleep 0.1
    done
    if [ -n "$sock" ]; then
      export WAYLAND_DISPLAY="$sock"
      # first XWayland display on a fresh boot
      export DISPLAY=:0
      i=0
      while [ $i -lt 20 ]; do
        for ns in "$XDG_RUNTIME_DIR"/niri.*.sock; do
          if [ -S "$ns" ]; then export NIRI_SOCKET="$ns"; break 2; fi
        done
        i=$((i + 1))
        sleep 0.1
      done
      # finix wallpaper behind the shell (Noctalia can replace it
      # from its own wallpaper settings later)
      ${pkgs.swaybg}/bin/swaybg -i /etc/finix/wallpaper.png -m fill &
      ${audioStart}
      # Log to a file: Noctalia treats EGL/GL init failure as FATAL
      # (e.g. broken GL on nouveau, or a hybrid laptop whose EGL picks
      # the wrong DRM node) and greetd sessions have no visible stderr.
      # If it dies right away, bring it back on Qt's software
      # rasterizer rather than leaving the user with a bare compositor
      # and no bar, launcher or lock screen.
      (
        ${noctalia}/bin/noctalia --daemon >"$XDG_RUNTIME_DIR/noctalia.log" 2>&1 &
        np=$!
        sleep 5
        if ! kill -0 "$np" 2>/dev/null; then
          echo "noctalia exited early; retrying with software rendering" \
            >>"$XDG_RUNTIME_DIR/noctalia.log"
          QT_QUICK_BACKEND=software LIBGL_ALWAYS_SOFTWARE=1 \
            ${noctalia}/bin/noctalia --daemon \
            >>"$XDG_RUNTIME_DIR/noctalia.log" 2>&1 &
        fi
      ) &
    fi
    wait "$comp"
  '';

  session-mango-noctalia = pkgs.writeShellScript "session-mango-noctalia" ''
    ${config.programs.mango.package}/bin/mango >"$XDG_RUNTIME_DIR/mango-compositor.log" 2>&1 &
    comp=$!
    sock=""
    i=0
    while [ $i -lt 100 ]; do
      for s in "$XDG_RUNTIME_DIR"/wayland-*; do
        case "$s" in
          *.lock) ;;
          *) if [ -S "$s" ]; then sock="$(basename "$s")"; break; fi ;;
        esac
      done
      [ -n "$sock" ] && break
      i=$((i + 1))
      sleep 0.1
    done
    if [ -n "$sock" ]; then
      export WAYLAND_DISPLAY="$sock"
      # first XWayland display on a fresh boot
      export DISPLAY=:0
      # finix wallpaper behind the shell (Noctalia can replace it
      # from its own wallpaper settings later)
      ${pkgs.swaybg}/bin/swaybg -i /etc/finix/wallpaper.png -m fill &
      ${audioStart}
      # Log to a file: Noctalia treats EGL/GL init failure as FATAL
      # (e.g. broken GL on nouveau, or a hybrid laptop whose EGL picks
      # the wrong DRM node) and greetd sessions have no visible stderr.
      # If it dies right away, bring it back on Qt's software
      # rasterizer rather than leaving the user with a bare compositor
      # and no bar, launcher or lock screen.
      (
        ${noctalia}/bin/noctalia --daemon >"$XDG_RUNTIME_DIR/noctalia.log" 2>&1 &
        np=$!
        sleep 5
        if ! kill -0 "$np" 2>/dev/null; then
          echo "noctalia exited early; retrying with software rendering" \
            >>"$XDG_RUNTIME_DIR/noctalia.log"
          QT_QUICK_BACKEND=software LIBGL_ALWAYS_SOFTWARE=1 \
            ${noctalia}/bin/noctalia --daemon \
            >>"$XDG_RUNTIME_DIR/noctalia.log" 2>&1 &
        fi
      ) &
    fi
    wait "$comp"
  '';

  session-labwc = pkgs.writeShellScript "session-labwc" ''
    ${audioStart}
    exec ${config.programs.labwc.package}/bin/labwc
  '';

  session-sway = pkgs.writeShellScript "session-sway" ''
    ${audioStart}
    exec ${config.programs.sway.package}/bin/sway
  '';

  session-niri = pkgs.writeShellScript "session-niri" ''
    ${audioStart}
    exec ${config.programs.niri.package}/bin/niri --session
  '';

  session-mango = pkgs.writeShellScript "session-mango" ''
    ${audioStart}
    exec ${config.programs.mango.package}/bin/mango
  '';

  # NVWM: vim-inspired tiling X11 window manager, built from the pinned
  # source input (C99, Xlib only)
  nvwm = pkgs.stdenv.mkDerivation {
    pname = "nvwm";
    version = "0-unstable-pinned";
    src = inputs.nvwm-src;
    buildInputs = with pkgs; [
      libx11
      libxinerama
      libxrandr
      libxcomposite
      libxrender
    ];
    makeFlags = [
      "PREFIX=${placeholder "out"}"
      "SYSCONFDIR=${placeholder "out"}/etc"
    ];
  };

  session-nvwm = pkgs.writeShellScript "session-nvwm" ''
    ${pkgs.xwallpaper}/bin/xwallpaper --zoom /etc/finix/wallpaper.png &
    ${audioStart}
    exec ${nvwm}/bin/nvwm
  '';

  swayConfigBase = "${config.programs.sway.package}/etc/sway/config";
  swayWallpaper = "output * bg /etc/finix/wallpaper.png fill";
  swayConfig = pkgs.runCommand "sway-config" { } ''
    # cat, not cp: cp keeps the store file's read-only mode and the
    # append on the next line then fails with "Permission denied"
    cat ${swayConfigBase} > $out
    echo "${swayWallpaper}" >> $out
  '';
  # same config without the trailing bar {} block: Noctalia draws
  # its own bar, and swaybar would sit on top of it
  swayConfigNoctalia = pkgs.runCommand "sway-config-noctalia" { } ''
    sed "/^bar {/,$ d" ${swayConfigBase} > $out
    echo "${swayWallpaper}" >> $out
  '';

  # vxwm: versatile dwm-style X11 WM, built from the pinned Codeberg
  # source (C + Xlib/Xft/Xinerama; dwm-style compiled-in config,
  # customize by editing config.def.h in an overridden build).
  vxwm = pkgs.stdenv.mkDerivation {
    pname = "vxwm";
    version = "2.3-pinned";
    src = inputs.vxwm-src;
    buildInputs = with pkgs; [
      libx11
      libxft
      libxinerama
      fontconfig
      freetype
    ];
    makeFlags = [
      "PREFIX=${placeholder "out"}"
      "X11INC=${pkgs.libx11.dev}/include"
      "X11LIB=${pkgs.libx11}/lib"
      "FREETYPEINC=${pkgs.freetype.dev}/include/freetype2"
    ];
  };

  session-vxwm = pkgs.writeShellScript "session-vxwm" ''
    ${pkgs.xwallpaper}/bin/xwallpaper --zoom /etc/finix/wallpaper.png &
    ${audioStart}
    exec ${vxwm}/bin/vxwm
  '';

  # newm: touchpad-centric Wayland compositor (pywm). Comes from its
  # own flake with its own OLD locked nixpkgs (the only combination
  # it builds with); config: ~/.config/newm/config.py.
  session-newm = pkgs.writeShellScript "session-newm" ''
    ${audioStart}
    exec ${inputs.newm-flake.packages.x86_64-linux.newm}/bin/start-newm
  '';

  seed-user-configs = pkgs.writeShellScript "seed-user-configs" ''
    export PATH=${pkgs.coreutils}/bin:$PATH
    seed() {
      [ -e "$1" ] || return 0
      [ -e "$2" ] && return 0
      mkdir -p "$(dirname "$2")"
      # -L: resolve the /etc/static -> store symlinks into real,
      # writable files; chmod: store files are read-only
      cp -rL "$1" "$2" || return 0
      chmod -R u+w "$2"
    }
    while IFS=: read -r user _ uid gid _ home _; do
      [ "$uid" -ge 1000 ] && [ "$uid" -lt 65000 ] || continue
      [ -d "$home" ] || continue
      h="$home"
      seed "/etc/xdg/labwc" "$h/.config/labwc"
      seed "/etc/sway/config" "$h/.config/sway/config"
      seed "/etc/mango/config.conf" "$h/.config/mango/config.conf"
      seed "/etc/nvwm/config.conf" "$h/.config/nvwm/config.conf"
      chown -R "$uid:$gid" "$h/.config" 2>/dev/null || true
    done < /etc/passwd
  '';
in
{
  environment.systemPackages = [
    (pkgs.writeTextDir "share/wayland-sessions/labwc-noctalia.desktop" ''
      [Desktop Entry]
      Name=Labwc + Noctalia
      Comment=labwc stacking compositor with the Noctalia desktop shell
      Exec=${pkgs.dbus}/bin/dbus-run-session -- ${session-labwc-noctalia}
      Type=Application
      DesktopNames=labwc;wlroots
    '')
    (pkgs.writeTextDir "share/wayland-sessions/sway-noctalia.desktop" ''
      [Desktop Entry]
      Name=Sway + Noctalia
      Comment=Sway i3-compatible compositor with the Noctalia desktop shell
      Exec=${pkgs.dbus}/bin/dbus-run-session -- ${session-sway-noctalia}
      Type=Application
      DesktopNames=sway;wlroots
    '')
    (pkgs.writeTextDir "share/wayland-sessions/niri-noctalia.desktop" ''
      [Desktop Entry]
      Name=Niri + Noctalia
      Comment=Niri scrollable-tiling compositor with the Noctalia desktop shell
      Exec=${pkgs.dbus}/bin/dbus-run-session -- ${session-niri-noctalia}
      Type=Application
      DesktopNames=niri
    '')
    (pkgs.writeTextDir "share/wayland-sessions/mango-noctalia.desktop" ''
      [Desktop Entry]
      Name=Mango + Noctalia
      Comment=Mango tiling compositor with the Noctalia desktop shell
      Exec=${pkgs.dbus}/bin/dbus-run-session -- ${session-mango-noctalia}
      Type=Application
      DesktopNames=mango;wlroots
    '')
    (lib.hiPrio (pkgs.writeTextDir "share/wayland-sessions/labwc.desktop" ''
      [Desktop Entry]
      Name=Labwc
      Comment=labwc stacking compositor
      Exec=${pkgs.dbus}/bin/dbus-run-session -- ${session-labwc}
      Type=Application
      DesktopNames=labwc;wlroots
    ''))
    (lib.hiPrio (pkgs.writeTextDir "share/wayland-sessions/sway.desktop" ''
      [Desktop Entry]
      Name=Sway
      Comment=Sway i3-compatible compositor
      Exec=${pkgs.dbus}/bin/dbus-run-session -- ${session-sway}
      Type=Application
      DesktopNames=sway;wlroots
    ''))
    (lib.hiPrio (pkgs.writeTextDir "share/wayland-sessions/niri.desktop" ''
      [Desktop Entry]
      Name=Niri
      Comment=Niri scrollable-tiling compositor
      Exec=${pkgs.dbus}/bin/dbus-run-session -- ${session-niri}
      Type=Application
      DesktopNames=niri
    ''))
    (lib.hiPrio (pkgs.writeTextDir "share/wayland-sessions/mango.desktop" ''
      [Desktop Entry]
      Name=Mango
      Comment=Mango tiling compositor
      Exec=${pkgs.dbus}/bin/dbus-run-session -- ${session-mango}
      Type=Application
      DesktopNames=mango;wlroots
    ''))
    (pkgs.writeTextDir "share/xsessions/nvwm.desktop" ''
      [Desktop Entry]
      Name=NVWM
      Comment=Vim-inspired tiling X11 window manager
      # no `--`: startx (tuigreet's xsession wrapper) would treat it as
      # its client/server separator
      Exec=${pkgs.dbus}/bin/dbus-run-session ${session-nvwm}
      Type=Application
      DesktopNames=nvwm
    '')
    # runtime tools nvwm's default config binds keys to
    pkgs.alacritty
    pkgs.rofi
    pkgs.maim
    nvwm
    vxwm
    (pkgs.writeTextDir "share/xsessions/vxwm.desktop" ''
      [Desktop Entry]
      Name=vxwm
      Comment=Versatile dwm-style X11 tiling window manager
      # no `--`: startx (the xsession wrapper) would read it as
      # its client/server separator, see the nvwm entry
      Exec=${pkgs.dbus}/bin/dbus-run-session ${session-vxwm}
      Type=Application
      DesktopNames=vxwm
    '')
    # runtime tools vxwm's default (dwm-style) binds call:
    # Super+Shift+Return = st, Super+P = dmenu_run
    pkgs.st
    pkgs.dmenu
    inputs.newm-flake.packages.x86_64-linux.newm
    (pkgs.writeTextDir "share/wayland-sessions/newm.desktop" ''
      [Desktop Entry]
      Name=newm
      Comment=Touchpad-centric Wayland compositor
      Exec=${pkgs.dbus}/bin/dbus-run-session -- ${session-newm}
      Type=Application
      DesktopNames=newm
    '')
    pkgs.alacritty
    pkgs.wob
    pkgs.pulseaudio # pactl, used by newm's volume keys
    # niri's excellent built-in defaults (Mod+Shift+/ shows them all)
    # spawn alacritty (Mod+T) and fuzzel (Mod+D); install both so the
    # defaults work; ~/.config/niri/config.kdl customizes as usual
    pkgs.alacritty
    pkgs.fuzzel
    # the launcher every default config above binds to Super+D
    pkgs.rofi
    pkgs.swaybg
    (lib.setPrio (-15) (pkgs.writeShellScriptBin "poweroff" ''
      [ "$(id -u)" = 0 ] && exec ${config.finit.package}/bin/initctl poweroff
      exec sudo -n ${config.finit.package}/bin/initctl poweroff
    ''))
    (lib.setPrio (-15) (pkgs.writeShellScriptBin "reboot" ''
      [ "$(id -u)" = 0 ] && exec ${config.finit.package}/bin/initctl reboot
      exec sudo -n ${config.finit.package}/bin/initctl reboot
    ''))
    (pkgs.writeShellScriptBin "zzz" ''
      [ "$(id -u)" = 0 ] && exec ${pkgs.writeShellScript "finix-suspend" "echo mem > /sys/power/state"}
      exec sudo -n ${pkgs.writeShellScript "finix-suspend" "echo mem > /sys/power/state"}
    '')
  ];
  environment.etc."nvwm/config.conf".source = "${nvwm}/etc/nvwm/config.conf";
  # default MangoWC config (copy to ~/.config/mango/config.conf to customize)
  environment.etc."mango/config.conf".source =
    config.programs.mango.package.src + "/assets/config.conf";
  # labwc reads $XDG_CONFIG_DIRS/labwc/ when ~/.config/labwc/ is absent
  environment.etc."xdg/labwc/rc.xml".source =
    config.programs.labwc.package.src + "/docs/rc.xml";
  environment.etc."xdg/labwc/menu.xml".source =
    config.programs.labwc.package.src + "/docs/menu.xml";
  environment.etc."xdg/labwc/autostart".text = ''
      # finix default labwc autostart. Copy /etc/xdg/labwc/ to
      # ~/.config/labwc/ to customize; your copy takes precedence.
      swaybg -i /etc/finix/wallpaper.png -m fill >/dev/null 2>&1 &
  '';
  # sway probes $XDG_CONFIG_DIRS/sway/config and /etc/sway/config as
  # system fallbacks; ship the same file at both lookup paths
  environment.etc."sway/config".source = swayConfig;
  environment.etc."xdg/sway/config".source = swayConfig;
  environment.etc."sway/config-noctalia".source = swayConfigNoctalia;
  # launchers (rofi -show drun, app menus) read .desktop files from
  # $XDG_DATA_DIRS = /run/current-system/sw/share; finix does not link
  # /share/applications by default, so nothing would be discoverable
  environment.pathsToLink = [ "/share/applications" "/share/xsessions" ];
  # /share/icons + /share/pixmaps, so those entries have icons
  xdg.icons.enable = true;
  security.wrappers.X.enable = lib.mkForce true;
  system.activation.scripts.seed-user-configs = {
    deps = [ "users" ];
    text = "${seed-user-configs}";
  };
  # exact commands only, wheel group, no password (see shims above)
  environment.etc.sudoers.text = lib.mkOrder 2000 ''
    %wheel ALL=(root) NOPASSWD: ${config.finit.package}/bin/initctl poweroff, ${config.finit.package}/bin/initctl reboot, ${pkgs.writeShellScript "finix-suspend" "echo mem > /sys/power/state"}
  '';
}
