#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import configparser
import json
import libcalamares
import os
import subprocess
import re

import gettext

_ = gettext.translation(
    "calamares-python",
    localedir=libcalamares.utils.gettext_path(),
    languages=libcalamares.utils.gettext_languages(),
    fallback=True,
).gettext


# The following strings contain pieces of a nix-configuration file.
# They are adapted from the default config generated from the nixos-generate-config command.

cfghead = """# finix system configuration, generated by the finix installer.
# finix uses finit as PID 1 (no systemd), mdevd+seatd (or eudev+elogind
# when KDE Plasma is installed), and the Nix package manager.
# Edit this file, then rebuild with:  sudo @@rebuildcmd@@ switch
# (the system flake lives in @@etcdir@@)

{ config, pkgs, ... }:

{
  imports =
    [ # Include the results of the hardware scan.
      ./hardware-configuration.nix
    ];

  # finix core (finit + nix daemon)
  finit.runlevel = 3;
  finit.services.nix-daemon.environment.CURL_CA_BUNDLE = config.security.pki.caBundle;
  services.nix-daemon.enable = true;
  services.nix-daemon.settings.experimental-features = [ "nix-command" "flakes" ];
  services.nix-daemon.settings.trusted-users = [ "root" "@wheel" ];

  services.dbus.enable = true;
  services.sysklogd.enable = true;
  services.polkit.enable = true;
  services.chrony.enable = true;
  services.bluetooth.enable = true;

  programs.sudo.enable = true;
  programs.bash.enable = true;
  hardware.graphics.enable = true;
  fonts.fontconfig.enable = true;
  fonts.enableDefaultPackages = true;

"""

# low-RAM machines: cap build parallelism on the installed system too
cfgnixlowram = """  # low-RAM machine: serialize builds so big rebuilds don't freeze it.
  # Raise these if you add RAM; delete for nix defaults.
  services.nix-daemon.settings.max-jobs = 1;
  services.nix-daemon.settings.cores = @@buildcores@@;

"""

# device manager + seat manager are coupled: elogind needs the udev
# database (eudev), seatd works with mdevd.
cfgseatd = """  # device manager + seat management: mdevd + seatd
  services.mdevd.enable = true;
  services.seatd.enable = true;

"""
# elogind flavor: required by KDE Plasma (KWin only has a logind backend)
cfgelogind = """  # device manager + seat management: eudev + elogind
  # (KDE Plasma needs elogind; elogind needs the udev database)
  services.udev.enable = true;
  services.elogind.enable = true;
  # finix xorg-module quirk: its udevApi is null under eudev, which builds
  # xorg-server without any libudev and fails; link eudev's libudev in.
  programs.xorg.package = pkgs.xorg-server.override { udev = pkgs.eudev; };

  # let wheel users power off / reboot / suspend without a password,
  # so desktop power buttons work
  services.polkit.extraConfig = ''
    polkit.addRule(function(action, subject) {
      if (subject.isInGroup("wheel") &&
          (action.id.indexOf("org.freedesktop.login1.power-off") == 0 ||
           action.id.indexOf("org.freedesktop.login1.reboot") == 0 ||
           action.id.indexOf("org.freedesktop.login1.suspend") == 0 ||
           action.id.indexOf("org.freedesktop.login1.hibernate") == 0)) {
        return polkit.Result.YES;
      }
    });
  '';

"""

# --- networking: exactly one of the two blocks below is emitted ---
# finix default: dhcpcd + iwd (no NetworkManager/systemd).
cfgnetfinix = """  # networking: dhcpcd + iwd (`iwctl` to connect to wifi)
  services.dhcpcd.enable = true;
  # kernel SLAAC handles IPv6 router advertisements; dhcpcd doing it too
  # spams the log with ipv6_addaddr1 errors
  services.dhcpcd.extraArgs = [ "--noipv6rs" ];
  services.iwd.enable = true;

"""

cfggreettui = """  # login: greetd/tuigreet, listing the installed sessions
  services.greetd.enable = true;
  services.greetd.settings.default_session.command = "${pkgs.tuigreet}/bin/tuigreet --time --remember --remember-session --sessions /run/current-system/sw/share/wayland-sessions";

"""

cfggreettuix11 = """  # login: greetd/tuigreet, listing wayland and X11 sessions
  services.greetd.enable = true;
  services.greetd.settings.default_session.command = "${pkgs.tuigreet}/bin/tuigreet --time --remember --remember-session --sessions /run/current-system/sw/share/wayland-sessions --xsessions /run/current-system/sw/share/xsessions --xsession-wrapper '${config.programs.xinit.package}/bin/startx ${pkgs.coreutils}/bin/env'";

"""

cfggreetnone = """  # login: console only (no display manager)

"""

cfgaudio = """  # audio: PipeWire + WirePlumber (started by the session launchers)
  programs.pipewire.enable = true;
  programs.pipewire.alsa.enable = true;
  programs.wireplumber.enable = true;
  services.rtkit.enable = true;
  users.groups.audio.gid = config.ids.gids.audio;

"""

# pinned input revisions for the generated system flake; these are what
# the ISO was built and tested against
NIXPKGS_REV = "e2587caef70cea85dd97d7daab492899902dbf5d"
FINIX_REV = "8a9b75a16b6f399e12d031dcd714a938af40c9b5"
NOCTALIA_REV = "3d7b9869950592ff7cf3704f6a53afb169d850db"  # v5.0.0-beta.5
NVWM_REV = "58bfe34f14d532b6fdcac3149133cccd2e3bf653"
VXWM_REV = "8b9f04c415a96c92fc36b7639cd1877903f3f0eb"
# newm keeps its own locked nixpkgs (no follows); other combinations
# don't build
NEWM_REV = "d120fcc390eba70593aecfafbafefe8647fd5c92"

# desktop choices offered by the packagechooser page (multi-select).
# opts = finix options to enable; the other flags pull in extra config
# (noctalia launcher, vendored plasma module, audio stack, ...)
cfgsessions = {
    "minimal": {
        "comment": "minimal install: no desktop and no greeter; log in on the console (tty)",
        "opts": [],
        "console": True,
    },
    "labwc": {
        "comment": "desktop: labwc (lightweight Wayland compositor)",
        "opts": ["programs.labwc.enable"],
    },
    "labwc-noctalia": {
        "comment": "desktop: labwc + Noctalia shell (bar, launcher, lock, OSD)",
        "opts": ["programs.labwc.enable"],
        "noctalia": "labwc",
        "audio": True,
    },
    "lxqt": {
        "comment": "desktop: LXQt (full desktop environment, Wayland session on labwc)",
        "opts": ["programs.lxqt.enable", "programs.labwc.enable"],
    },
    "plasma": {
        "comment": "desktop: KDE Plasma 6 (Wayland; experimental on finix)",
        "opts": ["programs.plasma.enable"],
        "plasma": True,
        "audio": True,
        "elogind": True,
    },
    "sway": {
        "comment": "desktop: Sway (i3-like tiling Wayland compositor)",
        "opts": ["programs.sway.enable"],
    },
    "niri": {
        "comment": "desktop: Niri (scrollable-tiling Wayland compositor)",
        "opts": ["programs.niri.enable"],
    },
    "niri-noctalia": {
        "comment": "desktop: Niri + Noctalia shell (with xwayland-satellite)",
        "opts": ["programs.niri.enable", "programs.xwayland-satellite.enable"],
        "noctalia": "niri",
        "audio": True,
    },
    "vxwm": {
        "comment": "desktop: vxwm (versatile dwm-style X11 tiling WM)",
        "opts": ["programs.xorg.enable", "programs.xinit.enable"],
        "vxwm": True,
        "audio": True,
    },
    "newm": {
        "comment": "desktop: newm (touchpad-centric Wayland compositor, pywm)",
        "opts": [],
        "newm": True,
        "audio": True,
    },
    "mango": {
        "comment": "desktop: Mango / MangoWC (dwl-based tiling Wayland compositor)",
        "opts": ["programs.mango.enable"],
        "mango": True,
    },
    "mango-noctalia": {
        "comment": "desktop: Mango + Noctalia shell",
        "opts": ["programs.mango.enable"],
        "noctalia": "mango",
        "audio": True,
        "mango": True,
    },
    "nvwm": {
        "comment": "desktop: NVWM (vim-inspired tiling X11 window manager)",
        "opts": ["programs.xorg.enable", "programs.xinit.enable"],
        "nvwm": True,
        "audio": True,
    },
}
cfgsessiondefault = "labwc"
# the existing ESP is kept so other-OS boot entries survive (dual boot)
cfgbootefi = """  # bootloader: limine (UEFI)
  programs.limine.enable = true;
  programs.limine.efiSupport = true;
  programs.limine.settings.editor_enabled = true;
  # No distro artwork behind the boot menu (the finix limine module defaults
  # to a NixOS wallpaper); keep the plain dark backdrop instead.
  programs.limine.settings.wallpaper = [ ];
  boot.loader.efi.canTouchEfiVariables = true;

"""

cfgbootbios = """  # bootloader: limine (legacy BIOS; UEFI is the recommended path)
  programs.limine.enable = true;
  programs.limine.biosSupport = true;
  programs.limine.biosDevice = "@@bootdev@@";
  programs.limine.settings.wallpaper = [ ];

"""

cfgbootbiosbtrfs = """  # bootloader: limine (legacy BIOS; UEFI is the recommended path)
  programs.limine.enable = true;
  programs.limine.biosSupport = true;
  programs.limine.biosDevice = "@@bootdev@@";
  programs.limine.settings.wallpaper = [ ];

"""

cfgbootnone = """  # No bootloader (bootloader managed manually).
  programs.limine.enable = false;

"""

# LUKS keyfile handling is bootloader-specific and unverified on limine/finix; skip.
cfgbootgrubcrypt = ""

cfgnetwork = """  networking.hostName = "@@hostname@@"; # Define your hostname.
  # networking.wireless.enable = true;  # Enables wireless support via wpa_supplicant.

  # Configure network proxy if necessary
  # networking.proxy.default = "http://user:password@proxy:port/";
  # networking.proxy.noProxy = "127.0.0.1,localhost,internal.domain";

"""

# finix networking is handled in cfghead (dhcpcd + iwd); the NixOS/systemd network
# stacks below are neutralized so nothing systemd-based is emitted.
cfgnetworkmanager = ""

cfgconnman = ""

cfgnmapplet = ""

cfgtime = """  # Set your time zone.
  time.timeZone = "@@timezone@@";

"""

cfglocale = """  # Select internationalisation properties.
  i18n.defaultLocale = "@@LANG@@";

"""

cfglocaleextra = """  i18n.extraLocaleSettings = {
    LC_ADDRESS = "@@LC_ADDRESS@@";
    LC_IDENTIFICATION = "@@LC_IDENTIFICATION@@";
    LC_MEASUREMENT = "@@LC_MEASUREMENT@@";
    LC_MONETARY = "@@LC_MONETARY@@";
    LC_NAME = "@@LC_NAME@@";
    LC_NUMERIC = "@@LC_NUMERIC@@";
    LC_PAPER = "@@LC_PAPER@@";
    LC_TELEPHONE = "@@LC_TELEPHONE@@";
    LC_TIME = "@@LC_TIME@@";
  };

"""

# stock NixOS desktop-environment blocks removed; sessions come from
# cfgsessions

# X11 keymap (services.xserver) does not apply on finix (Wayland/labwc, no xserver module
# enabled). Console keymap below still applies to the TTY; Wayland layout is a follow-up.
cfgkeymap = ""
cfgconsole = """  # Configure console keymap
  hardware.console.keyMap = "@@vconsole@@";

"""

# CUPS/pulseaudio use systemd on NixOS; neutralized for a minimal first finix boot.
# Audio (pipewire/wireplumber/rtkit are finix modules) can be added as a follow-up.
cfgmisc = ""
cfgusers = """  # Define a user account. Don't forget to set a password with ‘passwd’.
  users.users."@@username@@" = {
    isNormalUser = true;
    description = "@@fullname@@";
    extraGroups = [ @@groups@@ ];
    packages = with pkgs; [@@pkgs@@];
  };

"""

# firefox is a plain package on finix (no programs.firefox module)
cfgfirefox = ""

# autologin is not supported; greetd handles login
cfgautologin = ""
cfgautologingdm = ""
cfgautologintty = """  # automatic login is not supported by the finix installer yet

"""

# unfree is handled in build_flake (import nixpkgs { config.allowUnfree = true; })
cfgunfree = ""

cfgpkgs = """  # List packages installed in system profile. To search, run:
  # $ nix search wget
  environment.systemPackages = with pkgs; [
    vim
    git
    wget
    iproute2
    pciutils
    foot # wayland terminal
    firefox
    shadow # usermod & friends; also used by the installer's password step
    # rebuild wrapper: stages the flake dir into git (flakes only see
    # tracked files), then runs nixos-rebuild
    (lib.hiPrio (writeShellScriptBin "@@rebuildcmd@@" ''
      set -e
      ${git}/bin/git -C @@etcdir@@ add -A
      exec ${nixos-rebuild}/bin/nixos-rebuild "''${1:-switch}" --flake @@etcdir@@#finixos "''${@:2}"
    ''))
    fastfetch # finix colors come from /etc/xdg/fastfetch/config.jsonc
    # neofetch: wrapper around neowofetch (hyfetch) with the recolored
    # nixos ascii; distro is preset because it would detect /etc/NIXOS
    (writeShellScriptBin "neofetch" ''
      exec env distro="finix $(uname -m)" ${hyfetch}/bin/neowofetch --ascii_distro nixos --ascii_colors 1 8 1 8 1 8 "$@"
    '')
  ];

  # default fastfetch config: recolored nixos logo; the modules list has
  # to be spelled out, fastfetch doesn't merge partial configs
  environment.etc."xdg/fastfetch/config.jsonc".text = builtins.toJSON {
    logo = {
      source = "nixos";
      color = {
        "1" = "31";
        "2" = "90";
        "3" = "31";
        "4" = "90";
        "5" = "31";
        "6" = "90";
      };
    };
    modules = [
      "title" "separator" "os" "host" "kernel" "uptime" "packages" "shell"
      "display" "de" "wm" "wmtheme" "theme" "icons" "font" "cursor"
      "terminal" "terminalfont" "cpu" "gpu" "memory" "swap" "disk"
      "localip" "battery" "poweradapter" "locale" "break" "colors"
    ];
  };

"""

cfgtail = """  # Enable the OpenSSH daemon (optional).
  # services.openssh.enable = true;

  # NOTE: finix does not use NixOS's system.stateVersion; it is intentionally omitted.
}
"""

cfglatestkernel = """  # Use latest kernel.
  boot.kernelPackages = pkgs.linuxPackages_latest;

"""

# flake for the installed system (finix.lib.finixSystem, pinned inputs)
cfgflaketemplate = """{
  description = "finix system (installed by the finix installer)";

  inputs = {
    # Pinned to the revisions this installer ISO was validated against.
    nixpkgs.url = "github:nixos/nixpkgs/@@nixpkgs_rev@@";
    finix.url = "github:finix-community/finix/@@finix_rev@@";
@@extra_inputs@@  };

  outputs = inputs @ { self, nixpkgs, finix, ... }: let
    pkgs = import nixpkgs {
      system = "x86_64-linux";
      config.allowUnfree = true;
    };
  in {
    nixosConfigurations.finixos = finix.lib.finixSystem {
      inherit (pkgs) lib;

      modules = with finix.nixosModules; [
        { nixpkgs.pkgs = nixpkgs.lib.mkDefault pkgs; }
        (./configuration.nix)
        (./sessions.nix)
        (./branding.nix)@@plasma_import@@
        nix-daemon
        chronyd
        bluetooth
        openssh
        sysklogd
        limine
        sudo
        polkit
        getty
        bash
        dhcpcd
        iwd
        greetd
        networkmanager
        sddm
        upower
        # session/desktop modules (enable-gated; configuration.nix picks)
        labwc
        sway
        niri
        hyprland
        lxqt
        mango
        # audio / X11 / XWayland support (enable-gated)
        pipewire
        wireplumber
        rtkit
        xwayland-satellite
        xorg
        xinit
      ];

      specialArgs = {
        modulesPath = toString nixpkgs + "/nixos/modules";
        inherit inputs;
      };
    };
  };
}
"""


def parse_desktop_selection(raw_choice, warn=None):
    """Parse the (comma-separated, multi-select) packagechooser value into a
    validated selection list plus the aggregated feature flags. Anything
    unknown is dropped with a warning; an empty result falls back to the
    default so the install never emits options that don't exist on finix."""
    if warn is None:
        warn = lambda msg: None
    selected = []
    for choice in raw_choice.split(","):
        choice = choice.strip()
        if not choice:
            continue
        if choice not in cfgsessions:
            warn("Unknown desktop choice '{}', skipping".format(choice))
            continue
        if choice not in selected:
            selected.append(choice)
    if not selected:
        warn(
            "No (valid) desktop selected, falling back to {}".format(
                cfgsessiondefault
            )
        )
        selected = [cfgsessiondefault]

    needs = {
        "console_only": all(cfgsessions[s].get("console") for s in selected),
        "elogind": any(cfgsessions[s].get("elogind") for s in selected),
        "audio": any(cfgsessions[s].get("audio") for s in selected),
        "sddm": any(cfgsessions[s].get("sddm") for s in selected),
        "nm": any(cfgsessions[s].get("nm") for s in selected),
        "plasma": any(cfgsessions[s].get("plasma") for s in selected),
        "nvwm": any(cfgsessions[s].get("nvwm") for s in selected),
        "vxwm": any(cfgsessions[s].get("vxwm") for s in selected),
        "newm": any(cfgsessions[s].get("newm") for s in selected),
        "mango": any(cfgsessions[s].get("mango") for s in selected),
        # Per-compositor flags for the default-config emission (keybinds +
        # launcher; see build_sessions_nix). lxqt runs on labwc too.
        "labwc": any(s in ("labwc", "labwc-noctalia", "lxqt") for s in selected),
        "sway": "sway" in selected,
        "niri": any(s in ("niri", "niri-noctalia") for s in selected),
        "noctalia": any(cfgsessions[s].get("noctalia") for s in selected),
        "noctalia_compositors": [
            cfgsessions[s]["noctalia"]
            for s in selected
            if cfgsessions[s].get("noctalia")
        ],
    }
    return selected, needs


def build_flake(needs):
    """Render the system flake for the selected sessions. Extra inputs and
    the vendored plasma module are only wired in when needed."""
    extra_inputs = ""
    if needs["noctalia"]:
        extra_inputs += (
            '    noctalia-src = {\n'
            '      url = "github:noctalia-dev/noctalia-shell/' + NOCTALIA_REV + '";\n'
            '      flake = false;\n'
            '    };\n'
        )
    if needs["nvwm"]:
        extra_inputs += (
            '    nvwm-src = {\n'
            '      url = "github:Vifuddyxg/nvwm/' + NVWM_REV + '";\n'
            '      flake = false;\n'
            '    };\n'
        )
    if needs["vxwm"]:
        extra_inputs += (
            '    vxwm-src = {\n'
            '      url = "git+https://codeberg.org/wh1tepearl/vxwm?rev=' + VXWM_REV + '";\n'
            '      flake = false;\n'
            '    };\n'
        )
    if needs["newm"]:
        extra_inputs += (
            '    # a flake with its OWN lock (no follows): newm only builds\n'
            '    # against the old nixpkgs its lockfile pins\n'
            '    newm-flake.url = "github:jbuchermn/newm/' + NEWM_REV + '";\n'
        )
    flake = cfgflaketemplate
    flake = flake.replace("@@nixpkgs_rev@@", NIXPKGS_REV)
    flake = flake.replace("@@finix_rev@@", FINIX_REV)
    flake = flake.replace("@@extra_inputs@@", extra_inputs)
    flake = flake.replace(
        "@@plasma_import@@", "\n        (./plasma.nix)" if needs["plasma"] else ""
    )
    return flake


# hardware auto-detection (CPU microcode + GPU drivers). Detection reads
# /proc and /sys directly so it works on the live ISO without lspci.

def detect_cpu_vendor():
    """Return 'intel', 'amd' or None from /proc/cpuinfo."""
    try:
        with open("/proc/cpuinfo") as f:
            for line in f:
                if line.startswith("vendor_id"):
                    vendor = line.split(":", 1)[1].strip()
                    if vendor == "GenuineIntel":
                        return "intel"
                    if vendor == "AuthenticAMD":
                        return "amd"
                    return None
    except OSError:
        pass
    return None


def detect_gpu_vendors():
    """PCI vendor ids ('0x10de', ...) of display-class (0x03xxxx) devices."""
    vendors = set()
    base = "/sys/bus/pci/devices"
    try:
        entries = os.listdir(base)
    except OSError:
        return vendors
    for dev in entries:
        try:
            with open(os.path.join(base, dev, "class")) as f:
                if not f.read().startswith("0x03"):
                    continue
            with open(os.path.join(base, dev, "vendor")) as f:
                vendors.add(f.read().strip())
        except OSError:
            continue
    return vendors


def build_hardware_drivers(cpu_vendor, gpu_vendors, allow_unfree):
    """Render the auto-detected driver block of configuration.nix.
    linux-firmware + sof-firmware (wifi/bt/gpu/audio blobs) are already
    injected into hardware-configuration.nix by finixify_hardware_config."""
    out = "  # --- hardware auto-detection (CPU microcode + GPU drivers) ---\n"
    if cpu_vendor == "intel":
        out += "  # Intel CPU detected: load current microcode from the initrd.\n"
        out += "  hardware.cpu.intel.updateMicrocode = true;\n"
    elif cpu_vendor == "amd":
        out += "  # AMD CPU detected: load current microcode from the initrd.\n"
        out += "  hardware.cpu.amd.updateMicrocode = true;\n"

    if "0x10de" in gpu_vendors:
        # nouveau by default: the proprietary driver made kwin/wlroots
        # crash on real hardware, so it is only suggested, never enabled
        out += (
            "  # NVIDIA GPU detected; using the in-kernel nouveau driver.\n"
            "  # The proprietary driver is known to break wayland sessions\n"
            "  # on some laptops; to try it anyway"
            + (
                ":\n"
                if allow_unfree
                else " (also needs allowUnfree in flake.nix):\n"
            )
            + "  # hardware.nvidia.enable = true;\n"
        )
    if "0x8086" in gpu_vendors:
        out += (
            "  # Intel GPU detected: VA-API video acceleration drivers\n"
            "  # (intel-media-driver = Broadwell and newer, intel-vaapi-driver =\n"
            "  # older generations; the right one is picked at runtime).\n"
            "  hardware.graphics.extraPackages = with pkgs; [\n"
            "    intel-media-driver\n"
            "    intel-vaapi-driver\n"
            "  ];\n"
        )
    if "0x1002" in gpu_vendors:
        out += (
            "  # AMD GPU detected: fully covered by the in-kernel amdgpu driver\n"
            "  # and Mesa (already enabled via hardware.graphics.enable).\n"
        )
    return out + "\n"


# branding.nix: limine install hook rebuilt with the boot menu group
# renamed from NixOS to finix
BRANDING_NIX = """# Generated by the finix installer: finix branding fixes.
{
  config,
  pkgs,
  lib,
  inputs,
  ...
}:
let
  cfg = config.programs.limine;

  # same JSON the upstream limine module builds
  limineInstallConfig = pkgs.writeText "limine-install.json" (
    builtins.toJSON {
      inherit (cfg)
        additionalFiles
        biosDevice
        biosSupport
        efiSupport
        enrollConfig
        extraEntries
        force
        partitionIndex
        settings
        validateChecksums
        secureBoot
        ;

      nixPath = config.services.nix-daemon.package;
      efiBootMgrPath = pkgs.efibootmgr;
      liminePath = cfg.package;
      efiMountPoint = config.boot.loader.efi.efiSysMountPoint;
      fileSystems = config.fileSystems;
      canTouchEfiVariables = config.boot.loader.efi.canTouchEfiVariables;
      efiRemovable = cfg.efiInstallAsRemovable;
      maxGenerations = if cfg.maxGenerations == null then 0 else cfg.maxGenerations;
      hostArchitecture = pkgs.stdenv.hostPlatform.parsed.cpu;
      fwupdEfiPath = config.services.fwupd.package or null;
    }
  );

  # upstream limine-install.py with the menu group renamed to finix
  patchedInstallScript =
    pkgs.runCommand "limine-install-finix.py" { } ''
      sed -e "s|/+NixOS {group_name}|/+finix {group_name}|" \\
        ${inputs.finix}/modules/programs/limine/limine-install.py > $out
    '';
in
{
  config = lib.mkIf (config.providers.bootloader.backend or null == "limine") {
    providers.bootloader.installHook = lib.mkForce (
      pkgs.replaceVarsWith {
        src = patchedInstallScript;
        isExecutable = true;
        replacements = {
          python3 = pkgs.python3.withPackages (python-packages: [ python-packages.psutil ]);
          configPath = limineInstallConfig;
        };
      }
    );
  };
}
"""


# vendored KDE Plasma 6 module (based on the WIP upstream branch
# modules/plasma, b7d1b1d), written only when plasma is selected
PLASMA_NIX = """# KDE Plasma 6 on finix, generated by the finix installer.
# Based on the WIP upstream module (finix branch modules/plasma).
{
  config,
  pkgs,
  lib,
  ...
}:
let
  cfg = config.programs.plasma;

  inherit (pkgs) kdePackages;

  # start audio in-session, refresh the kservice cache, start plasma.
  # config.programs.*.package (not pkgs.*): under mdevd pipewire is
  # rebuilt against libudev-zero
  sessionScript = pkgs.writeShellScript "plasma-session" ''
    ${config.programs.pipewire.package}/bin/pipewire &
    ${config.programs.wireplumber.package}/bin/wireplumber &
    ${config.programs.pipewire.package}/bin/pipewire-pulse &
    ${kdePackages.kservice}/bin/kbuildsycoca6 || true
    exec ${kdePackages.plasma-workspace}/bin/startplasma-wayland
  '';

  sessionFile = pkgs.writeTextDir "share/wayland-sessions/plasma.desktop" ''
    [Desktop Entry]
    Name=Plasma (Wayland)
    Comment=KDE Plasma Desktop
    Exec=${pkgs.dbus}/bin/dbus-run-session -- ${sessionScript}
    Type=Application
    DesktopNames=KDE
  '';

  # look-and-feel package: breeze dark + finix wallpaper; user settings win
  lnfMetadata = pkgs.writeTextDir "share/plasma/look-and-feel/org.finix.desktop/metadata.json" (
    builtins.toJSON {
      KPackageStructure = "Plasma/LookAndFeel";
      KPlugin = {
        Id = "org.finix.desktop";
        Name = "finix";
        Description = "Breeze Dark with the finix wallpaper";
      };
      "X-Plasma-APIVersion" = "2";
    }
  );
  lnfDefaults = pkgs.writeTextDir "share/plasma/look-and-feel/org.finix.desktop/contents/defaults" ''
    [kdeglobals][KDE]
    widgetStyle=Breeze
    [kdeglobals][General]
    ColorScheme=BreezeDark
    [kdeglobals][Icons]
    Theme=breeze-dark
    [plasmarc][Theme]
    name=default
    [Wallpaper]
    Image=@@wallpaper@@
  '';
in
{
  options.programs.plasma = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Whether to enable the KDE Plasma 6 Wayland session.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    # Battery / power management backend for powerdevil.
    services.upower.enable = true;

    environment.systemPackages = with kdePackages; [
      # session entry point
      (lib.hiPrio sessionFile)

      # Qt Wayland support
      qtwayland
      qtsvg
      qtimageformats

      # kwin + the xwayland binary it lazy-spawns; without xwayland every
      # X11 client connecting to :0 hangs and session startup blocks
      kwin
      pkgs.xwayland

      # core plasma (mirrors nixos/modules/services/desktop-managers/plasma6.nix
      # requiredPackages, minus systemd-only bits)
      plasma-workspace
      plasma-desktop
      kscreen
      libkscreen
      kscreenlocker
      kactivitymanagerd
      kglobalacceld
      kwrited
      baloo
      milou
      kmenuedit
      kinfocenter
      plasma-systemmonitor
      ksystemstats
      libksysguard
      systemsettings
      kcmutils
      kdeplasma-addons
      pkgs.xdg-user-dirs

      # KDE frameworks needed at runtime
      frameworkintegration
      kauth
      kcoreaddons
      kded
      kfilemetadata
      kguiaddons
      kiconthemes
      kimageformats
      kio
      kio-admin
      kio-extras
      kio-fuse
      knighttime
      kpackage
      kservice
      kunifiedpush
      solid
      plasma-activities
      phonon-vlc

      # QML / Qt plugins needed by plasmashell
      libplasma
      qqc2-desktop-style
      kde-cli-tools

      # theme
      breeze
      breeze-icons
      breeze-gtk
      kde-gtk-config
      ocean-sound-theme
      pkgs.hicolor-icon-theme
      qqc2-breeze-style
      # finix default look-and-feel (wallpaper + Breeze Dark)
      lnfMetadata
      lnfDefaults

      # polkit agent
      polkit-kde-agent-1

      # platform integration
      plasma-integration

      drkonqi

      # audio + power applets; no plasma-nm (networking is dhcpcd + iwd,
      # wifi via iwgtk/iwctl)
      plasma-pa
      powerdevil
      pkgs.iwgtk

      # wallet (plasma-nm stores Wi-Fi passphrases here)
      kwallet
      kwalletmanager

      # beginner-friendly default applications
      dolphin
      konsole
      kate
      ark
      gwenview
      okular
      spectacle
      kdegraphics-thumbnailers
    ];

    environment.pathsToLink = [
      "/share"

      # for drkonqi
      "/libexec"
    ];

    security.pam.environment =
      let
        qtVersions = with pkgs; [
          qt5
          qt6
        ];
      in
      {
        QT_PLUGIN_PATH.default = map (qt: "/run/current-system/sw/${qt.qtbase.qtPluginPrefix}") qtVersions;
        QML2_IMPORT_PATH.default = map (qt: "/run/current-system/sw/${qt.qtbase.qtQmlPrefix}") qtVersions;

        # /etc/xdg holds the finix default kdeglobals below
        XDG_CONFIG_DIRS.default = [
          "@{HOME}/.config/kdedefaults"
          "/etc/xdg"
        ];

        KPACKAGE_DEP_RESOLVERS_PATH.default = [
          "${kdePackages.frameworkintegration.out}/libexec/kf6/kpackagehandlers"
        ];
      };

    # default look-and-feel for new users; system settings override it
    environment.etc."xdg/kdeglobals".text = ''
      [KDE]
      LookAndFeelPackage=org.finix.desktop
    '';

    # kscreenlocker authenticates through the "kde" PAM service
    security.pam.services.kde.text = ''
      auth      substack      login
      account   include       login
      password  substack      login
      session   include       login
    '';

    security.wrappers = {
      kwin_wayland = {
        owner = "root";
        group = "root";
        capabilities = "cap_sys_nice+ep";
        source = "${lib.getBin pkgs.kdePackages.kwin}/bin/kwin_wayland";
      };
    };

    xdg.portal.portals = [
      pkgs.kdePackages.xdg-desktop-portal-kde
      pkgs.xdg-desktop-portal-gtk
    ];
  };
}
"""


# --- sessions.nix generation -------------------------------------------------

_NOCTALIA_COMPOSITORS = {
    "labwc": {
        "name": "Labwc",
        "cmd": "${config.programs.labwc.package}/bin/labwc",
        "desktop_names": "labwc;wlroots",
        "comment": "labwc stacking compositor with the Noctalia desktop shell",
    },
    "niri": {
        "name": "Niri",
        "cmd": "${config.programs.niri.package}/bin/niri --session",
        "desktop_names": "niri",
        "comment": "Niri scrollable-tiling compositor with the Noctalia desktop shell",
    },
    "mango": {
        "name": "Mango",
        "cmd": "${config.programs.mango.package}/bin/mango",
        "desktop_names": "mango;wlroots",
        "comment": "Mango tiling compositor with the Noctalia desktop shell",
    },
}


def _noctalia_session_nix(comp, wallpaper):
    """One '<compositor> + Noctalia' launcher: start the compositor, wait
    for its wayland socket, then start audio and noctalia next to it."""
    c = _NOCTALIA_COMPOSITORS[comp]
    # noctalia's logout needs $NIRI_SOCKET; export it explicitly since
    # noctalia is started as the compositor's sibling
    niri_socket = ""
    if comp == "niri":
        niri_socket = (
            '      i=0\n'
            '      while [ $i -lt 20 ]; do\n'
            '        for ns in "$XDG_RUNTIME_DIR"/niri.*.sock; do\n'
            '          if [ -S "$ns" ]; then export NIRI_SOCKET="$ns"; break 2; fi\n'
            '        done\n'
            '        i=$((i + 1))\n'
            '        sleep 0.1\n'
            '      done\n'
        )
    script = (
        '  session-' + comp + '-noctalia = pkgs.writeShellScript "session-' + comp + '-noctalia" \'\'\n'
        '    ' + c["cmd"] + ' &\n'
        '    comp=$!\n'
        '    sock=""\n'
        '    i=0\n'
        '    while [ $i -lt 100 ]; do\n'
        '      for s in "$XDG_RUNTIME_DIR"/wayland-*; do\n'
        '        case "$s" in\n'
        '          *.lock) ;;\n'
        '          *) if [ -S "$s" ]; then sock="$(basename "$s")"; break; fi ;;\n'
        '        esac\n'
        '      done\n'
        '      [ -n "$sock" ] && break\n'
        '      i=$((i + 1))\n'
        '      sleep 0.1\n'
        '    done\n'
        '    if [ -n "$sock" ]; then\n'
        '      export WAYLAND_DISPLAY="$sock"\n'
        '      # first XWayland display on a fresh boot\n'
        '      export DISPLAY=:0\n'
        + niri_socket +
        '      # finix wallpaper behind the shell (Noctalia can replace it\n'
        '      # from its own wallpaper settings later)\n'
        '      ${pkgs.swaybg}/bin/swaybg -i ' + wallpaper + ' -m fill &\n'
        '      ${audioStart}\n'
        '      # Log to a file: Noctalia treats EGL/GL init failure as FATAL\n'
        '      # (e.g. broken GL on nouveau) and greetd sessions have no\n'
        '      # visible stderr\n'
        '      ${noctalia}/bin/noctalia --daemon >"$XDG_RUNTIME_DIR/noctalia.log" 2>&1 &\n'
        '    fi\n'
        '    wait "$comp"\n'
        '  \'\';\n'
    )
    desktop = (
        '    (pkgs.writeTextDir "share/wayland-sessions/' + comp + '-noctalia.desktop" \'\'\n'
        '      [Desktop Entry]\n'
        '      Name=' + c["name"] + ' + Noctalia\n'
        '      Comment=' + c["comment"] + '\n'
        '      Exec=${pkgs.dbus}/bin/dbus-run-session -- ${session-' + comp + '-noctalia}\n'
        '      Type=Application\n'
        '      DesktopNames=' + c["desktop_names"] + '\n'
        '    \'\')\n'
    )
    return script, desktop


_NVWM_NIX_LET = """  # NVWM: vim-inspired tiling X11 window manager, built from the pinned
  # source input (C99, Xlib only)
  nvwm = pkgs.stdenv.mkDerivation {
    pname = "nvwm";
    version = "0-unstable-pinned";
    src = inputs.nvwm-src;
    buildInputs = with pkgs; [
      libx11
      libxinerama
      libxrandr
      libxcomposite
      libxrender
    ];
    makeFlags = [
      "PREFIX=${placeholder "out"}"
      "SYSCONFDIR=${placeholder "out"}/etc"
    ];
  };

  session-nvwm = pkgs.writeShellScript "session-nvwm" ''
    ${pkgs.xwallpaper}/bin/xwallpaper --zoom @@wallpaper@@ &
    ${audioStart}
    exec ${nvwm}/bin/nvwm
  '';
"""

_NVWM_NIX_DESKTOP = """    (pkgs.writeTextDir "share/xsessions/nvwm.desktop" ''
      [Desktop Entry]
      Name=NVWM
      Comment=Vim-inspired tiling X11 window manager
      # no `--`: startx (tuigreet's xsession wrapper) would treat it as
      # its client/server separator
      Exec=${pkgs.dbus}/bin/dbus-run-session ${session-nvwm}
      Type=Application
      DesktopNames=nvwm
    '')
    # runtime tools nvwm's default config binds keys to
    pkgs.alacritty
    pkgs.rofi
    pkgs.maim
"""


# system-wide default compositor configs, placed at each compositor's
# documented /etc fallback path so ~/.config always wins.
# common binds: Super+Enter = foot, Super+D = rofi, Super+Q = close

_LABWC_RC_XML = """<?xml version="1.0"?>
<!-- finix default labwc config. Copy /etc/xdg/labwc/ to ~/.config/labwc/
     to customize; your copy takes precedence. <default /> keeps all of
     labwc's built-in key and mouse bindings (Alt-Tab, window menu, ...). -->
<labwc_config>
  <keyboard>
    <default />
    <keybind key="W-Return">
      <action name="Execute" command="foot" />
    </keybind>
    <keybind key="W-d">
      <action name="Execute" command="rofi -show drun" />
    </keybind>
    <keybind key="W-q">
      <action name="Close" />
    </keybind>
    <keybind key="W-S-e">
      <action name="Exit" />
    </keybind>
  </keyboard>
  <mouse>
    <default />
  </mouse>
</labwc_config>
"""

_LABWC_MENU_XML = """<?xml version="1.0" encoding="UTF-8"?>
<!-- finix default labwc root menu (right-click on the desktop). -->
<openbox_menu>
  <menu id="root-menu" label="finix">
    <item label="Terminal (foot)">
      <action name="Execute" command="foot" />
    </item>
    <item label="Applications (rofi)">
      <action name="Execute" command="rofi -show drun" />
    </item>
    <item label="Reconfigure">
      <action name="Reconfigure" />
    </item>
    <item label="Exit labwc">
      <action name="Exit" />
    </item>
  </menu>
</openbox_menu>
"""

_SWAY_CONFIG = """# finix default sway config. Copy to ~/.config/sway/config to customize;
# your copy takes precedence over this system fallback.
set $mod Mod4
set $left h
set $down j
set $up k
set $right l
set $term foot
set $menu rofi -show drun

output * bg @@wallpaper@@ fill
floating_modifier $mod normal

bindsym $mod+Return exec $term
bindsym $mod+d exec $menu
bindsym $mod+Shift+q kill
bindsym $mod+Shift+c reload
bindsym $mod+Shift+e exec swaynag -t warning -m 'Exit sway?' -B 'Yes, exit sway' 'swaymsg exit'

bindsym $mod+$left focus left
bindsym $mod+$down focus down
bindsym $mod+$up focus up
bindsym $mod+$right focus right
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right
bindsym $mod+Shift+$left move left
bindsym $mod+Shift+$down move down
bindsym $mod+Shift+$up move up
bindsym $mod+Shift+$right move right
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

bindsym $mod+1 workspace number 1
bindsym $mod+2 workspace number 2
bindsym $mod+3 workspace number 3
bindsym $mod+4 workspace number 4
bindsym $mod+5 workspace number 5
bindsym $mod+6 workspace number 6
bindsym $mod+7 workspace number 7
bindsym $mod+8 workspace number 8
bindsym $mod+9 workspace number 9
bindsym $mod+Shift+1 move container to workspace number 1
bindsym $mod+Shift+2 move container to workspace number 2
bindsym $mod+Shift+3 move container to workspace number 3
bindsym $mod+Shift+4 move container to workspace number 4
bindsym $mod+Shift+5 move container to workspace number 5
bindsym $mod+Shift+6 move container to workspace number 6
bindsym $mod+Shift+7 move container to workspace number 7
bindsym $mod+Shift+8 move container to workspace number 8
bindsym $mod+Shift+9 move container to workspace number 9

bindsym $mod+b splith
bindsym $mod+v splitv
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split
bindsym $mod+f fullscreen
bindsym $mod+Shift+space floating toggle
bindsym $mod+space focus mode_toggle

bar {
    position top
    status_command while date +'%Y-%m-%d %H:%M'; do sleep 60; done
}
"""

def _nix_etc_text(path, body):
    """environment.etc."<path>".text = ''<body>''; with proper indentation.
    The bodies contain no Nix-string specials ( '' or ${ )."""
    indented = "".join(
        ("      " + line if line.strip() else "") + "\n"
        for line in body.splitlines()
    )
    return (
        '  environment.etc."' + path + '".text = \'\'\n' + indented + "  \'\';\n"
    )


def build_sessions_nix(needs, etcdir="/etc/finix"):
    """Render sessions.nix: session launchers, packages and default
    compositor configs for the selected sessions. Always written (may be
    an empty module) so the flake can import it unconditionally."""
    wallpaper = etcdir + "/wallpaper.png"
    let_parts = []
    pkg_parts = []
    etc_parts = []

    if needs["noctalia"] or needs["nvwm"] or needs["vxwm"] or needs["newm"]:
        let_parts.append(
            '  # start the pipewire stack inside the session (no user services).\n'
            '  # config.programs.*.package, not pkgs.*: under mdevd the packages\n'
            '  # are rebuilt against libudev-zero.\n'
            '  audioStart = \'\'\n'
            '    ${config.programs.pipewire.package}/bin/pipewire &\n'
            '    ${config.programs.wireplumber.package}/bin/wireplumber &\n'
            '    ${config.programs.pipewire.package}/bin/pipewire-pulse &\n'
            '  \'\';\n'
        )

    if needs["noctalia"]:
        let_parts.append(
            '  # Noctalia v5 desktop shell, built from the pinned source against the\n'
            '  # same nixpkgs as the rest of the system\n'
            '  noctalia = pkgs.callPackage (inputs.noctalia-src + "/nix/package.nix") { };\n'
        )
        for comp in needs["noctalia_compositors"]:
            script, desktop = _noctalia_session_nix(comp, wallpaper)
            let_parts.append(script)
            pkg_parts.append(desktop)

    if needs["nvwm"]:
        let_parts.append(_NVWM_NIX_LET.replace("@@wallpaper@@", wallpaper))
        pkg_parts.append(_NVWM_NIX_DESKTOP)
        pkg_parts.append("    nvwm\n")
        etc_parts.append(
            '  environment.etc."nvwm/config.conf".source = "${nvwm}/etc/nvwm/config.conf";\n'
        )

    if needs["mango"]:
        # mango errors on a missing /etc/mango/config.conf; ship the
        # upstream default
        etc_parts.append(
            '  # default MangoWC config (copy to ~/.config/mango/config.conf to customize)\n'
            '  environment.etc."mango/config.conf".source =\n'
            '    config.programs.mango.package.src + "/assets/config.conf";\n'
        )

    # --- default keybind configs so every session works out of the box ---
    if needs["labwc"]:
        etc_parts.append(
            "  # labwc reads $XDG_CONFIG_DIRS/labwc/ when ~/.config/labwc/ is absent\n"
        )
        etc_parts.append(_nix_etc_text("xdg/labwc/rc.xml", _LABWC_RC_XML))
        etc_parts.append(_nix_etc_text("xdg/labwc/menu.xml", _LABWC_MENU_XML))
        etc_parts.append(
            _nix_etc_text(
                "xdg/labwc/autostart",
                "# finix default labwc autostart. Copy /etc/xdg/labwc/ to\n"
                "# ~/.config/labwc/ to customize; your copy takes precedence.\n"
                "swaybg -i " + wallpaper + " -m fill >/dev/null 2>&1 &\n",
            )
        )

    if needs["sway"]:
        sway_cfg = _SWAY_CONFIG.replace("@@wallpaper@@", wallpaper)
        etc_parts.append(
            "  # sway probes $XDG_CONFIG_DIRS/sway/config and /etc/sway/config as\n"
            "  # system fallbacks; ship the same file at both lookup paths\n"
        )
        etc_parts.append(_nix_etc_text("sway/config", sway_cfg))
        etc_parts.append(_nix_etc_text("xdg/sway/config", sway_cfg))

    if needs["vxwm"]:
        let_parts.append(
            "  # vxwm: versatile dwm-style X11 WM, built from the pinned Codeberg\n"
            "  # source (C + Xlib/Xft/Xinerama; dwm-style compiled-in config,\n"
            "  # customize by editing config.def.h in an overridden build).\n"
            "  vxwm = pkgs.stdenv.mkDerivation {\n"
            '    pname = "vxwm";\n'
            '    version = "2.3-pinned";\n'
            "    src = inputs.vxwm-src;\n"
            "    buildInputs = with pkgs; [\n"
            "      libx11\n"
            "      libxft\n"
            "      libxinerama\n"
            "      fontconfig\n"
            "      freetype\n"
            "    ];\n"
            "    makeFlags = [\n"
            '      "PREFIX=${placeholder "out"}"\n'
            '      "X11INC=${pkgs.libx11.dev}/include"\n'
            '      "X11LIB=${pkgs.libx11}/lib"\n'
            '      "FREETYPEINC=${pkgs.freetype.dev}/include/freetype2"\n'
            "    ];\n"
            "  };\n"
            "\n"
            '  session-vxwm = pkgs.writeShellScript "session-vxwm" \'\'\n'
            "    ${pkgs.xwallpaper}/bin/xwallpaper --zoom " + wallpaper + " &\n"
            "    ${audioStart}\n"
            "    exec ${vxwm}/bin/vxwm\n"
            "  \'\';\n"
        )
        pkg_parts.append(
            "    vxwm\n"
            '    (pkgs.writeTextDir "share/xsessions/vxwm.desktop" \'\'\n'
            "      [Desktop Entry]\n"
            "      Name=vxwm\n"
            "      Comment=Versatile dwm-style X11 tiling window manager\n"
            "      # no `--`: startx (the xsession wrapper) would read it as\n"
            "      # its client/server separator, see the nvwm entry\n"
            "      Exec=${pkgs.dbus}/bin/dbus-run-session ${session-vxwm}\n"
            "      Type=Application\n"
            "      DesktopNames=vxwm\n"
            "    \'\')\n"
            "    # runtime tools vxwm's default (dwm-style) binds call:\n"
            "    # Super+Shift+Return = st, Super+P = dmenu_run\n"
            "    pkgs.st\n"
            "    pkgs.dmenu\n"
        )

    if needs["newm"]:
        let_parts.append(
            "  # newm: touchpad-centric Wayland compositor (pywm). Comes from its\n"
            "  # own flake with its own OLD locked nixpkgs (the only combination\n"
            "  # it builds with); config: ~/.config/newm/config.py.\n"
            '  session-newm = pkgs.writeShellScript "session-newm" \'\'\n'
            "    ${audioStart}\n"
            '    exec ${inputs.newm-flake.packages.x86_64-linux.newm}/bin/start-newm\n'
            "  \'\';\n"
        )
        pkg_parts.append(
            "    inputs.newm-flake.packages.x86_64-linux.newm\n"
            '    (pkgs.writeTextDir "share/wayland-sessions/newm.desktop" \'\'\n'
            "      [Desktop Entry]\n"
            "      Name=newm\n"
            "      Comment=Touchpad-centric Wayland compositor\n"
            "      Exec=${pkgs.dbus}/bin/dbus-run-session -- ${session-newm}\n"
            "      Type=Application\n"
            "      DesktopNames=newm\n"
            "    \'\')\n"
        )
        # newm uses its bundled default config; install the tools its
        # binds call (alacritty terminal, wob volume bar, pactl)
        pkg_parts.append(
            "    pkgs.alacritty\n"
            "    pkgs.wob\n"
            "    pkgs.pulseaudio # pactl, used by newm's volume keys\n"
        )
    if needs["nvwm"] or needs["vxwm"]:
        # /share/xsessions is not linked by default; the greeter needs it
        # to list X11 sessions
        etc_parts.append(
            '  environment.pathsToLink = [ "/share/xsessions" ];\n'
        )
        # force the setuid X wrapper on: our xorg-server has no logind
        # integration, so rootless X under elogind doesn't work
        etc_parts.append(
            "  security.wrappers.X.enable = lib.mkForce true;\n"
        )

    if needs["niri"]:
        pkg_parts.append(
            "    # niri's excellent built-in defaults (Mod+Shift+/ shows them all)\n"
            "    # spawn alacritty (Mod+T) and fuzzel (Mod+D); install both so the\n"
            "    # defaults work; ~/.config/niri/config.kdl customizes as usual\n"
            "    pkgs.alacritty\n"
            "    pkgs.fuzzel\n"
        )

    if needs["labwc"] or needs["sway"] or needs["mango"]:
        pkg_parts.append(
            "    # the launcher every default config above binds to Super+D\n"
            "    pkgs.rofi\n"
        )

    # swaybg draws the wallpaper; labwc/sway resolve it through PATH
    if needs["labwc"] or needs["sway"] or needs["noctalia"]:
        pkg_parts.append("    pkgs.swaybg\n")

    # seed each user's ~/.config with editable copies of the default
    # configs. Runs from activation (homes are created at boot, not at
    # install time); never overwrites existing files
    seed_pairs = []
    if needs["labwc"]:
        seed_pairs.append(("/etc/xdg/labwc", ".config/labwc"))
    if needs["sway"]:
        seed_pairs.append(("/etc/sway/config", ".config/sway/config"))
    if needs["mango"]:
        seed_pairs.append(("/etc/mango/config.conf", ".config/mango/config.conf"))
    if needs["nvwm"]:
        # nvwm loads /etc/nvwm/config.conf first and ~/.config/nvwm/config.conf
        # last, so the seeded copy wins (verified in nvwm.c loadcfg()).
        seed_pairs.append(("/etc/nvwm/config.conf", ".config/nvwm/config.conf"))
    # vxwm is not seeded on purpose: it is dwm-style, its configuration is
    # compiled in (config.def.h) and it reads no runtime config file.
    if seed_pairs:
        seeds = "".join(
            '      seed "{}" "$h/{}"\n'.format(src, dst) for src, dst in seed_pairs
        )
        let_parts.append(
            '  seed-user-configs = pkgs.writeShellScript "seed-user-configs" \'\'\n'
            "    export PATH=${pkgs.coreutils}/bin:$PATH\n"
            "    seed() {\n"
            '      [ -e "$1" ] || return 0\n'
            '      [ -e "$2" ] && return 0\n'
            '      mkdir -p "$(dirname "$2")"\n'
            "      # -L: resolve the /etc/static -> store symlinks into real,\n"
            "      # writable files; chmod: store files are read-only\n"
            '      cp -rL "$1" "$2" || return 0\n'
            '      chmod -R u+w "$2"\n'
            "    }\n"
            "    while IFS=: read -r user _ uid gid _ home _; do\n"
            '      [ "$uid" -ge 1000 ] && [ "$uid" -lt 65000 ] || continue\n'
            '      [ -d "$home" ] || continue\n'
            '      h="$home"\n'
            + seeds +
            '      chown -R "$uid:$gid" "$h/.config" 2>/dev/null || true\n'
            "    done < /etc/passwd\n"
            "  \'\';\n"
        )
        etc_parts.append(
            "  system.activation.scripts.seed-user-configs = {\n"
            '    deps = [ "users" ];\n'
            "    text = \"${seed-user-configs}\";\n"
            "  };\n"
        )

    # power shims for the seatd flavor: poweroff/reboot/zzz go through
    # passwordless sudo so desktop power buttons work without elogind
    if not needs["elogind"] and not needs["console_only"]:
        poweroff_cmd = "${config.finit.package}/bin/initctl poweroff"
        reboot_cmd = "${config.finit.package}/bin/initctl reboot"
        pkg_parts.append(
            '    (lib.setPrio (-15) (pkgs.writeShellScriptBin "poweroff" \'\'\n'
            '      [ "$(id -u)" = 0 ] && exec ' + poweroff_cmd + "\n"
            "      exec sudo -n " + poweroff_cmd + "\n"
            "    \'\'))\n"
            '    (lib.setPrio (-15) (pkgs.writeShellScriptBin "reboot" \'\'\n'
            '      [ "$(id -u)" = 0 ] && exec ' + reboot_cmd + "\n"
            "      exec sudo -n " + reboot_cmd + "\n"
            "    \'\'))\n"
            '    (pkgs.writeShellScriptBin "zzz" \'\'\n'
            '      [ "$(id -u)" = 0 ] && exec ${pkgs.writeShellScript "finix-suspend" "echo mem > /sys/power/state"}\n'
            '      exec sudo -n ${pkgs.writeShellScript "finix-suspend" "echo mem > /sys/power/state"}\n'
            "    \'\')\n"
        )
        etc_parts.append(
            "  # exact commands only, wheel group, no password (see shims above)\n"
            "  environment.etc.sudoers.text = lib.mkOrder 2000 ''\n"
            "    %wheel ALL=(root) NOPASSWD: " + poweroff_cmd + ", " + reboot_cmd
            + ', ${pkgs.writeShellScript "finix-suspend" "echo mem > /sys/power/state"}\n'
            "  '';\n"
        )

    if not let_parts and not etc_parts and not pkg_parts:
        return (
            "# Generated by the finix installer. No extra session glue needed for\n"
            "# the selected sessions.\n"
            "{ ... }:\n\n{ }\n"
        )
    if not let_parts:
        out = (
            "# Generated by the finix installer: session glue for the selected\n"
            "# desktop sessions.\n"
            "{ config, pkgs, lib, ... }:\n\n{\n"
        )
        if pkg_parts:
            out += "  environment.systemPackages = [\n" + "".join(pkg_parts) + "  ];\n"
        out += "".join(etc_parts) + "}\n"
        return out

    out = (
        "# Generated by the finix installer: session launchers and packages for\n"
        "# the selected desktop sessions (Noctalia shell variants, NVWM).\n"
        "{\n  config,\n  pkgs,\n  lib,\n  inputs,\n  ...\n}:\nlet\n"
        + "\n".join(let_parts)
        + "in\n{\n"
    )
    if pkg_parts:
        out += "  environment.systemPackages = [\n" + "".join(pkg_parts) + "  ];\n"
    out += "".join(etc_parts)
    out += "}\n"
    return out
def env_is_set(name):
    envValue = os.environ.get(name)
    return not (envValue is None or envValue == "")

def generateProxyStrings():
    proxyEnv = []
    if env_is_set('http_proxy'):
        proxyEnv.append('http_proxy={}'.format(os.environ.get('http_proxy')))
    if env_is_set('https_proxy'):
        proxyEnv.append('https_proxy={}'.format(os.environ.get('https_proxy')))
    if env_is_set('HTTP_PROXY'):
        proxyEnv.append('HTTP_PROXY={}'.format(os.environ.get('HTTP_PROXY')))
    if env_is_set('HTTPS_PROXY'):
        proxyEnv.append('HTTPS_PROXY={}'.format(os.environ.get('HTTPS_PROXY')))

    if len(proxyEnv) > 0:
        proxyEnv.insert(0, "env")

    return proxyEnv

def pretty_name():
    return _("Installing finix.")


status = pretty_name()


def pretty_status_message():
    return status


def catenate(d, key, *values):
    """
    Sets @p d[key] to the string-concatenation of @p values
    if none of the values are None.
    This can be used to set keys conditionally based on
    the values being found.
    """
    if [v for v in values if v is None]:
        return

    d[key] = "".join(values)


def fix_btrfs_subvolumes(hardware_config, partitions):
    """
    Fix btrfs subvolume configuration in hardware-configuration.nix.

    nixos-generate-config generates incorrect subvol options for btrfs
    by setting them to mount points instead of actual subvolume names.
    This function corrects the subvol options to match what Calamares configured.
    """
    # Map of mount points to their correct btrfs subvolume names
    # These match what is configured in mount.conf btrfsSubvolumes
    # Root uses top-level (no subvolume) for GRUB compatibility
    subvol_map = {
        "/home": "home",
        "/nix": "nix",
    }

    # Check if root is actually btrfs
    root_is_btrfs = False
    for part in partitions:
        if part.get("mountPoint") == "/" and part.get("fs") == "btrfs":
            root_is_btrfs = True
            break

    if not root_is_btrfs:
        return hardware_config

    libcalamares.utils.debug("Fixing btrfs subvolume configuration")

    # Fix subvol options for each mount point
    # nixos-generate-config may generate "subvol=/" instead of "subvol=@"
    for mount_point, correct_subvol in subvol_map.items():
        # Match any "subvol=<something>" and replace with correct subvolume
        # This handles cases like "subvol=/" or "subvol=/home"
        pattern = r'(fileSystems\."{}"[^;]*"subvol=)[^"]*"'.format(re.escape(mount_point))
        replacement = r'\g<1>{}"'.format(correct_subvol)
        hardware_config = re.sub(pattern, replacement, hardware_config, flags=re.DOTALL)

    return hardware_config


_FINIX_HW_KEEP_PREFIXES = (
    "boot.initrd.availableKernelModules",
    "boot.initrd.kernelModules",
    "boot.kernelModules",
    "boot.extraModulePackages",
    "fileSystems.",
    "fileSystems",
    "swapDevices",
)


def _finix_split_top_level(body):
    """Split a Nix attrset body into top-level statements (terminated by ';'
    at bracket depth 0). Tracks (){}[] depth and skips '#' line comments so
    that ';' inside nested blocks or comments does not split a statement."""
    stmts = []
    buf = []
    depth = 0
    in_comment = False
    for c in body:
        if in_comment:
            buf.append(c)
            if c == "\n":
                in_comment = False
            continue
        if c == "#":
            in_comment = True
            buf.append(c)
            continue
        if c in "[{(":
            depth += 1
        elif c in "]})":
            depth -= 1
        buf.append(c)
        if c == ";" and depth == 0:
            stmts.append("".join(buf))
            buf = []
    tail = "".join(buf)
    return stmts, tail


def _finix_stmt_key(stmt):
    """Return the bare left-hand-side attribute path of a Nix statement,
    with leading comments/whitespace stripped (e.g. 'boot.kernelModules')."""
    lhs = stmt.split("=", 1)[0]
    lhs = "\n".join(line.split("#", 1)[0] for line in lhs.splitlines())
    return lhs.strip()


def finixify_hardware_config(hardware_config):
    """
    Strip NixOS-only options from nixos-generate-config output so the generated
    hardware-configuration.nix evaluates against finix's (much smaller) module
    set. finix does not define hardware.enableRedistributableFirmware (pulled in
    via the not-detected.nix import), hardware.cpu.*.updateMicrocode,
    networking.useDHCP, nixpkgs.hostPlatform, powerManagement.*, etc. Per the
    upstream finix install docs, the file must be reduced to boot.initrd.*,
    boot.kernelModules, boot.extraModulePackages, fileSystems.*, swapDevices,
    plus an explicit hardware.firmware = [ pkgs.linux-firmware ] for wireless/GPU
    firmware. Uses a keep-list so any future NixOS-only addition is dropped too.
    """
    # Split off the function-argument header: the ':' after the first balanced
    # { ... } (the argument attrset).
    first_open = hardware_config.find("{")
    if first_open == -1:
        return hardware_config
    depth = 0
    i = first_open
    while i < len(hardware_config):
        ch = hardware_config[i]
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                break
        i += 1
    colon = hardware_config.find(":", i)
    if colon == -1:
        return hardware_config
    header = hardware_config[: colon + 1]

    # Locate the body attrset that follows the header.
    rest = hardware_config[colon + 1 :]
    body_open = rest.find("{")
    if body_open == -1:
        return hardware_config
    depth = 0
    j = body_open
    while j < len(rest):
        ch = rest[j]
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                break
        j += 1
    body = rest[body_open + 1 : j]

    stmts, _tail = _finix_split_top_level(body)
    kept = []
    for stmt in stmts:
        key = _finix_stmt_key(stmt)
        if any(key == p or key.startswith(p) for p in _FINIX_HW_KEEP_PREFIXES):
            kept.append(stmt)

    new_body = "".join(kept).rstrip()
    return (
        header
        + "\n\n{\n"
        + new_body
        # linux-firmware: wifi/bt/gpu blobs; sof-firmware: intel audio DSP
        + "\n\n  hardware.firmware = [\n    pkgs.linux-firmware\n    pkgs.sof-firmware\n  ];\n}\n"
    )


# nix internal-json activity/result types
_ACT_COPY_PATH = 100
_ACT_COPY_PATHS = 103
_ACT_BUILDS = 104
_RES_PROGRESS = 105


class NixProgress:
    """Parse nix internal-json output and track build/copy progress."""

    def __init__(self):
        self._builds_done = 0
        self._builds_expected = 0
        self._copies_done = 0
        self._copies_expected = 0
        self._per_act_progress = {}
        self._copy_bytes = {}
        self._activities = {}
        self.fraction = 0.0
        self._floor = 0.0
        self._floor_done = 0
        self.log_messages = []

    def handle(self, line):
        """Process one line. Returns True for @nix lines, False for plain text."""
        line = line.strip()
        if not line:
            return True
        if not line.startswith("@nix "):
            return False
        try:
            msg = json.loads(line[5:])
        except (json.JSONDecodeError, ValueError):
            return False

        action = msg.get("action")
        if action == "start":
            self._on_start(msg)
        elif action == "stop":
            self._on_stop(msg)
        elif action == "result":
            self._on_result(msg)
        elif action == "msg":
            level = msg.get("level", 0)
            text = msg.get("msg", "")
            if level <= 1 and text:
                self.log_messages.append(text)

        self._update()
        return True

    def _on_start(self, msg):
        act_id = msg["id"]
        act_type = msg.get("type", 0)
        self._activities[act_id] = act_type
        text = msg.get("text", "")
        if text and msg.get("level", 5) <= 3:
            self.log_messages.append(text)

    def _on_stop(self, msg):
        act_id = msg["id"]
        self._activities.pop(act_id, None)
        self._copy_bytes.pop(act_id, None)

    def _on_result(self, msg):
        act_id = msg["id"]
        res_type = msg.get("type", 0)
        fields = msg.get("fields", [])
        act_type = self._activities.get(act_id, 0)

        if res_type != _RES_PROGRESS or len(fields) < 2:
            return
        if act_type == _ACT_BUILDS:
            self._per_act_progress[(act_type, act_id)] = (
                "builds",
                fields[0],
                fields[1],
            )
            self._recompute_counts()
        elif act_type == _ACT_COPY_PATHS:
            self._per_act_progress[(act_type, act_id)] = (
                "copies",
                fields[0],
                fields[1],
            )
            self._recompute_counts()
        elif act_type == _ACT_COPY_PATH:
            self._copy_bytes[act_id] = (fields[0], max(fields[1], 1))

    def _update(self):
        count_total = self._builds_expected + self._copies_expected
        count_done = self._builds_done + self._copies_done
        if count_total <= 0:
            return

        # Prevents the channel copy (1 path) from dominating the
        # entire progress bar before the main build starts.
        effective_total = max(count_total, 3)
        count_frac = count_done / effective_total

        # large single-path copies move the bar.
        total_bytes = sum(t for _, t in self._copy_bytes.values())
        done_bytes = sum(d for d, _ in self._copy_bytes.values())
        if total_bytes > 0:
            byte_sub = done_bytes / total_bytes
            step = len(self._copy_bytes) / effective_total
            raw = count_frac + byte_sub * step
        else:
            raw = count_frac
        raw = max(0.0, min(1.0, raw))

        # When the denominator grows (e.g. main build discovers hundreds
        # of new paths), remap remaining work into remaining bar space.
        if raw >= self._floor:
            self._floor = raw
            self._floor_done = count_done
        else:
            new_items = count_done - self._floor_done
            remaining = effective_total - self._floor_done
            if remaining > 0 and new_items >= 0:
                raw = self._floor + (new_items / remaining) * (1.0 - self._floor)
            else:
                raw = self._floor
            raw = max(0.0, min(1.0, raw))
            if raw > self._floor:
                self._floor = raw
                self._floor_done = count_done

        self.fraction = raw

    def _recompute_counts(self):
        bd = be = cd = ce = 0
        for kind, done, expected in self._per_act_progress.values():
            if kind == "builds":
                bd += done
                be += expected
            else:
                cd += done
                ce += expected
        self._builds_done = bd
        self._builds_expected = be
        self._copies_done = cd
        self._copies_expected = ce


def run():
    """finix Configuration."""

    INSTALL_PROGRESS_START = 0.1
    INSTALL_PROGRESS_END = 1.0

    global status
    status = _("Configuring finix")
    libcalamares.job.setprogress(0.01)

    ngc_cfg = configparser.ConfigParser()
    ngc_cfg["Defaults"] = { "Kernel": "lts" }
    ngc_cfg.read("/etc/nixos-generate-config.conf")

    # Create initial config file
    cfg = cfghead
    gs = libcalamares.globalstorage
    variables = dict()

    # Setup variables
    root_mount_point = gs.value("rootMountPoint")
    # naming choice: /etc/finix + finix-rebuild or /etc/nixos + nixos-rebuild
    naming = (gs.value("packagechooser_naming") or "").strip()
    if naming not in ("finix", "nixos"):
        naming = "finix"
    etcrel = "etc/nixos" if naming == "nixos" else "etc/finix"
    etcdir = "/" + etcrel
    rebuildcmd = "nixos-rebuild" if naming == "nixos" else "finix-rebuild"
    catenate(variables, "etcdir", etcdir)
    catenate(variables, "rebuildcmd", rebuildcmd)
    config = os.path.join(root_mount_point, etcrel, "configuration.nix")
    fw_type = gs.value("firmwareType")
    bootdev = (
        "nodev"
        if gs.value("bootLoader") is None
        else gs.value("bootLoader")["installPath"]
    )

    # Pick config parts and prepare substitution

    # Check if root filesystem is btrfs
    root_is_btrfs = False
    for part in gs.value("partitions"):
        if part.get("mountPoint") == "/" and part.get("fs") == "btrfs":
            root_is_btrfs = True
            break

    # Check bootloader
    if fw_type == "efi":
        cfg += cfgbootefi
    elif bootdev != "nodev":
        # Use btrfs-specific config to avoid blkid issues with subvolumes
        if root_is_btrfs:
            cfg += cfgbootbiosbtrfs
        else:
            cfg += cfgbootbios
        catenate(variables, "bootdev", bootdev)
    else:
        cfg += cfgbootnone

    if ngc_cfg["Defaults"]["Kernel"] == "latest":
        cfg += cfglatestkernel

    # LUKS is not supported yet (finix has no boot.initrd.luks.devices);
    # warn instead of emitting options that don't exist
    for part in gs.value("partitions"):
        if (
            part["claimed"] is True
            and (part["fsName"] == "luks" or part["fsName"] == "luks2")
        ):
            libcalamares.utils.warning(
                "LUKS partition {} detected: encrypted installs are not "
                "supported by the finix installer yet; skipping initrd LUKS "
                "config for it".format(part.get("device"))
            )

    # Check partitions
    root_is_encrypted = False
    boot_is_encrypted = False
    boot_is_partition = False

    for part in gs.value("partitions"):
        if part["mountPoint"] == "/":
            root_is_encrypted = part["fsName"] in ["luks", "luks2"]
        elif part["mountPoint"] == "/boot":
            boot_is_partition = True
            boot_is_encrypted = part["fsName"] in ["luks", "luks2"]

    status = _("Configuring finix")
    libcalamares.job.setprogress(0.03)

    # Desktop / compositor selection (multi-select packagechooser: the value
    # is a comma-separated list of ids).
    selected, needs = parse_desktop_selection(
        gs.value("packagechooser_packagechooser") or "",
        warn=libcalamares.utils.warning,
    )


    # cap compiler parallelism by available RAM; used for the install and
    # written into the installed config
    build_cores = 0  # 0 = nix default (all cores)
    try:
        mem_gb = 0
        with open("/proc/meminfo") as f:
            for line in f:
                if line.startswith("MemTotal:"):
                    mem_gb = int(line.split()[1]) // (1024 * 1024)
                    break
        cpus = os.cpu_count() or 4
        if mem_gb and mem_gb < 20:
            # about one compile job per 2 GB of RAM
            build_cores = max(1, min(cpus, mem_gb // 2))
    except Exception as e:
        libcalamares.utils.debug("could not size build cores: {}".format(e))

    if build_cores:
        cfg += cfgnixlowram
        catenate(variables, "buildcores", str(build_cores))

    # eudev + elogind when plasma is selected, otherwise mdevd + seatd
    cfg += cfgelogind if needs["elogind"] else cfgseatd

    # networking: dhcpcd + iwd (NetworkManager doesn't work under mdevd)
    cfg += cfgnetfinix
    cfg += cfgnetwork

    # hostname from the users page, default "finix"
    if gs.value("hostname"):
        catenate(variables, "hostname", gs.value("hostname"))
    else:
        catenate(variables, "hostname", "finix")

    if gs.value("locationRegion") is not None and gs.value("locationZone") is not None:
        cfg += cfgtime
        catenate(
            variables,
            "timezone",
            gs.value("locationRegion"),
            "/",
            gs.value("locationZone"),
        )

    if gs.value("localeConf") is not None:
        localeconf = gs.value("localeConf")
        locale = localeconf.pop("LANG").split("/")[0]
        cfg += cfglocale
        catenate(variables, "LANG", locale)
        if (
            len(set(localeconf.values())) != 1
            or list(set(localeconf.values()))[0] != locale
        ):
            cfg += cfglocaleextra
            for conf in localeconf:
                catenate(variables, conf, localeconf.get(conf).split("/")[0])

    # greeter: greetd/tuigreet (with xsessions when an X11 session is in)
    if needs["console_only"]:
        cfg += cfggreetnone
    elif needs["nvwm"] or needs["vxwm"]:
        cfg += cfggreettuix11
    else:
        cfg += cfggreettui

    # audio stack (pipewire)
    if needs["audio"]:
        cfg += cfgaudio

    # session options, deduplicated across selections
    session_opts = []
    for s in selected:
        cfg += "  # --- {} ---\n".format(cfgsessions[s]["comment"])
        for opt in cfgsessions[s]["opts"]:
            if opt not in session_opts:
                session_opts.append(opt)
                cfg += "  {} = true;\n".format(opt)
        cfg += "\n"

    if (
        gs.value("keyboardLayout") is not None
        and gs.value("keyboardVariant") is not None
    ):
        cfg += cfgkeymap
        catenate(variables, "kblayout", gs.value("keyboardLayout"))
        catenate(variables, "kbvariant", gs.value("keyboardVariant"))

        if gs.value("keyboardVConsoleKeymap") is not None:
            try:
                subprocess.check_output(
                    ["pkexec", "loadkeys", gs.value("keyboardVConsoleKeymap").strip()],
                    stderr=subprocess.STDOUT,
                )
                cfg += cfgconsole
                catenate(
                    variables, "vconsole", gs.value("keyboardVConsoleKeymap").strip()
                )
            except subprocess.CalledProcessError as e:
                libcalamares.utils.error("loadkeys: {}".format(e.output))
                libcalamares.utils.error(
                    "Setting vconsole keymap to {} will fail, using default".format(
                        gs.value("keyboardVConsoleKeymap").strip()
                    )
                )
        else:
            kbdmodelmap = open(
                "/run/current-system/sw/share/systemd/kbd-model-map", "r"
            )
            kbd = kbdmodelmap.readlines()
            out = []
            for line in kbd:
                if line.startswith("#"):
                    continue
                out.append(line.split())
            # Find rows with same layout
            find = []
            for row in out:
                if gs.value("keyboardLayout") == row[1]:
                    find.append(row)
            if find != []:
                vconsole = find[0][0]
            else:
                vconsole = ""
            if gs.value("keyboardVariant") is not None:
                variant = gs.value("keyboardVariant")
            else:
                variant = "-"
            # Find rows with same variant
            for row in find:
                if variant in row[3]:
                    vconsole = row[0]
                    break
                # If none found set to "us"
            if vconsole != "" and vconsole != "us" and vconsole is not None:
                try:
                    subprocess.check_output(
                        ["pkexec", "loadkeys", vconsole], stderr=subprocess.STDOUT
                    )
                    cfg += cfgconsole
                    catenate(variables, "vconsole", vconsole)
                except subprocess.CalledProcessError as e:
                    libcalamares.utils.error("loadkeys: {}".format(e.output))
                    libcalamares.utils.error("vconsole value: {}".format(vconsole))
                    libcalamares.utils.error(
                        "Setting vconsole keymap to {} will fail, using default".format(
                            gs.value("keyboardVConsoleKeymap")
                        )
                    )

    if (
        gs.value("packagechooser_packagechooser") is not None
        and gs.value("packagechooser_packagechooser") != ""
    ):
        cfg += cfgmisc

    if gs.value("username") is not None:
        fullname = gs.value("fullname")
        # wheel = sudo, video = gpu; audio/networkmanager only when the
        # matching stack is enabled
        groups = ["wheel", "video"]
        if needs["audio"]:
            groups.append("audio")
        if needs["nm"]:
            groups.append("networkmanager")

        cfg += cfgusers
        catenate(variables, "username", gs.value("username"))
        catenate(variables, "fullname", fullname)
        # seatd group only exists on the seatd flavor
        groups_nix = (" ").join(['"' + s + '"' for s in groups])
        if not needs["elogind"]:
            groups_nix += " config.services.seatd.group"
        catenate(variables, "groups", groups_nix)
        if (
            gs.value("autoLoginUser") is not None
            and gs.value("packagechooser_packagechooser") is not None
            and gs.value("packagechooser_packagechooser") != ""
        ):
            cfg += cfgautologin
            if gs.value("packagechooser_packagechooser") == "gnome":
                cfg += cfgautologingdm
        elif gs.value("autoLoginUser") is not None:
            cfg += cfgautologintty

    # Check if unfree packages are allowed
    free = True
    if gs.value("nixos_allow_unfree"):
        free = False
        cfg += cfgunfree

    # hardware auto-detection (nvidia driver only if unfree is allowed)
    cfg += build_hardware_drivers(
        detect_cpu_vendor(), detect_gpu_vendors(), not free
    )

    cfg += cfgpkgs
    catenate(variables, "pkgs", "")

    cfg += cfgtail

    # Check that all variables are used
    for key in variables.keys():
        pattern = "@@{key}@@".format(key=key)
        if pattern not in cfg:
            libcalamares.utils.warning("Variable '{key}' is not used.".format(key=key))

    # Check that all patterns exist
    variable_pattern = re.compile(r"@@\w+@@")
    for match in variable_pattern.finditer(cfg):
        variable_name = cfg[match.start() + 2 : match.end() - 2]
        if variable_name not in variables:
            libcalamares.utils.warning(
                "Variable '{key}' is used but not defined.".format(key=variable_name)
            )

    # Do the substitutions
    for key in variables.keys():
        pattern = "@@{key}@@".format(key=key)
        cfg = cfg.replace(pattern, str(variables[key]))

    status = _("Generating finix configuration")
    libcalamares.job.setprogress(0.05)

    try:
        # Generate hardware.nix with mounted swap device
        subprocess.check_output(
            ["pkexec", "nixos-generate-config", "--root", root_mount_point],
            stderr=subprocess.STDOUT,
        )
    except subprocess.CalledProcessError as e:
        if e.output is not None:
            libcalamares.utils.error(e.output.decode("utf8"))
        return (_("nixos-generate-config failed"), _(e.output.decode("utf8")))

    # relocate nixos-generate-config output when finix naming is chosen
    if etcrel != "etc/nixos":
        libcalamares.utils.host_env_process_output(
            ["mkdir", "-p", root_mount_point + "/" + etcrel], None
        )
        libcalamares.utils.host_env_process_output(
            [
                "mv",
                root_mount_point + "/etc/nixos/hardware-configuration.nix",
                root_mount_point + "/" + etcrel + "/hardware-configuration.nix",
            ],
            None,
        )
        libcalamares.utils.host_env_process_output(
            ["rm", "-rf", root_mount_point + "/etc/nixos"], None
        )

    # Read and fix hardware-configuration.nix
    hf = open(root_mount_point + "/" + etcrel + "/hardware-configuration.nix", "r")
    htxt = hf.read()
    hf.close()

    hardware_modified = False

    # strip NixOS-only options finix doesn't define, inject hardware.firmware
    try:
        htxt_finix = finixify_hardware_config(htxt)
        if htxt_finix != htxt:
            htxt = htxt_finix
            hardware_modified = True
    except Exception as e:
        libcalamares.utils.warning(
            "finixify_hardware_config failed, using raw nixos-generate-config "
            "output (install may fail on NixOS-only options): {}".format(e)
        )

    # Fix btrfs subvolume configuration if needed
    htxt_fixed = fix_btrfs_subvolumes(htxt, gs.value("partitions"))
    if htxt_fixed != htxt:
        htxt = htxt_fixed
        hardware_modified = True

    # Check for unfree stuff in hardware-configuration.nix
    search = re.search(r"boot\.extraModulePackages = \[ (.*) \];", htxt)

    # Check if any extraModulePackages are defined, and remove if only free packages are allowed
    if search is not None and free:
        expkgs = search.group(1).split(" ")
        for pkg in expkgs:
            p = ".".join(pkg.split(".")[3:])
            # Check package p is unfree
            isunfree = subprocess.check_output(
                [
                    "nix-instantiate",
                    "--eval",
                    "--strict",
                    "-E",
                    "with import <nixpkgs> {{}}; pkgs.linuxKernel.packageAliases.linux_default.{}.meta.unfree".format(
                        p
                    ),
                    "--json",
                ],
                stderr=subprocess.STDOUT,
            )
            if isunfree == b"true":
                libcalamares.utils.warning(
                    "{} is marked as unfree, removing from hardware-configuration.nix".format(
                        p
                    )
                )
                expkgs.remove(pkg)
        htxt = re.sub(
            r"boot\.extraModulePackages = \[ (.*) \];",
            "boot.extraModulePackages = [ {}];".format(
                "".join(map(lambda x: x + " ", expkgs))
            ),
            htxt,
        )
        hardware_modified = True

    # Write the hardware-configuration.nix file if modified
    if hardware_modified:
        libcalamares.utils.host_env_process_output(
            [
                "cp",
                "/dev/stdin",
                root_mount_point + "/" + etcrel + "/hardware-configuration.nix",
            ],
            None,
            htxt,
        )

    # Write the configuration.nix file
    libcalamares.utils.host_env_process_output(["cp", "/dev/stdin", config], None, cfg)

    # Write the flake.nix that makes the installed system a finix system (finit PID 1).
    flakepath = os.path.join(root_mount_point, etcrel, "flake.nix")
    libcalamares.utils.host_env_process_output(
        ["cp", "/dev/stdin", flakepath], None, build_flake(needs)
    )

    # Write sessions.nix (always imported by the flake; may be a no-op module).
    sessionspath = os.path.join(root_mount_point, etcrel, "sessions.nix")
    libcalamares.utils.host_env_process_output(
        ["cp", "/dev/stdin", sessionspath], None, build_sessions_nix(needs, etcdir)
    )

    # Write branding.nix (always imported: finix-labelled limine boot menu).
    brandingpath = os.path.join(root_mount_point, etcrel, "branding.nix")
    libcalamares.utils.host_env_process_output(
        ["cp", "/dev/stdin", brandingpath], None, BRANDING_NIX
    )

    # ship the wallpaper next to the flake; configs reference it there
    wallpaper_src = os.path.join(os.path.dirname(__file__), "finixwallpaper.png")
    if os.path.exists(wallpaper_src):
        libcalamares.utils.host_env_process_output(
            [
                "cp",
                wallpaper_src,
                os.path.join(root_mount_point, etcrel, "wallpaper.png"),
            ],
            None,
        )
    else:
        libcalamares.utils.warning(
            "finixwallpaper.png not found next to main.py; installed sessions "
            "will fall back to a plain background"
        )

    # Write the vendored Plasma module only when the plasma session was
    # selected (the flake imports it conditionally too).
    if needs["plasma"]:
        plasmapath = os.path.join(root_mount_point, etcrel, "plasma.nix")
        libcalamares.utils.host_env_process_output(
            ["cp", "/dev/stdin", plasmapath], None,
            PLASMA_NIX.replace("@@wallpaper@@", etcdir + "/wallpaper.png"),
        )

    # git init the flake dir: on a plain path flake the flake.lock write
    # invalidates the source hash (NAR hash mismatch)
    nixosDir = os.path.join(root_mount_point, etcrel)
    try:
        subprocess.check_output(["git", "init", "-q", nixosDir], stderr=subprocess.STDOUT)
        subprocess.check_output(["git", "-C", nixosDir, "add", "-A"], stderr=subprocess.STDOUT)
        subprocess.check_output(
            [
                "git", "-C", nixosDir,
                "-c", "user.email=installer@finix.local",
                "-c", "user.name=finix Installer",
                "commit", "-q", "-m", "finix generated system configuration",
            ],
            stderr=subprocess.STDOUT,
        )
    except subprocess.CalledProcessError as e:
        libcalamares.utils.warning(
            "git init of {} failed (flake install may hit a NAR hash mismatch): {}".format(
                nixosDir, e.output
            )
        )

    status = _("Installing finix")
    libcalamares.job.setprogress(INSTALL_PROGRESS_START)

    try:
        subprocess.check_output(
            ["pkexec", "chmod", "755", root_mount_point],
            stderr=subprocess.STDOUT,
        )
    except subprocess.CalledProcessError as e:
        libcalamares.utils.warning("Failed to set permissions on {}: {}".format(root_mount_point, e.output))

    # enable target swap during the install; helps low-RAM machines
    for part in gs.value("partitions"):
        if part.get("fs") == "linuxswap" and part.get("device"):
            try:
                subprocess.check_output(
                    ["pkexec", "swapon", part["device"]],
                    stderr=subprocess.STDOUT,
                )
                libcalamares.utils.debug(
                    "enabled swap on {} for the install".format(part["device"])
                )
            except subprocess.CalledProcessError as e:
                # already on / not formatted yet / zram-only setups: harmless
                libcalamares.utils.debug(
                    "swapon {} skipped: {}".format(part.get("device"), e.output)
                )

    # bind-mount a target-disk scratch dir over /nix/var/nix/builds:
    # large source builds otherwise fill the live ISO's RAM store
    build_scratch = os.path.join(root_mount_point, "var/tmp/finix-installer-build")
    build_dir_bound = False
    try:
        subprocess.check_output(
            ["pkexec", "mkdir", "-p", build_scratch, "/nix/var/nix/builds"],
            stderr=subprocess.STDOUT,
        )
        subprocess.check_output(
            ["pkexec", "mount", "--bind", build_scratch, "/nix/var/nix/builds"],
            stderr=subprocess.STDOUT,
        )
        build_dir_bound = True
    except subprocess.CalledProcessError as e:
        libcalamares.utils.warning(
            "could not bind-mount the build dir onto the target disk "
            "(large source builds may exhaust the live RAM): {}".format(e.output)
        )

    # build nixos-install command
    nixosInstallCmd = [ "pkexec" ]
    nixosInstallCmd.extend(generateProxyStrings())
    nixosInstallCmd.extend(
        [
            "nixos-install",
            "--no-root-passwd",
            "--root",
            root_mount_point,
            # build from the generated finix flake
            "--flake",
            os.path.join(root_mount_point, etcrel) + "#finixos",
            # serialize derivation builds; parallel source builds can
            # exhaust memory
            "--max-jobs",
            "1",
        ]
    )
    if build_cores:
        nixosInstallCmd.extend(["--cores", str(build_cores)])
    nixosInstallCmd.extend(
        [
            "--option",
            "experimental-features",
            "nix-command flakes",
            "--log-format",
            "internal-json",
            "--option",
            "build-dir",
            "/nix/var/nix/builds",
        ]
    )

    progress = NixProgress()

    try:
        output = ""
        proc = subprocess.Popen(
            nixosInstallCmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT
        )
        while True:
            line = proc.stdout.readline().decode("utf-8")
            if not line:
                break

            was_json = progress.handle(line)

            # Keep output for error reporting
            if not was_json:
                output += line
            for log_line in progress.log_messages:
                output += log_line + "\n"

            mapped = INSTALL_PROGRESS_START + progress.fraction * (
                INSTALL_PROGRESS_END - INSTALL_PROGRESS_START
            )
            libcalamares.job.setprogress(mapped)

            for log_line in progress.log_messages:
                libcalamares.utils.debug("nixos-install: {}".format(log_line))
            progress.log_messages.clear()

            if not was_json:
                libcalamares.utils.debug("nixos-install: {}".format(line.strip()))

        exit = proc.wait()
        if exit != 0:
            return (_("finix installation failed"), _(output))
    except:
        return (_("finix installation failed"), _("Installation failed to complete"))
    finally:
        # undo the bind mount and drop the scratch data
        if build_dir_bound:
            try:
                subprocess.check_output(
                    ["pkexec", "umount", "/nix/var/nix/builds"],
                    stderr=subprocess.STDOUT,
                )
                subprocess.check_output(
                    ["pkexec", "rm", "-rf", build_scratch],
                    stderr=subprocess.STDOUT,
                )
            except subprocess.CalledProcessError as e:
                libcalamares.utils.warning(
                    "build-dir cleanup failed: {}".format(e.output)
                )

    libcalamares.job.setprogress(INSTALL_PROGRESS_END)
    return None
