#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import configparser
import json
import libcalamares
import os
import subprocess
import re

import gettext

_ = gettext.translation(
    "calamares-python",
    localedir=libcalamares.utils.gettext_path(),
    languages=libcalamares.utils.gettext_languages(),
    fallback=True,
).gettext


# The following strings contain pieces of a nix-configuration file.
# They are adapted from the default config generated from the nixos-generate-config command.

cfghead = """# Finix system configuration, generated by the Finix installer.
# Finix uses finit as PID 1 (no systemd), mdevd+seatd (or eudev+elogind when
# KDE Plasma is installed), and the Nix package manager.
# Edit this file, then rebuild with:  sudo finix-rebuild switch
# (the system flake lives in /etc/finix)

{ config, pkgs, ... }:

{
  imports =
    [ # Include the results of the hardware scan.
      ./hardware-configuration.nix
    ];

  # --- Finix core (finit init + Nix daemon) ---
  finit.runlevel = 3;
  finit.services.nix-daemon.environment.CURL_CA_BUNDLE = config.security.pki.caBundle;
  services.nix-daemon.enable = true;
  services.nix-daemon.settings.experimental-features = [ "nix-command" "flakes" ];
  services.nix-daemon.settings.trusted-users = [ "root" "@wheel" ];

  # --- logging / policy (Finix replacements for systemd bits) ---
  # (the device manager — mdevd or eudev — is emitted with the seat
  # management block below; the two choices are coupled)
  services.dbus.enable = true;
  services.sysklogd.enable = true;
  services.polkit.enable = true;

  programs.sudo.enable = true;
  programs.bash.enable = true;
  hardware.graphics.enable = true;
  fonts.fontconfig.enable = true;
  fonts.enableDefaultPackages = true;

"""

# Emitted on low-RAM machines (detected at install time): caps Nix build
# parallelism on the INSTALLED system too, so `finix-rebuild switch` after a
# `nix flake update` (which recompiles the finix-overridden packages) cannot
# freeze the machine the way parallel builds froze the live installer.
cfgnixlowram = """  # Low-RAM machine (detected at install time): build one derivation at a
  # time with limited compiler jobs, so system updates that recompile the
  # Finix-patched packages (compositors, PipeWire, Noctalia) stay safe.
  # Raise these if you add RAM. Delete to return to Nix defaults.
  services.nix-daemon.settings.max-jobs = 1;
  services.nix-daemon.settings.cores = @@buildcores@@;

"""

# --- seat management + device manager: exactly one of the two blocks below
# is emitted. The two choices are COUPLED:
# elogind resolves TakeDevice through the udev device database
# (/run/udev/data), which mdevd does not provide — under mdevd seat0 has
# zero devices and EVERY compositor (KWin and wlroots-via-logind alike)
# dies with "No such device" on /dev/dri/card*. So elogind ships with
# eudev, and the Finix-default mdevd ships with seatd.
# Finix default: mdevd + seatd (wlroots compositors use libseat's seatd
# backend; the same builds worked via seatd on the very boot where the
# elogind path returned ENODEV).
cfgseatd = """  # --- device manager + seat management: mdevd + seatd ---
  services.mdevd.enable = true;
  services.seatd.enable = true;

"""
# (power shims for the seatd flavor are emitted in sessions.nix — a second
# environment.systemPackages in configuration.nix's attrset would be an
# "attribute already defined" eval error)

# elogind: REQUIRED for KDE Plasma — KWin has no libseat/seatd backend at all
# (its only session backends are logind -> ConsoleKit -> Noop). wlroots
# compositors keep working: libseat falls back to its logind backend, and
# with elogind X11 runs rootless (no setuid X wrapper needed).
cfgelogind = """  # --- device manager + seat management: eudev + elogind ---
  # (required by KDE Plasma / KWin; elogind needs the udev database for
  # TakeDevice, so the device manager is eudev instead of mdevd here)
  services.udev.enable = true;
  services.elogind.enable = true;
  # Finix's xorg module selects its libudev implementation from the device
  # manager (libudev-zero for mdevd, libudev-garden for gardendevd) and picks
  # none under eudev, which makes xorg-server build without libudev at all.
  # Point it at eudev's libudev explicitly.
  programs.xorg.package = pkgs.xorg-server.override { udev = pkgs.eudev; };

  # Let wheel users power off / reboot / suspend through elogind without a
  # password. The default policy answers "challenge", and desktop power
  # buttons (Noctalia, Plasma) launch `loginctl poweroff` detached — the
  # prompt has nowhere to go, so the button silently does nothing.
  services.polkit.extraConfig = ''
    polkit.addRule(function(action, subject) {
      if (subject.isInGroup("wheel") &&
          (action.id.indexOf("org.freedesktop.login1.power-off") == 0 ||
           action.id.indexOf("org.freedesktop.login1.reboot") == 0 ||
           action.id.indexOf("org.freedesktop.login1.suspend") == 0 ||
           action.id.indexOf("org.freedesktop.login1.hibernate") == 0)) {
        return polkit.Result.YES;
      }
    });
  '';

"""

# --- networking: exactly one of the two blocks below is emitted ---
# Finix default: dhcpcd + iwd (no NetworkManager/systemd).
cfgnetfinix = """  # --- networking (dhcpcd + iwd; no NetworkManager/systemd) ---
  services.dhcpcd.enable = true;
  services.iwd.enable = true;

"""

# dhcpcd + iwd is the networking stack for every selection, including Plasma:
# NetworkManager reads the udev device database, which mdevd does not provide,
# so under the default device manager it manages nothing. greetd/tuigreet is
# likewise the greeter for every selection — it lists the Plasma Wayland
# session like any other.

# --- login greeter: greetd/tuigreet for every selection ---
# --remember/--remember-session restore the last user + session choice.
cfggreettui = """  # --- login: greetd/tuigreet, listing the installed sessions ---
  services.greetd.enable = true;
  services.greetd.settings.default_session.command = "${pkgs.tuigreet}/bin/tuigreet --time --remember --remember-session --sessions /run/current-system/sw/share/wayland-sessions";

"""

# nvwm (X11) variant: also list xsessions and launch them through startx
# (coreutils env as the wrapper head — /usr/bin/env may not exist on Finix).
cfggreettuix11 = """  # --- login: greetd/tuigreet, listing Wayland and X11 sessions ---
  services.greetd.enable = true;
  services.greetd.settings.default_session.command = "${pkgs.tuigreet}/bin/tuigreet --time --remember --remember-session --sessions /run/current-system/sw/share/wayland-sessions --xsessions /run/current-system/sw/share/xsessions --xsession-wrapper '${config.programs.xinit.package}/bin/startx ${pkgs.coreutils}/bin/env'";

"""

# Minimal install: no display manager at all; finix's getty module (enabled
# by default) provides classic console login on the ttys.
cfggreetnone = """  # --- login: console only (minimal install, no display manager) ---
  # getty is enabled by default; log in on tty1 and configure from there.

"""

# --- audio: PipeWire stack. The session launchers generated in sessions.nix
# start pipewire/wireplumber/pipewire-pulse inside the user session (Finix has
# no systemd user units). rtkit gives the daemons realtime priority.
cfgaudio = """  # --- audio: PipeWire + WirePlumber (started by the session launchers) ---
  programs.pipewire.enable = true;
  programs.pipewire.alsa.enable = true;
  programs.wireplumber.enable = true;
  services.rtkit.enable = true;
  users.groups.audio.gid = config.ids.gids.audio;

"""

# Pinned input revisions for the generated system flake. `nixos-unstable`
# moves daily and has broken installs before (niri failed to compile from
# source on the rev of the day); these pins are exactly what this ISO was
# built and validated against, so the target machine reuses the live ISO's
# store instead of chasing a moving target.
NIXPKGS_REV = "e2587caef70cea85dd97d7daab492899902dbf5d"
FINIX_REV = "8a9b75a16b6f399e12d031dcd714a938af40c9b5"
NOCTALIA_REV = "3d7b9869950592ff7cf3704f6a53afb169d850db"  # v5.0.0-beta.5
NVWM_REV = "58bfe34f14d532b6fdcac3149133cccd2e3bf653"
VXWM_REV = "8b9f04c415a96c92fc36b7639cd1877903f3f0eb"
# newm is a FLAKE input WITHOUT follows: it must keep its own (old) locked
# nixpkgs — that is the only combination it is known to build with.
NEWM_REV = "d120fcc390eba70593aecfafbafefe8647fd5c92"

# Desktop / compositor choices offered by the Calamares packagechooser page
# (multi-select: the user may pick several; every pick is installed).
# Only sessions with real Finix modules (or modules vendored by this
# installer: plasma.nix, sessions.nix) are offered. Each entry:
#   opts:     Finix options set to true in configuration.nix (deduplicated
#             across selections, so e.g. labwc + lxqt both enabling labwc is
#             emitted once)
#   noctalia: compositor id -> a "<compositor> + Noctalia" session launcher
#             is generated in sessions.nix (with XWayland + audio)
#   plasma:   vendored plasma.nix module is written and imported
#   nvwm:     nvwm (X11) package + xsession are generated in sessions.nix
#   audio:    session needs the PipeWire stack emitted
#   sddm:     session needs SDDM instead of greetd/tuigreet
#   nm:       session needs NetworkManager instead of dhcpcd/iwd
cfgsessions = {
    "minimal": {
        "comment": "minimal install: no desktop and no greeter; log in on the console (tty)",
        "opts": [],
        "console": True,
    },
    "labwc": {
        "comment": "desktop: labwc (lightweight Wayland compositor)",
        "opts": ["programs.labwc.enable"],
    },
    "labwc-noctalia": {
        "comment": "desktop: labwc + Noctalia shell (bar, launcher, lock, OSD)",
        "opts": ["programs.labwc.enable"],
        "noctalia": "labwc",
        "audio": True,
    },
    "lxqt": {
        "comment": "desktop: LXQt (full desktop environment, Wayland session on labwc)",
        "opts": ["programs.lxqt.enable", "programs.labwc.enable"],
    },
    "plasma": {
        "comment": "desktop: KDE Plasma 6 (Wayland; experimental on Finix)",
        "opts": ["programs.plasma.enable"],
        "plasma": True,
        "audio": True,
        "elogind": True,
    },
    "sway": {
        "comment": "desktop: Sway (i3-like tiling Wayland compositor)",
        "opts": ["programs.sway.enable"],
    },
    "niri": {
        "comment": "desktop: Niri (scrollable-tiling Wayland compositor)",
        "opts": ["programs.niri.enable"],
    },
    "niri-noctalia": {
        "comment": "desktop: Niri + Noctalia shell (with xwayland-satellite)",
        "opts": ["programs.niri.enable", "programs.xwayland-satellite.enable"],
        "noctalia": "niri",
        "audio": True,
    },
    "vxwm": {
        "comment": "desktop: vxwm (versatile dwm-style X11 tiling WM)",
        "opts": ["programs.xorg.enable", "programs.xinit.enable"],
        "vxwm": True,
        "audio": True,
    },
    "newm": {
        "comment": "desktop: newm (touchpad-centric Wayland compositor, pywm)",
        "opts": [],
        "newm": True,
        "audio": True,
    },
    "mango": {
        "comment": "desktop: Mango / MangoWC (dwl-based tiling Wayland compositor)",
        "opts": ["programs.mango.enable"],
        "mango": True,
    },
    "mango-noctalia": {
        "comment": "desktop: Mango + Noctalia shell",
        "opts": ["programs.mango.enable"],
        "noctalia": "mango",
        "audio": True,
        "mango": True,
    },
    "nvwm": {
        "comment": "desktop: NVWM (vim-inspired tiling X11 window manager)",
        "opts": ["programs.xorg.enable", "programs.xinit.enable"],
        "nvwm": True,
        "audio": True,
    },
}
cfgsessiondefault = "labwc"
# Finix bootloader = limine (UEFI). Dual boot: the installer must NOT reformat the
# existing EFI System Partition, so other-OS UEFI entries stay in the firmware boot
# menu; extra entries can be added under programs.limine.extraEntries if desired.
cfgbootefi = """  # Bootloader: limine (UEFI).
  programs.limine.enable = true;
  programs.limine.efiSupport = true;
  programs.limine.settings.editor_enabled = true;
  # No distro artwork behind the boot menu (the Finix limine module defaults
  # to a NixOS wallpaper); keep the plain dark backdrop instead.
  programs.limine.settings.wallpaper = [ ];
  boot.loader.efi.canTouchEfiVariables = true;

"""

# Legacy BIOS: Finix/limine strongly prefers UEFI (upstream notes legacy boot breaks
# limine detection). We still emit a BIOS limine config, but UEFI is the supported path.
cfgbootbios = """  # Bootloader: limine (legacy BIOS — UEFI is strongly recommended for Finix).
  programs.limine.enable = true;
  programs.limine.biosSupport = true;
  programs.limine.biosDevice = "@@bootdev@@";
  programs.limine.settings.wallpaper = [ ];

"""

cfgbootbiosbtrfs = """  # Bootloader: limine (legacy BIOS — UEFI is strongly recommended for Finix).
  programs.limine.enable = true;
  programs.limine.biosSupport = true;
  programs.limine.biosDevice = "@@bootdev@@";
  programs.limine.settings.wallpaper = [ ];

"""

cfgbootnone = """  # No bootloader (bootloader managed manually).
  programs.limine.enable = false;

"""

# LUKS keyfile handling is bootloader-specific and unverified on limine/Finix; skip.
cfgbootgrubcrypt = ""

cfgnetwork = """  networking.hostName = "@@hostname@@"; # Define your hostname.
  # networking.wireless.enable = true;  # Enables wireless support via wpa_supplicant.

  # Configure network proxy if necessary
  # networking.proxy.default = "http://user:password@proxy:port/";
  # networking.proxy.noProxy = "127.0.0.1,localhost,internal.domain";

"""

# Finix networking is handled in cfghead (dhcpcd + iwd); the NixOS/systemd network
# stacks below are neutralized so nothing systemd-based is emitted.
cfgnetworkmanager = ""

cfgconnman = ""

cfgnmapplet = ""

cfgtime = """  # Set your time zone.
  time.timeZone = "@@timezone@@";

"""

cfglocale = """  # Select internationalisation properties.
  i18n.defaultLocale = "@@LANG@@";

"""

cfglocaleextra = """  i18n.extraLocaleSettings = {
    LC_ADDRESS = "@@LC_ADDRESS@@";
    LC_IDENTIFICATION = "@@LC_IDENTIFICATION@@";
    LC_MEASUREMENT = "@@LC_MEASUREMENT@@";
    LC_MONETARY = "@@LC_MONETARY@@";
    LC_NAME = "@@LC_NAME@@";
    LC_NUMERIC = "@@LC_NUMERIC@@";
    LC_PAPER = "@@LC_PAPER@@";
    LC_TELEPHONE = "@@LC_TELEPHONE@@";
    LC_TIME = "@@LC_TIME@@";
  };

"""

# The stock NixOS desktop-environment blocks (GNOME/Plasma/Xfce/...) are gone:
# they enabled X11 + systemd display managers, and Finix has no modules for
# those desktops. The offered sessions live in cfgsessions above.

# X11 keymap (services.xserver) does not apply on Finix (Wayland/labwc, no xserver module
# enabled). Console keymap below still applies to the TTY; Wayland layout is a follow-up.
cfgkeymap = ""
cfgconsole = """  # Configure console keymap
  hardware.console.keyMap = "@@vconsole@@";

"""

# CUPS/pulseaudio use systemd on NixOS; neutralized for a minimal first Finix boot.
# Audio (pipewire/wireplumber/rtkit are Finix modules) can be added as a follow-up.
cfgmisc = ""
cfgusers = """  # Define a user account. Don't forget to set a password with ‘passwd’.
  users.users."@@username@@" = {
    isNormalUser = true;
    description = "@@fullname@@";
    extraGroups = [ @@groups@@ ];
    packages = with pkgs; [@@pkgs@@];
  };

"""

# Finix has no programs.firefox module (that is a NixOS/systemd-era module).
# The browser is instead added as a plain package in cfgpkgs below.
cfgfirefox = ""

# displayManager autologin is systemd-based; not applicable on Finix (greetd handles login).
cfgautologin = ""

# GNOME/systemd autologin workaround does not apply on Finix (no systemd).
cfgautologingdm = ""

# Finix's services.getty has no autologinUser option (only enable/package/
# extraArgs/ttys); login is handled by greetd. Emitting the NixOS option would
# abort the install with "option does not exist".
cfgautologintty = """  # Automatic login is not supported by the Finix installer yet
  # (services.getty.autologinUser does not exist on Finix; greetd handles login).

"""

# Unfree is allowed via the flake's `import nixpkgs { config.allowUnfree = true; }`
# (finixSystem sets nixpkgs.pkgs directly, so nixpkgs.config is not available here).
cfgunfree = ""

cfgpkgs = """  # List packages installed in system profile. To search, run:
  # $ nix search wget
  environment.systemPackages = with pkgs; [
    vim
    git
    wget
    iproute2 # `ip addr` & friends — finix's base ships no network CLI at all
    pciutils # lspci — invaluable for GPU/driver debugging
    foot # Wayland terminal
    firefox # web browser (plain package; Finix has no programs.firefox module)
    # usermod & friends in /run/current-system/sw/bin: the installer's password
    # step runs `chroot <target> usermod -p <hash> <user>` and resolves the
    # binary through the target's PATH; finix's shadow module only ships the
    # setuid wrappers (su/passwd), not the plain tools. Also useful post-install.
    shadow
    # `sudo finix-rebuild switch` (or boot): stages /etc/finix into git —
    # required, the flake only sees git-tracked files — then rebuilds.
    (writeShellScriptBin "finix-rebuild" ''
      set -e
      ${git}/bin/git -C /etc/finix add -A
      exec ${nixos-rebuild}/bin/nixos-rebuild "''${1:-switch}" --flake /etc/finix#finixos "''${@:2}"
    '')
    # fastfetch: stock binary; the Finix-recolored NixOS snowflake comes from
    # /etc/xdg/fastfetch/config.jsonc (below). A user config in
    # ~/.config/fastfetch/ overrides it entirely — standard fastfetch behavior.
    fastfetch
    # `neofetch` = neowofetch (the maintained neofetch fork from hyfetch;
    # upstream neofetch is unmaintained and no longer in nixpkgs). It has no
    # system-wide config file, so only the two logo flags are baked in
    # (os-release ID=finix is unknown to it and would show Tux); everything
    # else, including ~/.config/neofetch/config.conf, works as usual.
    # Colors: 1 = red, 8 = gray.
    # distro= preset: neowofetch checks for /etc/NIXOS (which the NixOS
    # activation machinery creates and finix keeps — do NOT delete it)
    # BEFORE reading os-release, so it would print "OS: NixOS ...".
    # get_distro() starts with `[[ $distro ]] && return`, and environment
    # variables are visible as shell variables to the script — presetting
    # distro skips detection entirely.
    (writeShellScriptBin "neofetch" ''
      exec env distro="finix $(uname -m)" ${hyfetch}/bin/neowofetch --ascii_distro nixos --ascii_colors 1 8 1 8 1 8 "$@"
    '')
  ];

  # Default fastfetch config: any direct invocation of a stock fastfetch
  # binary also gets the Finix-recolored NixOS snowflake instead of Tux.
  # The "modules" list MUST be spelled out: with a config file present,
  # fastfetch does not fall back to its built-in module list — a logo-only
  # config prints the logo and nothing else (verified on 2.x).
  environment.etc."xdg/fastfetch/config.jsonc".text = builtins.toJSON {
    logo = {
      source = "nixos";
      color = {
        "1" = "31";
        "2" = "90";
        "3" = "31";
        "4" = "90";
        "5" = "31";
        "6" = "90";
      };
    };
    modules = [
      "title" "separator" "os" "host" "kernel" "uptime" "packages" "shell"
      "display" "de" "wm" "wmtheme" "theme" "icons" "font" "cursor"
      "terminal" "terminalfont" "cpu" "gpu" "memory" "swap" "disk"
      "localip" "battery" "poweradapter" "locale" "break" "colors"
    ];
  };

"""

cfgtail = """  # Enable the OpenSSH daemon (optional).
  # services.openssh.enable = true;

  # NOTE: Finix does not use NixOS's system.stateVersion; it is intentionally omitted.
}
"""

cfglatestkernel = """  # Use latest kernel.
  boot.kernelPackages = pkgs.linuxPackages_latest;

"""

# Flake that builds the installed system as a Finix system (finit PID 1) rather than
# stock NixOS. `configuration.nix` + `sessions.nix` (generated above) and
# `hardware-configuration.nix` are imported as modules. finixSystem pulls nixpkgs'
# nixos modules via modulesPath but swaps init/seat/device management.
# All inputs are pinned (see NIXPKGS_REV & friends above).
cfgflaketemplate = """{
  description = "Finix system (installed by the Finix installer)";

  inputs = {
    # Pinned to the revisions this installer ISO was validated against.
    nixpkgs.url = "github:nixos/nixpkgs/@@nixpkgs_rev@@";
    finix.url = "github:finix-community/finix/@@finix_rev@@";
@@extra_inputs@@  };

  outputs = inputs @ { self, nixpkgs, finix, ... }: let
    pkgs = import nixpkgs {
      system = "x86_64-linux";
      config.allowUnfree = true;
    };
  in {
    nixosConfigurations.finixos = finix.lib.finixSystem {
      inherit (pkgs) lib;

      modules = with finix.nixosModules; [
        { nixpkgs.pkgs = nixpkgs.lib.mkDefault pkgs; }
        (./configuration.nix)
        (./sessions.nix)
        (./branding.nix)@@plasma_import@@
        nix-daemon
        openssh
        sysklogd
        limine
        sudo
        polkit
        getty
        bash
        dhcpcd
        iwd
        greetd
        networkmanager
        sddm
        upower
        # session/desktop modules (enable-gated; configuration.nix picks)
        labwc
        sway
        niri
        hyprland
        lxqt
        mango
        # audio / X11 / XWayland support (enable-gated)
        pipewire
        wireplumber
        rtkit
        xwayland-satellite
        xorg
        xinit
      ];

      specialArgs = {
        modulesPath = toString nixpkgs + "/nixos/modules";
        inherit inputs;
      };
    };
  };
}
"""


def parse_desktop_selection(raw_choice, warn=None):
    """Parse the (comma-separated, multi-select) packagechooser value into a
    validated selection list plus the aggregated feature flags. Anything
    unknown is dropped with a warning; an empty result falls back to the
    default so the install never emits options that don't exist on Finix."""
    if warn is None:
        warn = lambda msg: None
    selected = []
    for choice in raw_choice.split(","):
        choice = choice.strip()
        if not choice:
            continue
        if choice not in cfgsessions:
            warn("Unknown desktop choice '{}', skipping".format(choice))
            continue
        if choice not in selected:
            selected.append(choice)
    if not selected:
        warn(
            "No (valid) desktop selected, falling back to {}".format(
                cfgsessiondefault
            )
        )
        selected = [cfgsessiondefault]

    needs = {
        "console_only": all(cfgsessions[s].get("console") for s in selected),
        "elogind": any(cfgsessions[s].get("elogind") for s in selected),
        "audio": any(cfgsessions[s].get("audio") for s in selected),
        "sddm": any(cfgsessions[s].get("sddm") for s in selected),
        "nm": any(cfgsessions[s].get("nm") for s in selected),
        "plasma": any(cfgsessions[s].get("plasma") for s in selected),
        "nvwm": any(cfgsessions[s].get("nvwm") for s in selected),
        "vxwm": any(cfgsessions[s].get("vxwm") for s in selected),
        "newm": any(cfgsessions[s].get("newm") for s in selected),
        "mango": any(cfgsessions[s].get("mango") for s in selected),
        # Per-compositor flags for the default-config emission (keybinds +
        # launcher; see build_sessions_nix). lxqt runs on labwc too.
        "labwc": any(s in ("labwc", "labwc-noctalia", "lxqt") for s in selected),
        "sway": "sway" in selected,
        "niri": any(s in ("niri", "niri-noctalia") for s in selected),
        "noctalia": any(cfgsessions[s].get("noctalia") for s in selected),
        "noctalia_compositors": [
            cfgsessions[s]["noctalia"]
            for s in selected
            if cfgsessions[s].get("noctalia")
        ],
    }
    return selected, needs


def build_flake(needs):
    """Render the system flake for the selected sessions. Extra inputs
    (noctalia, nvwm sources) and the vendored plasma module are only wired
    in when the matching session was selected."""
    extra_inputs = ""
    if needs["noctalia"]:
        extra_inputs += (
            '    noctalia-src = {\n'
            '      url = "github:noctalia-dev/noctalia-shell/' + NOCTALIA_REV + '";\n'
            '      flake = false;\n'
            '    };\n'
        )
    if needs["nvwm"]:
        extra_inputs += (
            '    nvwm-src = {\n'
            '      url = "github:Vifuddyxg/nvwm/' + NVWM_REV + '";\n'
            '      flake = false;\n'
            '    };\n'
        )
    if needs["vxwm"]:
        extra_inputs += (
            '    vxwm-src = {\n'
            '      url = "git+https://codeberg.org/wh1tepearl/vxwm?rev=' + VXWM_REV + '";\n'
            '      flake = false;\n'
            '    };\n'
        )
    if needs["newm"]:
        extra_inputs += (
            '    # a flake with its OWN lock (no follows): newm only builds\n'
            '    # against the old nixpkgs its lockfile pins\n'
            '    newm-flake.url = "github:jbuchermn/newm/' + NEWM_REV + '";\n'
        )
    flake = cfgflaketemplate
    flake = flake.replace("@@nixpkgs_rev@@", NIXPKGS_REV)
    flake = flake.replace("@@finix_rev@@", FINIX_REV)
    flake = flake.replace("@@extra_inputs@@", extra_inputs)
    flake = flake.replace(
        "@@plasma_import@@", "\n        (./plasma.nix)" if needs["plasma"] else ""
    )
    return flake


# Finix branding module, always written to /etc/finix/branding.nix and
# imported by the flake. Currently: the limine boot menu group header.
# Finix's limine-install.py writes "/+NixOS default profile" as the menu
# group name; this rebuilds the install hook from the SAME pinned Finix
# source with that header substituted. The per-generation entries already
# read "finix (Linux ...)" from the Finix bootspec label.
BRANDING_NIX = """# Generated by the Finix installer: Finix branding fixes.
{
  config,
  pkgs,
  lib,
  inputs,
  ...
}:
let
  cfg = config.programs.limine;

  # Same JSON the upstream module builds (modules/programs/limine/
  # providers.bootloader.nix at the pinned finix revision).
  limineInstallConfig = pkgs.writeText "limine-install.json" (
    builtins.toJSON {
      inherit (cfg)
        additionalFiles
        biosDevice
        biosSupport
        efiSupport
        enrollConfig
        extraEntries
        force
        partitionIndex
        settings
        validateChecksums
        secureBoot
        ;

      nixPath = config.services.nix-daemon.package;
      efiBootMgrPath = pkgs.efibootmgr;
      liminePath = cfg.package;
      efiMountPoint = config.boot.loader.efi.efiSysMountPoint;
      fileSystems = config.fileSystems;
      canTouchEfiVariables = config.boot.loader.efi.canTouchEfiVariables;
      efiRemovable = cfg.efiInstallAsRemovable;
      maxGenerations = if cfg.maxGenerations == null then 0 else cfg.maxGenerations;
      hostArchitecture = pkgs.stdenv.hostPlatform.parsed.cpu;
      fwupdEfiPath = config.services.fwupd.package or null;
    }
  );

  # Upstream limine-install.py with the boot menu group renamed
  # "NixOS ..." -> "Finix ..." (keeps the @python3@/@configPath@
  # placeholders for replaceVarsWith below).
  patchedInstallScript =
    pkgs.runCommand "limine-install-finix.py" { } ''
      sed -e "s|/+NixOS {group_name}|/+Finix {group_name}|" \\
        ${inputs.finix}/modules/programs/limine/limine-install.py > $out
    '';
in
{
  config = lib.mkIf (config.providers.bootloader.backend or null == "limine") {
    providers.bootloader.installHook = lib.mkForce (
      pkgs.replaceVarsWith {
        src = patchedInstallScript;
        isExecutable = true;
        replacements = {
          python3 = pkgs.python3.withPackages (python-packages: [ python-packages.psutil ]);
          configPath = limineInstallConfig;
        };
      }
    );
  };
}
"""


# Vendored KDE Plasma 6 module (based on finix-community/finix branch
# `modules/plasma`, commit b7d1b1d, extended by this installer). Written to
# /etc/finix/plasma.nix and imported from the flake only when the plasma
# session is selected. Plasma has no upstream Finix module yet; this is the
# careful, self-contained version: Wayland session via kwin (which brings its
# own XWayland), audio started by the session script, plasma-nm/plasma-pa
# applets, and a beginner-friendly application set.
PLASMA_NIX = """# KDE Plasma 6 on Finix — generated by the Finix installer.
# Based on the WIP upstream module (finix branch modules/plasma), extended
# with audio startup, network/audio applets and default applications.
{
  config,
  pkgs,
  lib,
  ...
}:
let
  cfg = config.programs.plasma;

  inherit (pkgs) kdePackages;

  # Start the PipeWire audio stack inside the session (Finix has no systemd
  # user units), refresh the KService cache, then hand over to Plasma.
  # startplasma detects the missing systemd user manager and logs
  # "Using classic boot" (plasma_session) — the supported non-systemd path.
  # IMPORTANT: config.programs.*.package, not pkgs.* — under mdevd the
  # PipeWire packages are rebuilt against libudev-zero.
  sessionScript = pkgs.writeShellScript "plasma-session" ''
    ${config.programs.pipewire.package}/bin/pipewire &
    ${config.programs.wireplumber.package}/bin/wireplumber &
    ${config.programs.pipewire.package}/bin/pipewire-pulse &
    ${kdePackages.kservice}/bin/kbuildsycoca6 || true
    exec ${kdePackages.plasma-workspace}/bin/startplasma-wayland
  '';

  sessionFile = pkgs.writeTextDir "share/wayland-sessions/plasma.desktop" ''
    [Desktop Entry]
    Name=Plasma (Wayland)
    Comment=KDE Plasma Desktop
    Exec=${pkgs.dbus}/bin/dbus-run-session -- ${sessionScript}
    Type=Application
    DesktopNames=KDE
  '';
in
{
  options.programs.plasma = {
    enable = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = ''
        Whether to enable the KDE Plasma 6 Wayland session.
      '';
    };
  };

  config = lib.mkIf cfg.enable {
    # Battery / power management backend for powerdevil.
    services.upower.enable = true;

    environment.systemPackages = with kdePackages; [
      # session entry point
      (lib.hiPrio sessionFile)

      # Qt Wayland support
      qtwayland
      qtsvg
      qtimageformats

      # compositor + the Xwayland binary KWin lazy-spawns for X11 apps.
      # Without pkgs.xwayland any X11 client connecting to :0 hangs forever
      # (KWin accepts the connection, fails to start Xwayland, never answers):
      # xrdb from a phase-0 kcminit module then blocks the whole
      # plasma_session startup: a black screen with only a cursor.
      kwin
      pkgs.xwayland

      # core plasma (mirrors nixos/modules/services/desktop-managers/plasma6.nix
      # requiredPackages, minus systemd-only bits)
      plasma-workspace
      plasma-desktop
      kscreen
      libkscreen
      kscreenlocker
      kactivitymanagerd
      kglobalacceld
      kwrited
      baloo
      milou
      kmenuedit
      kinfocenter
      plasma-systemmonitor
      ksystemstats
      libksysguard
      systemsettings
      kcmutils
      kdeplasma-addons
      pkgs.xdg-user-dirs

      # KDE frameworks needed at runtime
      frameworkintegration
      kauth
      kcoreaddons
      kded
      kfilemetadata
      kguiaddons
      kiconthemes
      kimageformats
      kio
      kio-admin
      kio-extras
      kio-fuse
      knighttime
      kpackage
      kservice
      kunifiedpush
      solid
      plasma-activities
      phonon-vlc

      # QML / Qt plugins needed by plasmashell
      libplasma
      qqc2-desktop-style
      kde-cli-tools

      # theme
      breeze
      breeze-icons
      breeze-gtk
      kde-gtk-config
      ocean-sound-theme
      pkgs.hicolor-icon-theme
      qqc2-breeze-style

      # polkit agent
      polkit-kde-agent-1

      # platform integration
      plasma-integration

      drkonqi

      # audio + power applets (PipeWire and upower are enabled when this
      # session is selected; these are gated on NixOS-only options upstream
      # so they must be listed explicitly). NOTE: no plasma-nm — Finix
      # networking is dhcpcd + iwd (NetworkManager reads the udev database,
      # which mdevd does not provide);
      # Wi-Fi is managed with iwgtk (GUI) or iwctl.
      plasma-pa
      powerdevil
      pkgs.iwgtk

      # wallet (plasma-nm stores Wi-Fi passphrases here)
      kwallet
      kwalletmanager

      # beginner-friendly default applications
      dolphin
      konsole
      kate
      ark
      gwenview
      okular
      spectacle
      kdegraphics-thumbnailers
    ];

    environment.pathsToLink = [
      "/share"

      # for drkonqi
      "/libexec"
    ];

    security.pam.environment =
      let
        qtVersions = with pkgs; [
          qt5
          qt6
        ];
      in
      {
        QT_PLUGIN_PATH.default = map (qt: "/run/current-system/sw/${qt.qtbase.qtPluginPrefix}") qtVersions;
        QML2_IMPORT_PATH.default = map (qt: "/run/current-system/sw/${qt.qtbase.qtQmlPrefix}") qtVersions;

        XDG_CONFIG_DIRS.default = [ "@{HOME}/.config/kdedefaults" ];

        KPACKAGE_DEP_RESOLVERS_PATH.default = [
          "${kdePackages.frameworkintegration.out}/libexec/kf6/kpackagehandlers"
        ];
      };

    # kscreenlocker authenticates through the "kde" PAM service — without it
    # the lock screen can never verify the password (user locked out).
    security.pam.services.kde.text = ''
      auth      substack      login
      account   include       login
      password  substack      login
      session   include       login
    '';

    security.wrappers = {
      kwin_wayland = {
        owner = "root";
        group = "root";
        capabilities = "cap_sys_nice+ep";
        source = "${lib.getBin pkgs.kdePackages.kwin}/bin/kwin_wayland";
      };
    };

    xdg.portal.portals = [
      pkgs.kdePackages.xdg-desktop-portal-kde
      pkgs.xdg-desktop-portal-gtk
    ];
  };
}
"""


# --- sessions.nix generation -------------------------------------------------

_NOCTALIA_COMPOSITORS = {
    "labwc": {
        "name": "Labwc",
        "cmd": "${config.programs.labwc.package}/bin/labwc",
        "desktop_names": "labwc;wlroots",
        "comment": "labwc stacking compositor with the Noctalia desktop shell",
    },
    "niri": {
        "name": "Niri",
        "cmd": "${config.programs.niri.package}/bin/niri --session",
        "desktop_names": "niri",
        "comment": "Niri scrollable-tiling compositor with the Noctalia desktop shell",
    },
    "mango": {
        "name": "Mango",
        "cmd": "${config.programs.mango.package}/bin/mango",
        "desktop_names": "mango;wlroots",
        "comment": "Mango tiling compositor with the Noctalia desktop shell",
    },
}


def _noctalia_session_nix(comp):
    """One '<compositor> + Noctalia' launcher: start the compositor, wait for
    its Wayland socket, then start audio + Noctalia next to it. Generic on
    purpose — works the same for labwc, niri and mango, and never touches the
    compositor's own config files."""
    c = _NOCTALIA_COMPOSITORS[comp]
    # Noctalia's logout button talks to niri through its IPC socket, found
    # ONLY via $NIRI_SOCKET — and noctalia is started as the compositor's
    # sibling here, so it never inherits it. Export it explicitly (the
    # socket name embeds the compositor pid: niri.<display>.<pid>.sock).
    niri_socket = ""
    if comp == "niri":
        niri_socket = (
            '      i=0\n'
            '      while [ $i -lt 20 ]; do\n'
            '        for ns in "$XDG_RUNTIME_DIR"/niri.*.sock; do\n'
            '          if [ -S "$ns" ]; then export NIRI_SOCKET="$ns"; break 2; fi\n'
            '        done\n'
            '        i=$((i + 1))\n'
            '        sleep 0.1\n'
            '      done\n'
        )
    script = (
        '  session-' + comp + '-noctalia = pkgs.writeShellScript "session-' + comp + '-noctalia" \'\'\n'
        '    ' + c["cmd"] + ' &\n'
        '    comp=$!\n'
        '    sock=""\n'
        '    i=0\n'
        '    while [ $i -lt 100 ]; do\n'
        '      for s in "$XDG_RUNTIME_DIR"/wayland-*; do\n'
        '        case "$s" in\n'
        '          *.lock) ;;\n'
        '          *) if [ -S "$s" ]; then sock="$(basename "$s")"; break; fi ;;\n'
        '        esac\n'
        '      done\n'
        '      [ -n "$sock" ] && break\n'
        '      i=$((i + 1))\n'
        '      sleep 0.1\n'
        '    done\n'
        '    if [ -n "$sock" ]; then\n'
        '      export WAYLAND_DISPLAY="$sock"\n'
        '      # first XWayland display on a fresh boot\n'
        '      export DISPLAY=:0\n'
        + niri_socket +
        '      ${audioStart}\n'
        '      ${noctalia}/bin/noctalia --daemon &\n'
        '    fi\n'
        '    wait "$comp"\n'
        '  \'\';\n'
    )
    desktop = (
        '    (pkgs.writeTextDir "share/wayland-sessions/' + comp + '-noctalia.desktop" \'\'\n'
        '      [Desktop Entry]\n'
        '      Name=' + c["name"] + ' + Noctalia\n'
        '      Comment=' + c["comment"] + '\n'
        '      Exec=${pkgs.dbus}/bin/dbus-run-session -- ${session-' + comp + '-noctalia}\n'
        '      Type=Application\n'
        '      DesktopNames=' + c["desktop_names"] + '\n'
        '    \'\')\n'
    )
    return script, desktop


_NVWM_NIX_LET = """  # NVWM: vim-inspired tiling X11 window manager, built from the pinned
  # source input (C99, only Xlib deps — builds in seconds).
  nvwm = pkgs.stdenv.mkDerivation {
    pname = "nvwm";
    version = "0-unstable-pinned";
    src = inputs.nvwm-src;
    buildInputs = with pkgs; [
      libx11
      libxinerama
      libxrandr
      libxcomposite
      libxrender
    ];
    makeFlags = [
      "PREFIX=${placeholder "out"}"
      "SYSCONFDIR=${placeholder "out"}/etc"
    ];
  };

  session-nvwm = pkgs.writeShellScript "session-nvwm" ''
    ${audioStart}
    exec ${nvwm}/bin/nvwm
  '';
"""

_NVWM_NIX_DESKTOP = """    (pkgs.writeTextDir "share/xsessions/nvwm.desktop" ''
      [Desktop Entry]
      Name=NVWM
      Comment=Vim-inspired tiling X11 window manager
      # NO `--` here. X11 sessions are launched through tuigreet's
      # --xsession-wrapper (startx ...), and startx treats the FIRST `--`
      # as its own client/server separator: it took the session script as
      # the X server binary, so no X server ever started ("xinit: unable to
      # connect to X server: Connection refused"). dbus-run-session accepts
      # PROGRAM without the separator.
      Exec=${pkgs.dbus}/bin/dbus-run-session ${session-nvwm}
      Type=Application
      DesktopNames=nvwm
    '')
    # runtime tools nvwm's default config binds keys to
    pkgs.alacritty
    pkgs.rofi
    pkgs.maim
"""


# --- system-wide default configs for the wlroots compositors -------------
# The upstream defaults assume a package set this image does not have:
# labwc's built-in binds include no terminal or launcher, sway's bundled
# config calls wmenu and kitty, niri's calls fuzzel and alacritty. Each
# config
# below lives in /etc as the documented SYSTEM FALLBACK of that compositor,
# so a user config in ~/.config always wins and customization works the
# standard way. Common vocabulary: Super+Enter = foot, Super+D = rofi,
# Super+Q (or Shift+Q on sway) = close, Super+Shift+E = exit.

_LABWC_RC_XML = """<?xml version="1.0"?>
<!-- Finix default labwc config. Copy /etc/xdg/labwc/ to ~/.config/labwc/
     to customize; your copy takes precedence. <default /> keeps all of
     labwc's built-in key and mouse bindings (Alt-Tab, window menu, ...). -->
<labwc_config>
  <keyboard>
    <default />
    <keybind key="W-Return">
      <action name="Execute" command="foot" />
    </keybind>
    <keybind key="W-d">
      <action name="Execute" command="rofi -show drun" />
    </keybind>
    <keybind key="W-q">
      <action name="Close" />
    </keybind>
    <keybind key="W-S-e">
      <action name="Exit" />
    </keybind>
  </keyboard>
  <mouse>
    <default />
  </mouse>
</labwc_config>
"""

_LABWC_MENU_XML = """<?xml version="1.0" encoding="UTF-8"?>
<!-- Finix default labwc root menu (right-click on the desktop). -->
<openbox_menu>
  <menu id="root-menu" label="Finix">
    <item label="Terminal (foot)">
      <action name="Execute" command="foot" />
    </item>
    <item label="Applications (rofi)">
      <action name="Execute" command="rofi -show drun" />
    </item>
    <item label="Reconfigure">
      <action name="Reconfigure" />
    </item>
    <item label="Exit labwc">
      <action name="Exit" />
    </item>
  </menu>
</openbox_menu>
"""

_SWAY_CONFIG = """# Finix default sway config. Copy to ~/.config/sway/config to customize;
# your copy takes precedence over this system fallback.
set $mod Mod4
set $left h
set $down j
set $up k
set $right l
set $term foot
set $menu rofi -show drun

output * bg #1A1A1A solid_color
floating_modifier $mod normal

bindsym $mod+Return exec $term
bindsym $mod+d exec $menu
bindsym $mod+Shift+q kill
bindsym $mod+Shift+c reload
bindsym $mod+Shift+e exec swaynag -t warning -m 'Exit sway?' -B 'Yes, exit sway' 'swaymsg exit'

bindsym $mod+$left focus left
bindsym $mod+$down focus down
bindsym $mod+$up focus up
bindsym $mod+$right focus right
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right
bindsym $mod+Shift+$left move left
bindsym $mod+Shift+$down move down
bindsym $mod+Shift+$up move up
bindsym $mod+Shift+$right move right
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

bindsym $mod+1 workspace number 1
bindsym $mod+2 workspace number 2
bindsym $mod+3 workspace number 3
bindsym $mod+4 workspace number 4
bindsym $mod+5 workspace number 5
bindsym $mod+6 workspace number 6
bindsym $mod+7 workspace number 7
bindsym $mod+8 workspace number 8
bindsym $mod+9 workspace number 9
bindsym $mod+Shift+1 move container to workspace number 1
bindsym $mod+Shift+2 move container to workspace number 2
bindsym $mod+Shift+3 move container to workspace number 3
bindsym $mod+Shift+4 move container to workspace number 4
bindsym $mod+Shift+5 move container to workspace number 5
bindsym $mod+Shift+6 move container to workspace number 6
bindsym $mod+Shift+7 move container to workspace number 7
bindsym $mod+Shift+8 move container to workspace number 8
bindsym $mod+Shift+9 move container to workspace number 9

bindsym $mod+b splith
bindsym $mod+v splitv
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split
bindsym $mod+f fullscreen
bindsym $mod+Shift+space floating toggle
bindsym $mod+space focus mode_toggle

bar {
    position top
    status_command while date +'%Y-%m-%d %H:%M'; do sleep 60; done
}
"""

def _nix_etc_text(path, body):
    """environment.etc."<path>".text = ''<body>''; with proper indentation.
    The bodies contain no Nix-string specials ( '' or ${ )."""
    indented = "".join(
        ("      " + line if line.strip() else "") + "\n"
        for line in body.splitlines()
    )
    return (
        '  environment.etc."' + path + '".text = \'\'\n' + indented + "  \'\';\n"
    )


def build_sessions_nix(needs):
    """Render sessions.nix: session launcher scripts, packages and default
    compositor configs (keybinds + launcher) for the selected sessions.
    Always written (may be an empty module) so the flake can import it
    unconditionally."""
    let_parts = []
    pkg_parts = []
    etc_parts = []

    if needs["noctalia"] or needs["nvwm"] or needs["vxwm"] or needs["newm"]:
        let_parts.append(
            '  # start the PipeWire audio stack inside the user session (Finix ships\n'
            '  # no service for it). IMPORTANT: use config.programs.*.package, not\n'
            '  # pkgs.* — under mdevd the packages are rebuilt against libudev-zero.\n'
            '  audioStart = \'\'\n'
            '    ${config.programs.pipewire.package}/bin/pipewire &\n'
            '    ${config.programs.wireplumber.package}/bin/wireplumber &\n'
            '    ${config.programs.pipewire.package}/bin/pipewire-pulse &\n'
            '  \'\';\n'
        )

    if needs["noctalia"]:
        let_parts.append(
            '  # Noctalia v5 desktop shell, built from the pinned source against the\n'
            '  # same nixpkgs as the rest of the system\n'
            '  noctalia = pkgs.callPackage (inputs.noctalia-src + "/nix/package.nix") { };\n'
        )
        for comp in needs["noctalia_compositors"]:
            script, desktop = _noctalia_session_nix(comp)
            let_parts.append(script)
            pkg_parts.append(desktop)

    if needs["nvwm"]:
        let_parts.append(_NVWM_NIX_LET)
        pkg_parts.append(_NVWM_NIX_DESKTOP)
        pkg_parts.append("    nvwm\n")
        etc_parts.append(
            '  environment.etc."nvwm/config.conf".source = "${nvwm}/etc/nvwm/config.conf";\n'
        )

    if needs["mango"]:
        # mango errors on a missing /etc/mango/config.conf (its compiled-in
        # SYSCONFDIR is /etc but the Nix package installs the default config
        # into $out); ship the upstream default so the session works and the
        # user has a documented starting point to copy to ~/.config/mango/.
        # (its default binds use foot + rofi — both installed below/in base)
        etc_parts.append(
            '  # default MangoWC config (copy to ~/.config/mango/config.conf to customize)\n'
            '  environment.etc."mango/config.conf".source =\n'
            '    config.programs.mango.package.src + "/assets/config.conf";\n'
        )

    # --- default keybind configs so every session works out of the box ---
    if needs["labwc"]:
        etc_parts.append(
            "  # labwc reads $XDG_CONFIG_DIRS/labwc/ when ~/.config/labwc/ is absent\n"
        )
        etc_parts.append(_nix_etc_text("xdg/labwc/rc.xml", _LABWC_RC_XML))
        etc_parts.append(_nix_etc_text("xdg/labwc/menu.xml", _LABWC_MENU_XML))

    if needs["sway"]:
        etc_parts.append(
            "  # sway probes $XDG_CONFIG_DIRS/sway/config and /etc/sway/config as\n"
            "  # system fallbacks; ship the same file at both lookup paths\n"
        )
        etc_parts.append(_nix_etc_text("sway/config", _SWAY_CONFIG))
        etc_parts.append(_nix_etc_text("xdg/sway/config", _SWAY_CONFIG))

    if needs["vxwm"]:
        let_parts.append(
            "  # vxwm: versatile dwm-style X11 WM, built from the pinned Codeberg\n"
            "  # source (C + Xlib/Xft/Xinerama; dwm-style compiled-in config —\n"
            "  # customize by editing config.def.h in an overridden build).\n"
            "  vxwm = pkgs.stdenv.mkDerivation {\n"
            '    pname = "vxwm";\n'
            '    version = "2.3-pinned";\n'
            "    src = inputs.vxwm-src;\n"
            "    buildInputs = with pkgs; [\n"
            "      libx11\n"
            "      libxft\n"
            "      libxinerama\n"
            "      fontconfig\n"
            "      freetype\n"
            "    ];\n"
            "    makeFlags = [\n"
            '      "PREFIX=${placeholder "out"}"\n'
            '      "X11INC=${pkgs.libx11.dev}/include"\n'
            '      "X11LIB=${pkgs.libx11}/lib"\n'
            '      "FREETYPEINC=${pkgs.freetype.dev}/include/freetype2"\n'
            "    ];\n"
            "  };\n"
            "\n"
            '  session-vxwm = pkgs.writeShellScript "session-vxwm" \'\'\n'
            "    ${audioStart}\n"
            "    exec ${vxwm}/bin/vxwm\n"
            "  \'\';\n"
        )
        pkg_parts.append(
            "    vxwm\n"
            '    (pkgs.writeTextDir "share/xsessions/vxwm.desktop" \'\'\n'
            "      [Desktop Entry]\n"
            "      Name=vxwm\n"
            "      Comment=Versatile dwm-style X11 tiling window manager\n"
            "      # no `--`: startx (the xsession wrapper) would read it as\n"
            "      # its client/server separator — see the nvwm entry\n"
            "      Exec=${pkgs.dbus}/bin/dbus-run-session ${session-vxwm}\n"
            "      Type=Application\n"
            "      DesktopNames=vxwm\n"
            "    \'\')\n"
            "    # runtime tools vxwm's default (dwm-style) binds call:\n"
            "    # Super+Shift+Return = st, Super+P = dmenu_run\n"
            "    pkgs.st\n"
            "    pkgs.dmenu\n"
        )

    if needs["newm"]:
        let_parts.append(
            "  # newm: touchpad-centric Wayland compositor (pywm). Comes from its\n"
            "  # own flake with its own OLD locked nixpkgs (the only combination\n"
            "  # it builds with); config: ~/.config/newm/config.py.\n"
            '  session-newm = pkgs.writeShellScript "session-newm" \'\'\n'
            "    ${audioStart}\n"
            '    exec ${inputs.newm-flake.packages.x86_64-linux.newm}/bin/start-newm\n'
            "  \'\';\n"
        )
        pkg_parts.append(
            "    inputs.newm-flake.packages.x86_64-linux.newm\n"
            '    (pkgs.writeTextDir "share/wayland-sessions/newm.desktop" \'\'\n'
            "      [Desktop Entry]\n"
            "      Name=newm\n"
            "      Comment=Touchpad-centric Wayland compositor\n"
            "      Exec=${pkgs.dbus}/bin/dbus-run-session -- ${session-newm}\n"
            "      Type=Application\n"
            "      DesktopNames=newm\n"
            "    \'\')\n"
        )
    if needs["nvwm"] or needs["vxwm"]:
        # Finix links /share/wayland-sessions into the system path by default,
        # but NOT /share/xsessions — without this the greeter would not see
        # the X11 sessions. Emitted once (a duplicate attribute in the same
        # module would be an eval error).
        etc_parts.append(
            '  environment.pathsToLink = [ "/share/xsessions" ];\n'
        )
        # Finix's xorg module ships a setuid X wrapper and disables it when
        # elogind is present, since logind can hand X the VT. That path needs
        # an xorg-server built with libsystemd, which this one is not, so X
        # fails with "parse_vt_settings: Cannot open /dev/tty0 (Permission
        # denied)". Force the wrapper on — /run/wrappers/bin comes first in
        # PATH, so startx and xinit resolve X to it.
        etc_parts.append(
            "  security.wrappers.X.enable = lib.mkForce true;\n"
        )

    if needs["niri"]:
        pkg_parts.append(
            "    # niri's excellent built-in defaults (Mod+Shift+/ shows them all)\n"
            "    # spawn alacritty (Mod+T) and fuzzel (Mod+D) — install both so the\n"
            "    # defaults work; ~/.config/niri/config.kdl customizes as usual\n"
            "    pkgs.alacritty\n"
            "    pkgs.fuzzel\n"
        )

    if needs["labwc"] or needs["sway"] or needs["mango"]:
        pkg_parts.append(
            "    # the launcher every default config above binds to Super+D\n"
            "    pkgs.rofi\n"
        )

    # Seed every human user's ~/.config with editable copies of the system
    # default configs, so customizing means "edit the file", not "find and
    # copy it first" (the /etc originals are read-only store symlinks that
    # every finix-rebuild regenerates).
    # This runs as an ACTIVATION script, not from the installer: on finix
    # home directories are created by finit's tmpfiles at BOOT, so at
    # nixos-install time there is no home to seed yet. Activation also
    # re-runs on every rebuild, which covers users added later.
    # Idempotent: an existing destination is never touched, so user edits
    # (and deliberate deletions of a whole config dir) survive.
    seed_pairs = []
    if needs["labwc"]:
        seed_pairs.append(("/etc/xdg/labwc", ".config/labwc"))
    if needs["sway"]:
        seed_pairs.append(("/etc/sway/config", ".config/sway/config"))
    if needs["mango"]:
        seed_pairs.append(("/etc/mango/config.conf", ".config/mango/config.conf"))
    if needs["nvwm"]:
        # nvwm loads /etc/nvwm/config.conf first and ~/.config/nvwm/config.conf
        # last, so the seeded copy wins (verified in nvwm.c loadcfg()).
        seed_pairs.append(("/etc/nvwm/config.conf", ".config/nvwm/config.conf"))
    # vxwm is not seeded on purpose: it is dwm-style, its configuration is
    # compiled in (config.def.h) and it reads no runtime config file.
    if seed_pairs:
        seeds = "".join(
            '      seed "{}" "$h/{}"\n'.format(src, dst) for src, dst in seed_pairs
        )
        let_parts.append(
            '  seed-user-configs = pkgs.writeShellScript "seed-user-configs" \'\'\n'
            "    export PATH=${pkgs.coreutils}/bin:$PATH\n"
            "    seed() {\n"
            '      [ -e "$1" ] || return 0\n'
            '      [ -e "$2" ] && return 0\n'
            '      mkdir -p "$(dirname "$2")"\n'
            "      # -L: resolve the /etc/static -> store symlinks into real,\n"
            "      # writable files; chmod: store files are read-only\n"
            '      cp -rL "$1" "$2" || return 0\n'
            '      chmod -R u+w "$2"\n'
            "    }\n"
            "    while IFS=: read -r user _ uid gid _ home _; do\n"
            '      [ "$uid" -ge 1000 ] && [ "$uid" -lt 65000 ] || continue\n'
            '      [ -d "$home" ] || continue\n'
            '      h="$home"\n'
            + seeds +
            '      chown -R "$uid:$gid" "$h/.config" 2>/dev/null || true\n'
            "    done < /etc/passwd\n"
            "  \'\';\n"
        )
        etc_parts.append(
            "  system.activation.scripts.seed-user-configs = {\n"
            '    deps = [ "users" ];\n'
            "    text = \"${seed-user-configs}\";\n"
            "  };\n"
        )

    # --- power buttons (Noctalia, terminal `poweroff`) on the seatd flavor ---
    # Without elogind there is no login1: `poweroff`/`reboot` in PATH are
    # finit's initctl and need root. Desktop shells launch them detached and
    # believe they worked while the machine stays on. Shim them through
    # passwordless sudo (wheel group); `zzz` covers suspend the same way.
    # (The elogind flavor needs none of this: a polkit rule in
    # configuration.nix makes `loginctl poweroff` — the variant desktop
    # shells reach first — work for wheel users.)
    if not needs["elogind"] and not needs["console_only"]:
        pkg_parts.append(
            '    (lib.setPrio (-15) (pkgs.writeShellScriptBin "poweroff" \'\'\n'
            '      [ "$(id -u)" = 0 ] && exec ${config.finit.package}/bin/initctl poweroff\n'
            "      exec sudo -n ${config.finit.package}/bin/initctl poweroff\n"
            "    \'\'))\n"
            '    (lib.setPrio (-15) (pkgs.writeShellScriptBin "reboot" \'\'\n'
            '      [ "$(id -u)" = 0 ] && exec ${config.finit.package}/bin/initctl reboot\n'
            "      exec sudo -n ${config.finit.package}/bin/initctl reboot\n"
            "    \'\'))\n"
            '    (pkgs.writeShellScriptBin "zzz" \'\'\n'
            '      [ "$(id -u)" = 0 ] && exec ${pkgs.writeShellScript "finix-suspend" "echo mem > /sys/power/state"}\n'
            '      exec sudo -n ${pkgs.writeShellScript "finix-suspend" "echo mem > /sys/power/state"}\n'
            "    \'\')\n"
        )
        etc_parts.append(
            "  # exact commands only, wheel group, no password (see shims above)\n"
            "  environment.etc.sudoers.text = lib.mkOrder 2000 ''\n"
            '    %wheel ALL=(root) NOPASSWD: ${config.finit.package}/bin/initctl poweroff, ${config.finit.package}/bin/initctl reboot, ${pkgs.writeShellScript "finix-suspend" "echo mem > /sys/power/state"}\n'
            "  '';\n"
        )

    if not let_parts and not etc_parts and not pkg_parts:
        return (
            "# Generated by the Finix installer. No extra session glue needed for\n"
            "# the selected sessions.\n"
            "{ ... }:\n\n{ }\n"
        )
    if not let_parts:
        out = (
            "# Generated by the Finix installer: session glue for the selected\n"
            "# desktop sessions.\n"
            "{ config, pkgs, lib, ... }:\n\n{\n"
        )
        if pkg_parts:
            out += "  environment.systemPackages = [\n" + "".join(pkg_parts) + "  ];\n"
        out += "".join(etc_parts) + "}\n"
        return out

    out = (
        "# Generated by the Finix installer: session launchers and packages for\n"
        "# the selected desktop sessions (Noctalia shell variants, NVWM).\n"
        "{\n  config,\n  pkgs,\n  lib,\n  inputs,\n  ...\n}:\nlet\n"
        + "\n".join(let_parts)
        + "in\n{\n"
    )
    if pkg_parts:
        out += "  environment.systemPackages = [\n" + "".join(pkg_parts) + "  ];\n"
    out += "".join(etc_parts)
    out += "}\n"
    return out
def env_is_set(name):
    envValue = os.environ.get(name)
    return not (envValue is None or envValue == "")

def generateProxyStrings():
    proxyEnv = []
    if env_is_set('http_proxy'):
        proxyEnv.append('http_proxy={}'.format(os.environ.get('http_proxy')))
    if env_is_set('https_proxy'):
        proxyEnv.append('https_proxy={}'.format(os.environ.get('https_proxy')))
    if env_is_set('HTTP_PROXY'):
        proxyEnv.append('HTTP_PROXY={}'.format(os.environ.get('HTTP_PROXY')))
    if env_is_set('HTTPS_PROXY'):
        proxyEnv.append('HTTPS_PROXY={}'.format(os.environ.get('HTTPS_PROXY')))

    if len(proxyEnv) > 0:
        proxyEnv.insert(0, "env")

    return proxyEnv

def pretty_name():
    return _("Installing Finix.")


status = pretty_name()


def pretty_status_message():
    return status


def catenate(d, key, *values):
    """
    Sets @p d[key] to the string-concatenation of @p values
    if none of the values are None.
    This can be used to set keys conditionally based on
    the values being found.
    """
    if [v for v in values if v is None]:
        return

    d[key] = "".join(values)


def fix_btrfs_subvolumes(hardware_config, partitions):
    """
    Fix btrfs subvolume configuration in hardware-configuration.nix.

    nixos-generate-config generates incorrect subvol options for btrfs
    by setting them to mount points instead of actual subvolume names.
    This function corrects the subvol options to match what Calamares configured.
    """
    # Map of mount points to their correct btrfs subvolume names
    # These match what is configured in mount.conf btrfsSubvolumes
    # Root uses top-level (no subvolume) for GRUB compatibility
    subvol_map = {
        "/home": "home",
        "/nix": "nix",
    }

    # Check if root is actually btrfs
    root_is_btrfs = False
    for part in partitions:
        if part.get("mountPoint") == "/" and part.get("fs") == "btrfs":
            root_is_btrfs = True
            break

    if not root_is_btrfs:
        return hardware_config

    libcalamares.utils.debug("Fixing btrfs subvolume configuration")

    # Fix subvol options for each mount point
    # nixos-generate-config may generate "subvol=/" instead of "subvol=@"
    for mount_point, correct_subvol in subvol_map.items():
        # Match any "subvol=<something>" and replace with correct subvolume
        # This handles cases like "subvol=/" or "subvol=/home"
        pattern = r'(fileSystems\."{}"[^;]*"subvol=)[^"]*"'.format(re.escape(mount_point))
        replacement = r'\g<1>{}"'.format(correct_subvol)
        hardware_config = re.sub(pattern, replacement, hardware_config, flags=re.DOTALL)

    return hardware_config


_FINIX_HW_KEEP_PREFIXES = (
    "boot.initrd.availableKernelModules",
    "boot.initrd.kernelModules",
    "boot.kernelModules",
    "boot.extraModulePackages",
    "fileSystems.",
    "fileSystems",
    "swapDevices",
)


def _finix_split_top_level(body):
    """Split a Nix attrset body into top-level statements (terminated by ';'
    at bracket depth 0). Tracks (){}[] depth and skips '#' line comments so
    that ';' inside nested blocks or comments does not split a statement."""
    stmts = []
    buf = []
    depth = 0
    in_comment = False
    for c in body:
        if in_comment:
            buf.append(c)
            if c == "\n":
                in_comment = False
            continue
        if c == "#":
            in_comment = True
            buf.append(c)
            continue
        if c in "[{(":
            depth += 1
        elif c in "]})":
            depth -= 1
        buf.append(c)
        if c == ";" and depth == 0:
            stmts.append("".join(buf))
            buf = []
    tail = "".join(buf)
    return stmts, tail


def _finix_stmt_key(stmt):
    """Return the bare left-hand-side attribute path of a Nix statement,
    with leading comments/whitespace stripped (e.g. 'boot.kernelModules')."""
    lhs = stmt.split("=", 1)[0]
    lhs = "\n".join(line.split("#", 1)[0] for line in lhs.splitlines())
    return lhs.strip()


def finixify_hardware_config(hardware_config):
    """
    Strip NixOS-only options from nixos-generate-config output so the generated
    hardware-configuration.nix evaluates against Finix's (much smaller) module
    set. Finix does not define hardware.enableRedistributableFirmware (pulled in
    via the not-detected.nix import), hardware.cpu.*.updateMicrocode,
    networking.useDHCP, nixpkgs.hostPlatform, powerManagement.*, etc. Per the
    upstream Finix install docs, the file must be reduced to boot.initrd.*,
    boot.kernelModules, boot.extraModulePackages, fileSystems.*, swapDevices,
    plus an explicit hardware.firmware = [ pkgs.linux-firmware ] for wireless/GPU
    firmware. Uses a keep-list so any future NixOS-only addition is dropped too.
    """
    # Split off the function-argument header: the ':' after the first balanced
    # { ... } (the argument attrset).
    first_open = hardware_config.find("{")
    if first_open == -1:
        return hardware_config
    depth = 0
    i = first_open
    while i < len(hardware_config):
        ch = hardware_config[i]
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                break
        i += 1
    colon = hardware_config.find(":", i)
    if colon == -1:
        return hardware_config
    header = hardware_config[: colon + 1]

    # Locate the body attrset that follows the header.
    rest = hardware_config[colon + 1 :]
    body_open = rest.find("{")
    if body_open == -1:
        return hardware_config
    depth = 0
    j = body_open
    while j < len(rest):
        ch = rest[j]
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                break
        j += 1
    body = rest[body_open + 1 : j]

    stmts, _tail = _finix_split_top_level(body)
    kept = []
    for stmt in stmts:
        key = _finix_stmt_key(stmt)
        if any(key == p or key.startswith(p) for p in _FINIX_HW_KEEP_PREFIXES):
            kept.append(stmt)

    new_body = "".join(kept).rstrip()
    return (
        header
        + "\n\n{\n"
        + new_body
        # linux-firmware = wifi/bt/gpu blobs; sof-firmware = audio DSP on
        # modern (2019+) Intel laptops — on NixOS both come via
        # hardware.enableRedistributableFirmware, which finix doesn't have.
        + "\n\n  hardware.firmware = [\n    pkgs.linux-firmware\n    pkgs.sof-firmware\n  ];\n}\n"
    )


# The by-uuid paths emitted by nixos-generate-config are kept as-is, which is
# independent of device enumeration order (it can differ between the live ISO
# and the installed kernel on machines with several disks). This relies on the
# pinned Finix revision's mdevd module, which ships mdevd-disk.sh (blkid-driven)
# in both the system and the initrd to create /dev/disk/by-uuid at coldplug,
# with the initrd's wait-dev task polling the path for up to 90s. See finix
# issue #67 for the history.


# nix internal-json activity/result types
_ACT_COPY_PATH = 100
_ACT_COPY_PATHS = 103
_ACT_BUILDS = 104
_RES_PROGRESS = 105


class NixProgress:
    """Parse nix internal-json output and track build/copy progress."""

    def __init__(self):
        self._builds_done = 0
        self._builds_expected = 0
        self._copies_done = 0
        self._copies_expected = 0
        self._per_act_progress = {}
        self._copy_bytes = {}
        self._activities = {}
        self.fraction = 0.0
        self._floor = 0.0
        self._floor_done = 0
        self.log_messages = []

    def handle(self, line):
        """Process one line. Returns True for @nix lines, False for plain text."""
        line = line.strip()
        if not line:
            return True
        if not line.startswith("@nix "):
            return False
        try:
            msg = json.loads(line[5:])
        except (json.JSONDecodeError, ValueError):
            return False

        action = msg.get("action")
        if action == "start":
            self._on_start(msg)
        elif action == "stop":
            self._on_stop(msg)
        elif action == "result":
            self._on_result(msg)
        elif action == "msg":
            level = msg.get("level", 0)
            text = msg.get("msg", "")
            if level <= 1 and text:
                self.log_messages.append(text)

        self._update()
        return True

    def _on_start(self, msg):
        act_id = msg["id"]
        act_type = msg.get("type", 0)
        self._activities[act_id] = act_type
        text = msg.get("text", "")
        if text and msg.get("level", 5) <= 3:
            self.log_messages.append(text)

    def _on_stop(self, msg):
        act_id = msg["id"]
        self._activities.pop(act_id, None)
        self._copy_bytes.pop(act_id, None)

    def _on_result(self, msg):
        act_id = msg["id"]
        res_type = msg.get("type", 0)
        fields = msg.get("fields", [])
        act_type = self._activities.get(act_id, 0)

        if res_type != _RES_PROGRESS or len(fields) < 2:
            return
        if act_type == _ACT_BUILDS:
            self._per_act_progress[(act_type, act_id)] = (
                "builds",
                fields[0],
                fields[1],
            )
            self._recompute_counts()
        elif act_type == _ACT_COPY_PATHS:
            self._per_act_progress[(act_type, act_id)] = (
                "copies",
                fields[0],
                fields[1],
            )
            self._recompute_counts()
        elif act_type == _ACT_COPY_PATH:
            self._copy_bytes[act_id] = (fields[0], max(fields[1], 1))

    def _update(self):
        count_total = self._builds_expected + self._copies_expected
        count_done = self._builds_done + self._copies_done
        if count_total <= 0:
            return

        # Prevents the channel copy (1 path) from dominating the
        # entire progress bar before the main build starts.
        effective_total = max(count_total, 3)
        count_frac = count_done / effective_total

        # large single-path copies move the bar.
        total_bytes = sum(t for _, t in self._copy_bytes.values())
        done_bytes = sum(d for d, _ in self._copy_bytes.values())
        if total_bytes > 0:
            byte_sub = done_bytes / total_bytes
            step = len(self._copy_bytes) / effective_total
            raw = count_frac + byte_sub * step
        else:
            raw = count_frac
        raw = max(0.0, min(1.0, raw))

        # When the denominator grows (e.g. main build discovers hundreds
        # of new paths), remap remaining work into remaining bar space.
        if raw >= self._floor:
            self._floor = raw
            self._floor_done = count_done
        else:
            new_items = count_done - self._floor_done
            remaining = effective_total - self._floor_done
            if remaining > 0 and new_items >= 0:
                raw = self._floor + (new_items / remaining) * (1.0 - self._floor)
            else:
                raw = self._floor
            raw = max(0.0, min(1.0, raw))
            if raw > self._floor:
                self._floor = raw
                self._floor_done = count_done

        self.fraction = raw

    def _recompute_counts(self):
        bd = be = cd = ce = 0
        for kind, done, expected in self._per_act_progress.values():
            if kind == "builds":
                bd += done
                be += expected
            else:
                cd += done
                ce += expected
        self._builds_done = bd
        self._builds_expected = be
        self._copies_done = cd
        self._copies_expected = ce


def run():
    """Finix Configuration."""

    INSTALL_PROGRESS_START = 0.1
    INSTALL_PROGRESS_END = 1.0

    global status
    status = _("Configuring Finix")
    libcalamares.job.setprogress(0.01)

    ngc_cfg = configparser.ConfigParser()
    ngc_cfg["Defaults"] = { "Kernel": "lts" }
    ngc_cfg.read("/etc/nixos-generate-config.conf")

    # Create initial config file
    cfg = cfghead
    gs = libcalamares.globalstorage
    variables = dict()

    # Setup variables
    root_mount_point = gs.value("rootMountPoint")
    # Finix keeps its system flake in /etc/finix (not /etc/nixos).
    config = os.path.join(root_mount_point, "etc/finix/configuration.nix")
    fw_type = gs.value("firmwareType")
    bootdev = (
        "nodev"
        if gs.value("bootLoader") is None
        else gs.value("bootLoader")["installPath"]
    )

    # Pick config parts and prepare substitution

    # Check if root filesystem is btrfs
    root_is_btrfs = False
    for part in gs.value("partitions"):
        if part.get("mountPoint") == "/" and part.get("fs") == "btrfs":
            root_is_btrfs = True
            break

    # Check bootloader
    if fw_type == "efi":
        cfg += cfgbootefi
    elif bootdev != "nodev":
        # Use btrfs-specific config to avoid blkid issues with subvolumes
        if root_is_btrfs:
            cfg += cfgbootbiosbtrfs
        else:
            cfg += cfgbootbios
        catenate(variables, "bootdev", bootdev)
    else:
        cfg += cfgbootnone

    if ngc_cfg["Defaults"]["Kernel"] == "latest":
        cfg += cfglatestkernel

    # Finix has no boot.initrd.luks.devices option (its LUKS support is the
    # separate boot.initrd.supportedFilesystems.luks mechanism, untested with
    # this installer). Emitting the NixOS option would abort the install with
    # "option does not exist", so LUKS setups are not emitted; warn instead.
    for part in gs.value("partitions"):
        if (
            part["claimed"] is True
            and (part["fsName"] == "luks" or part["fsName"] == "luks2")
        ):
            libcalamares.utils.warning(
                "LUKS partition {} detected: encrypted installs are not "
                "supported by the Finix installer yet; skipping initrd LUKS "
                "config for it".format(part.get("device"))
            )

    # Check partitions
    root_is_encrypted = False
    boot_is_encrypted = False
    boot_is_partition = False

    for part in gs.value("partitions"):
        if part["mountPoint"] == "/":
            root_is_encrypted = part["fsName"] in ["luks", "luks2"]
        elif part["mountPoint"] == "/boot":
            boot_is_partition = True
            boot_is_encrypted = part["fsName"] in ["luks", "luks2"]

    # The BIOS/GRUB crypto_keyfile flow was removed: it emitted
    # boot.initrd.luks.devices.*.keyFile, which does not exist on Finix
    # (see the LUKS warning above; Finix is UEFI/limine anyway).

    status = _("Configuring Finix")
    libcalamares.job.setprogress(0.03)

    # Desktop / compositor selection (multi-select packagechooser: the value
    # is a comma-separated list of ids).
    selected, needs = parse_desktop_selection(
        gs.value("packagechooser_packagechooser") or "",
        warn=libcalamares.utils.warning,
    )

    # Cap per-build compiler parallelism by available RAM. Each C++/Rust
    # compile job peaks around 1.5-2 GB; on an 8 GB machine 8 parallel jobs
    # inside one derivation can freeze the system even with --max-jobs 1.
    # Used for the install itself AND written into the installed system's
    # config so post-update rebuilds stay safe on the same hardware.
    build_cores = 0  # 0 = nix default (all cores)
    try:
        mem_gb = 0
        with open("/proc/meminfo") as f:
            for line in f:
                if line.startswith("MemTotal:"):
                    mem_gb = int(line.split()[1]) // (1024 * 1024)
                    break
        cpus = os.cpu_count() or 4
        if mem_gb and mem_gb < 20:
            # ~1 compile job per 2 GB of RAM (8 GB -> 4 jobs). Safe now that
            # builds are serialized, scratch lives on the target disk and the
            # target's swap is enabled during the install.
            build_cores = max(1, min(cpus, mem_gb // 2))
    except Exception as e:
        libcalamares.utils.debug("could not size build cores: {}".format(e))

    if build_cores:
        cfg += cfgnixlowram
        catenate(variables, "buildcores", str(build_cores))

    # seat management + device manager: eudev + elogind when Plasma is
    # selected (KWin has no seatd backend, and elogind's TakeDevice needs
    # the udev database), otherwise the Finix default mdevd + seatd.
    # Never both.
    cfg += cfgelogind if needs["elogind"] else cfgseatd

    # networking: dhcpcd + iwd for every selection (NetworkManager is broken
    # under mdevd — no udev database, all devices "unmanaged").
    cfg += cfgnetfinix
    cfg += cfgnetwork

    # Hostname: apply what the user typed on the users page; default "finix"
    # (never "nixos" — the installed system is Finix).
    if gs.value("hostname"):
        catenate(variables, "hostname", gs.value("hostname"))
    else:
        catenate(variables, "hostname", "finix")

    if gs.value("locationRegion") is not None and gs.value("locationZone") is not None:
        cfg += cfgtime
        catenate(
            variables,
            "timezone",
            gs.value("locationRegion"),
            "/",
            gs.value("locationZone"),
        )

    if gs.value("localeConf") is not None:
        localeconf = gs.value("localeConf")
        locale = localeconf.pop("LANG").split("/")[0]
        cfg += cfglocale
        catenate(variables, "LANG", locale)
        if (
            len(set(localeconf.values())) != 1
            or list(set(localeconf.values()))[0] != locale
        ):
            cfg += cfglocaleextra
            for conf in localeconf:
                catenate(variables, conf, localeconf.get(conf).split("/")[0])

    # Login greeter: greetd/tuigreet for every graphical selection (with the
    # xsessions list added when an X11 session — nvwm — is installed);
    # nothing at all for a console-only (minimal) install.
    if needs["console_only"]:
        cfg += cfggreetnone
    elif needs["nvwm"] or needs["vxwm"]:
        cfg += cfggreettuix11
    else:
        cfg += cfggreettui

    # Audio stack (PipeWire), needed by Noctalia / Plasma / NVWM selections.
    if needs["audio"]:
        cfg += cfgaudio

    # Desktop / compositor: emit each selected session's options, deduplicated
    # (e.g. labwc + labwc-noctalia both enable programs.labwc — Nix forbids
    # defining the same attribute twice in one attrset).
    session_opts = []
    for s in selected:
        cfg += "  # --- {} ---\n".format(cfgsessions[s]["comment"])
        for opt in cfgsessions[s]["opts"]:
            if opt not in session_opts:
                session_opts.append(opt)
                cfg += "  {} = true;\n".format(opt)
        cfg += "\n"

    if (
        gs.value("keyboardLayout") is not None
        and gs.value("keyboardVariant") is not None
    ):
        cfg += cfgkeymap
        catenate(variables, "kblayout", gs.value("keyboardLayout"))
        catenate(variables, "kbvariant", gs.value("keyboardVariant"))

        if gs.value("keyboardVConsoleKeymap") is not None:
            try:
                subprocess.check_output(
                    ["pkexec", "loadkeys", gs.value("keyboardVConsoleKeymap").strip()],
                    stderr=subprocess.STDOUT,
                )
                cfg += cfgconsole
                catenate(
                    variables, "vconsole", gs.value("keyboardVConsoleKeymap").strip()
                )
            except subprocess.CalledProcessError as e:
                libcalamares.utils.error("loadkeys: {}".format(e.output))
                libcalamares.utils.error(
                    "Setting vconsole keymap to {} will fail, using default".format(
                        gs.value("keyboardVConsoleKeymap").strip()
                    )
                )
        else:
            kbdmodelmap = open(
                "/run/current-system/sw/share/systemd/kbd-model-map", "r"
            )
            kbd = kbdmodelmap.readlines()
            out = []
            for line in kbd:
                if line.startswith("#"):
                    continue
                out.append(line.split())
            # Find rows with same layout
            find = []
            for row in out:
                if gs.value("keyboardLayout") == row[1]:
                    find.append(row)
            if find != []:
                vconsole = find[0][0]
            else:
                vconsole = ""
            if gs.value("keyboardVariant") is not None:
                variant = gs.value("keyboardVariant")
            else:
                variant = "-"
            # Find rows with same variant
            for row in find:
                if variant in row[3]:
                    vconsole = row[0]
                    break
                # If none found set to "us"
            if vconsole != "" and vconsole != "us" and vconsole is not None:
                try:
                    subprocess.check_output(
                        ["pkexec", "loadkeys", vconsole], stderr=subprocess.STDOUT
                    )
                    cfg += cfgconsole
                    catenate(variables, "vconsole", vconsole)
                except subprocess.CalledProcessError as e:
                    libcalamares.utils.error("loadkeys: {}".format(e.output))
                    libcalamares.utils.error("vconsole value: {}".format(vconsole))
                    libcalamares.utils.error(
                        "Setting vconsole keymap to {} will fail, using default".format(
                            gs.value("keyboardVConsoleKeymap")
                        )
                    )

    if (
        gs.value("packagechooser_packagechooser") is not None
        and gs.value("packagechooser_packagechooser") != ""
    ):
        cfg += cfgmisc

    if gs.value("username") is not None:
        fullname = gs.value("fullname")
        # Finix-safe groups: 'wheel' = sudo, 'video' = GPU access, plus the
        # seatd group for the Wayland seat. 'audio' / 'networkmanager' only
        # when the matching stack is enabled (their groups exist only then).
        groups = ["wheel", "video"]
        if needs["audio"]:
            groups.append("audio")
        if needs["nm"]:
            groups.append("networkmanager")

        cfg += cfgusers
        catenate(variables, "username", gs.value("username"))
        catenate(variables, "fullname", fullname)
        # The seatd group only exists when seatd is the seat manager; under
        # elogind (Plasma) device access comes from logind ACLs instead.
        groups_nix = (" ").join(['"' + s + '"' for s in groups])
        if not needs["elogind"]:
            groups_nix += " config.services.seatd.group"
        catenate(variables, "groups", groups_nix)
        if (
            gs.value("autoLoginUser") is not None
            and gs.value("packagechooser_packagechooser") is not None
            and gs.value("packagechooser_packagechooser") != ""
        ):
            cfg += cfgautologin
            if gs.value("packagechooser_packagechooser") == "gnome":
                cfg += cfgautologingdm
        elif gs.value("autoLoginUser") is not None:
            cfg += cfgautologintty

    # Check if unfree packages are allowed
    free = True
    if gs.value("nixos_allow_unfree"):
        free = False
        cfg += cfgunfree

    cfg += cfgpkgs
    catenate(variables, "pkgs", "")

    cfg += cfgtail

    # Check that all variables are used
    for key in variables.keys():
        pattern = "@@{key}@@".format(key=key)
        if pattern not in cfg:
            libcalamares.utils.warning("Variable '{key}' is not used.".format(key=key))

    # Check that all patterns exist
    variable_pattern = re.compile(r"@@\w+@@")
    for match in variable_pattern.finditer(cfg):
        variable_name = cfg[match.start() + 2 : match.end() - 2]
        if variable_name not in variables:
            libcalamares.utils.warning(
                "Variable '{key}' is used but not defined.".format(key=variable_name)
            )

    # Do the substitutions
    for key in variables.keys():
        pattern = "@@{key}@@".format(key=key)
        cfg = cfg.replace(pattern, str(variables[key]))

    status = _("Generating Finix configuration")
    libcalamares.job.setprogress(0.05)

    try:
        # Generate hardware.nix with mounted swap device
        subprocess.check_output(
            ["pkexec", "nixos-generate-config", "--root", root_mount_point],
            stderr=subprocess.STDOUT,
        )
    except subprocess.CalledProcessError as e:
        if e.output is not None:
            libcalamares.utils.error(e.output.decode("utf8"))
        return (_("nixos-generate-config failed"), _(e.output.decode("utf8")))

    # nixos-generate-config writes into /etc/nixos; relocate its output to
    # /etc/finix and drop the /etc/nixos directory entirely.
    libcalamares.utils.host_env_process_output(
        ["mkdir", "-p", root_mount_point + "/etc/finix"], None
    )
    libcalamares.utils.host_env_process_output(
        [
            "mv",
            root_mount_point + "/etc/nixos/hardware-configuration.nix",
            root_mount_point + "/etc/finix/hardware-configuration.nix",
        ],
        None,
    )
    libcalamares.utils.host_env_process_output(
        ["rm", "-rf", root_mount_point + "/etc/nixos"], None
    )

    # Read and fix hardware-configuration.nix
    hf = open(root_mount_point + "/etc/finix/hardware-configuration.nix", "r")
    htxt = hf.read()
    hf.close()

    hardware_modified = False

    # Strip NixOS-only options that Finix's module set doesn't define
    # (not-detected.nix import -> hardware.enableRedistributableFirmware,
    # hardware.cpu.*.updateMicrocode, networking.useDHCP, nixpkgs.hostPlatform,
    # ...) and inject hardware.firmware. Without this nixos-install aborts with
    # e.g. "The option 'hardware.enableRedistributableFirmware' does not exist".
    try:
        htxt_finix = finixify_hardware_config(htxt)
        if htxt_finix != htxt:
            htxt = htxt_finix
            hardware_modified = True
    except Exception as e:
        libcalamares.utils.warning(
            "finixify_hardware_config failed, using raw nixos-generate-config "
            "output (install may fail on NixOS-only options): {}".format(e)
        )

    # Fix btrfs subvolume configuration if needed
    htxt_fixed = fix_btrfs_subvolumes(htxt, gs.value("partitions"))
    if htxt_fixed != htxt:
        htxt = htxt_fixed
        hardware_modified = True

    # Check for unfree stuff in hardware-configuration.nix
    search = re.search(r"boot\.extraModulePackages = \[ (.*) \];", htxt)

    # Check if any extraModulePackages are defined, and remove if only free packages are allowed
    if search is not None and free:
        expkgs = search.group(1).split(" ")
        for pkg in expkgs:
            p = ".".join(pkg.split(".")[3:])
            # Check package p is unfree
            isunfree = subprocess.check_output(
                [
                    "nix-instantiate",
                    "--eval",
                    "--strict",
                    "-E",
                    "with import <nixpkgs> {{}}; pkgs.linuxKernel.packageAliases.linux_default.{}.meta.unfree".format(
                        p
                    ),
                    "--json",
                ],
                stderr=subprocess.STDOUT,
            )
            if isunfree == b"true":
                libcalamares.utils.warning(
                    "{} is marked as unfree, removing from hardware-configuration.nix".format(
                        p
                    )
                )
                expkgs.remove(pkg)
        htxt = re.sub(
            r"boot\.extraModulePackages = \[ (.*) \];",
            "boot.extraModulePackages = [ {}];".format(
                "".join(map(lambda x: x + " ", expkgs))
            ),
            htxt,
        )
        hardware_modified = True

    # Write the hardware-configuration.nix file if modified
    if hardware_modified:
        libcalamares.utils.host_env_process_output(
            [
                "cp",
                "/dev/stdin",
                root_mount_point + "/etc/finix/hardware-configuration.nix",
            ],
            None,
            htxt,
        )

    # Write the configuration.nix file
    libcalamares.utils.host_env_process_output(["cp", "/dev/stdin", config], None, cfg)

    # Write the flake.nix that makes the installed system a Finix system (finit PID 1).
    flakepath = os.path.join(root_mount_point, "etc/finix/flake.nix")
    libcalamares.utils.host_env_process_output(
        ["cp", "/dev/stdin", flakepath], None, build_flake(needs)
    )

    # Write sessions.nix (always imported by the flake; may be a no-op module).
    sessionspath = os.path.join(root_mount_point, "etc/finix/sessions.nix")
    libcalamares.utils.host_env_process_output(
        ["cp", "/dev/stdin", sessionspath], None, build_sessions_nix(needs)
    )

    # Write branding.nix (always imported: Finix-labelled limine boot menu).
    brandingpath = os.path.join(root_mount_point, "etc/finix/branding.nix")
    libcalamares.utils.host_env_process_output(
        ["cp", "/dev/stdin", brandingpath], None, BRANDING_NIX
    )

    # Write the vendored Plasma module only when the plasma session was
    # selected (the flake imports it conditionally too).
    if needs["plasma"]:
        plasmapath = os.path.join(root_mount_point, "etc/finix/plasma.nix")
        libcalamares.utils.host_env_process_output(
            ["cp", "/dev/stdin", plasmapath], None, PLASMA_NIX
        )

    # Turn the generated /etc/finix into a git repository before running
    # `nixos-install --flake`. Reason: on a plain (non-git) path flake, Nix
    # hashes the directory, then writes flake.lock into it while resolving the
    # finix + nixpkgs inputs; that mutates the directory and invalidates the
    # pinned hash, producing "error: NAR hash mismatch in input 'path:...'".
    # A git-tree flake is hashed from the committed tree, so the later
    # flake.lock write (untracked) no longer perturbs the source hash.
    nixosDir = os.path.join(root_mount_point, "etc/finix")
    try:
        subprocess.check_output(["git", "init", "-q", nixosDir], stderr=subprocess.STDOUT)
        subprocess.check_output(["git", "-C", nixosDir, "add", "-A"], stderr=subprocess.STDOUT)
        subprocess.check_output(
            [
                "git", "-C", nixosDir,
                "-c", "user.email=installer@finix.local",
                "-c", "user.name=Finix Installer",
                "commit", "-q", "-m", "Finix generated system configuration",
            ],
            stderr=subprocess.STDOUT,
        )
    except subprocess.CalledProcessError as e:
        libcalamares.utils.warning(
            "git init of {} failed (flake install may hit a NAR hash mismatch): {}".format(
                nixosDir, e.output
            )
        )

    status = _("Installing Finix")
    libcalamares.job.setprogress(INSTALL_PROGRESS_START)

    try:
        subprocess.check_output(
            ["pkexec", "chmod", "755", root_mount_point],
            stderr=subprocess.STDOUT,
        )
    except subprocess.CalledProcessError as e:
        libcalamares.utils.warning("Failed to set permissions on {}: {}".format(root_mount_point, e.output))

    # Activate the target's swap partition(s) for the duration of the install:
    # the live ISO has no swap, and heavy source builds (noctalia, niri) can
    # otherwise stall the whole machine on low-RAM systems.
    for part in gs.value("partitions"):
        if part.get("fs") == "linuxswap" and part.get("device"):
            try:
                subprocess.check_output(
                    ["pkexec", "swapon", part["device"]],
                    stderr=subprocess.STDOUT,
                )
                libcalamares.utils.debug(
                    "enabled swap on {} for the install".format(part["device"])
                )
            except subprocess.CalledProcessError as e:
                # already on / not formatted yet / zram-only setups: harmless
                libcalamares.utils.debug(
                    "swapon {} skipped: {}".format(part.get("device"), e.output)
                )

    # Nix requires its build directory to have no world-writable parent
    # directories, which rules out anything under /tmp (where Calamares
    # mounts the target). /nix/var/nix/builds satisfies the check BUT on the
    # live ISO it sits on the RAM-backed store overlay — large source builds
    # (niri's cargo target dir, noctalia, wlroots rebuilds) can fill it up,
    # and the kernel then OOM-kills `nix build`.
    # Fix: bind-mount a scratch dir on the TARGET DISK over
    # /nix/var/nix/builds — path keeps its safe parents, data lands on disk.
    build_scratch = os.path.join(root_mount_point, "var/tmp/finix-installer-build")
    build_dir_bound = False
    try:
        subprocess.check_output(
            ["pkexec", "mkdir", "-p", build_scratch, "/nix/var/nix/builds"],
            stderr=subprocess.STDOUT,
        )
        subprocess.check_output(
            ["pkexec", "mount", "--bind", build_scratch, "/nix/var/nix/builds"],
            stderr=subprocess.STDOUT,
        )
        build_dir_bound = True
    except subprocess.CalledProcessError as e:
        libcalamares.utils.warning(
            "could not bind-mount the build dir onto the target disk "
            "(large source builds may exhaust the live RAM): {}".format(e.output)
        )

    # build nixos-install command
    nixosInstallCmd = [ "pkexec" ]
    nixosInstallCmd.extend(generateProxyStrings())
    nixosInstallCmd.extend(
        [
            "nixos-install",
            "--no-root-passwd",
            "--root",
            root_mount_point,
            # Build the installed system from the generated Finix flake (finit PID 1),
            # not a stock NixOS configuration.nix.
            "--flake",
            os.path.join(root_mount_point, "etc/finix") + "#finixos",
            # Serialize derivation builds: with many sessions selected,
            # several large from-source builds (wlroots, niri, noctalia)
            # would otherwise run at once and exhaust memory on small
            # machines. Each build still uses every core.
            "--max-jobs",
            "1",
        ]
    )
    if build_cores:
        nixosInstallCmd.extend(["--cores", str(build_cores)])
    nixosInstallCmd.extend(
        [
            "--option",
            "experimental-features",
            "nix-command flakes",
            "--log-format",
            "internal-json",
            "--option",
            "build-dir",
            "/nix/var/nix/builds",
        ]
    )

    progress = NixProgress()

    try:
        output = ""
        proc = subprocess.Popen(
            nixosInstallCmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT
        )
        while True:
            line = proc.stdout.readline().decode("utf-8")
            if not line:
                break

            was_json = progress.handle(line)

            # Keep output for error reporting
            if not was_json:
                output += line
            for log_line in progress.log_messages:
                output += log_line + "\n"

            mapped = INSTALL_PROGRESS_START + progress.fraction * (
                INSTALL_PROGRESS_END - INSTALL_PROGRESS_START
            )
            libcalamares.job.setprogress(mapped)

            for log_line in progress.log_messages:
                libcalamares.utils.debug("nixos-install: {}".format(log_line))
            progress.log_messages.clear()

            if not was_json:
                libcalamares.utils.debug("nixos-install: {}".format(line.strip()))

        exit = proc.wait()
        if exit != 0:
            return (_("Finix installation failed"), _(output))
    except:
        return (_("Finix installation failed"), _("Installation failed to complete"))
    finally:
        # Undo the build-dir bind mount and drop its scratch data from the
        # target disk (also frees the space on the installed system). Must
        # happen on every path or Calamares' umount job would find the
        # target busy.
        if build_dir_bound:
            try:
                subprocess.check_output(
                    ["pkexec", "umount", "/nix/var/nix/builds"],
                    stderr=subprocess.STDOUT,
                )
                subprocess.check_output(
                    ["pkexec", "rm", "-rf", build_scratch],
                    stderr=subprocess.STDOUT,
                )
            except subprocess.CalledProcessError as e:
                libcalamares.utils.warning(
                    "build-dir cleanup failed: {}".format(e.output)
                )

    libcalamares.job.setprogress(INSTALL_PROGRESS_END)
    return None
