# Finix system configuration, generated by the Finix installer.
# Finix uses finit as PID 1 (no systemd), seatd, mdevd, and the Nix package
# manager. Edit this file, then rebuild with:  sudo finix-rebuild switch
# (the system flake lives in /etc/finix)

{ config, pkgs, ... }:

{
  imports =
    [ # Include the results of the hardware scan.
      ./hardware-configuration.nix
    ];

  # --- Finix core (finit init + Nix daemon) ---
  finit.runlevel = 3;
  finit.services.nix-daemon.environment.CURL_CA_BUNDLE = config.security.pki.caBundle;
  services.nix-daemon.enable = true;
  services.nix-daemon.settings.experimental-features = [ "nix-command" "flakes" ];
  services.nix-daemon.settings.trusted-users = [ "root" "@wheel" ];

  # --- seat / device / logging / policy (Finix replacements for systemd bits) ---
  services.seatd.enable = true;
  services.mdevd.enable = true;
  services.dbus.enable = true;
  services.sysklogd.enable = true;
  services.polkit.enable = true;

  # --- networking (dhcpcd + iwd; no NetworkManager/systemd) ---
  services.dhcpcd.enable = true;
  services.iwd.enable = true;

  # --- login: greetd/tuigreet, listing the installed Wayland sessions ---
  programs.sudo.enable = true;
  programs.bash.enable = true;
  services.greetd.enable = true;
  services.greetd.settings.default_session.command = "${pkgs.tuigreet}/bin/tuigreet --time --sessions /run/current-system/sw/share/wayland-sessions";
  hardware.graphics.enable = true;
  fonts.fontconfig.enable = true;
  fonts.enableDefaultPackages = true;

  # Bootloader: limine (UEFI).
  programs.limine.enable = true;
  programs.limine.efiSupport = true;
  programs.limine.settings.editor_enabled = true;
  # No distro artwork behind the boot menu (the Finix limine module defaults
  # to a NixOS wallpaper); keep the plain dark backdrop instead.
  programs.limine.settings.wallpaper = [ ];
  boot.loader.efi.canTouchEfiVariables = true;

  # Use latest kernel.
  boot.kernelPackages = pkgs.linuxPackages_latest;

  networking.hostName = "finix"; # Define your hostname.
  # networking.wireless.enable = true;  # Enables wireless support via wpa_supplicant.

  # Configure network proxy if necessary
  # networking.proxy.default = "http://user:password@proxy:port/";
  # networking.proxy.noProxy = "127.0.0.1,localhost,internal.domain";

  # Set your time zone.
  time.timeZone = "UTC";

  # Select internationalisation properties.
  i18n.defaultLocale = "en_US.UTF-8";

  i18n.extraLocaleSettings = {
    LC_ADDRESS = "en_US.UTF-8";
    LC_IDENTIFICATION = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_NAME = "en_US.UTF-8";
    LC_NUMERIC = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_TELEPHONE = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
  };

  # --- desktop: labwc (lightweight Wayland compositor) ---
  programs.labwc.enable = true;

  # Configure console keymap
  hardware.console.keyMap = "us";

  # Define a user account. Don't forget to set a password with ‘passwd’.
  users.users."finix" = {
    isNormalUser = true;
    description = "Finix User";
    extraGroups = [ "wheel" "video" config.services.seatd.group ];
    packages = with pkgs; [];
  };

  # Automatic login is not supported by the Finix installer yet
  # (services.getty.autologinUser does not exist on Finix; greetd handles login).

  # List packages installed in system profile. To search, run:
  # $ nix search wget
  environment.systemPackages = with pkgs; [
    vim
    git
    wget
    foot # Wayland terminal
    firefox # web browser (plain package; Finix has no programs.firefox module)
    # usermod & friends in /run/current-system/sw/bin: the installer's password
    # step runs `chroot <target> usermod -p <hash> <user>` and resolves the
    # binary through the target's PATH; finix's shadow module only ships the
    # setuid wrappers (su/passwd), not the plain tools. Also useful post-install.
    shadow
    # `sudo finix-rebuild switch` (or boot): stages /etc/finix into git —
    # required, the flake only sees git-tracked files — then rebuilds.
    (writeShellScriptBin "finix-rebuild" ''
      set -e
      ${git}/bin/git -C /etc/finix add -A
      exec ${nixos-rebuild}/bin/nixos-rebuild "''${1:-switch}" --flake /etc/finix#finixos "''${@:2}"
    '')
    # fastfetch with the classic NixOS ascii logo recolored to Finix red/gray.
    (writeShellScriptBin "fastfetch" ''
      exec ${fastfetch}/bin/fastfetch --logo nixos --logo-color-1 "31" --logo-color-2 "90" "$@"
    '')
  ];

  # Enable the OpenSSH daemon (optional).
  # services.openssh.enable = true;

  # NOTE: Finix does not use NixOS's system.stateVersion; it is intentionally omitted.
}
